// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using System.Linq;
using Maestro.Quest.Creation;
using Newtonsoft.Json.Linq;
using static Maestro.Quest.Programs.CapabilitySchema;
namespace Maestro.Quest.Programs
{
    internal static class AudioFacts
    {
        static ProgramDataType Type(string fields)=>ProgramDataType.Read(JObject.Parse("{\"record\":"+fields+"}"));
        static string[] Features=>new[]{AudioSchema.Feature};
        internal static BehaviourCatalog.FactDefinition List()=>new("audio.source.list",Type("{\"total\":\"number\",\"next\":\"number\",\"entries\":{\"list\":{\"record\":{\"id\":\"text\",\"name\":\"text\",\"kind\":\"text\",\"revision\":\"number\"}}}}"),"Reusable room sounds","List four saved audio sources at a time in stable ID order. next=-1 ends the list. Reads never open a connection or play a sound.",Object(new JObject {["offset"]=Number(0,32,true)}),new JObject {["offset"]=0},(c,a)=>{
            if(!c.Editor)return null;var all=c.Editor.AudioSources();int offset=(int)a["offset"];var page=all.Skip(offset).Take(4).ToArray();
            return ProgramValue.Literal(new JObject {["total"]=all.Length,["next"]=offset+page.Length<all.Length?offset+page.Length:-1,["entries"]=new JArray(page.Select(s=>new JObject {["id"]=s.id,["name"]=s.name,["kind"]=s.kind,["revision"]=c.Editor.AudioRevision(s.id)}))},Type("{\"total\":\"number\",\"next\":\"number\",\"entries\":{\"list\":{\"record\":{\"id\":\"text\",\"name\":\"text\",\"kind\":\"text\",\"revision\":\"number\"}}}}"));
        },features:Features);
        internal static BehaviourCatalog.FactDefinition Definition()=>new("audio.source.definition",Type("{\"id\":\"text\",\"revision\":\"number\",\"definition\":{\"record\":{\"name\":\"text\",\"kind\":\"text\",\"clip\":{\"record\":{\"assetHash\":\"text\",\"seconds\":\"number\"}},\"tone\":{\"record\":{\"wave\":\"text\",\"frequency\":\"number\",\"endFrequency\":\"number\",\"seconds\":\"number\",\"attack\":\"number\",\"release\":\"number\",\"seed\":\"number\"}}}}}"),"Sound definition","Read the exact saved source and current edit revision. Active playback may retain an earlier revision. Missing IDs are unavailable, never silently substituted. kind selects tone or clip; the other block contains inactive defaults. Pass only the selected block when saving.",Object(new JObject {["id"]=AudioSchema.Id()}),new JObject {["id"]=new string('0',32)},(c,a)=>{var s=c.Editor?c.Editor.ReadAudio((string)a["id"]):null;return s==null?null:ProgramValue.Literal(new JObject {["id"]=s.id,["revision"]=c.Editor.AudioRevision(s.id),["definition"]=AudioSchema.ObserveSource(s)});},features:Features,version:2);
        internal static BehaviourCatalog.FactDefinition Emitters()=>new("object.audioEmitters",Type("{\"revision\":\"number\",\"entries\":{\"list\":{\"record\":{\"emitter\":\"text\",\"source\":\"text\"}}}}"),"Object sounds","List all saved sound emitter keys and exact source IDs on an object. No playback is started.",Object(new JObject {["target"]=AudioSchema.Target()}),new JObject {["target"]="maestro"},(c,a)=>{var d=c.Editor?c.Editor.Read((string)a["target"]):null;if(d==null)return null;return ProgramValue.Literal(new JObject {["revision"]=c.Editor.ObjectRevision(d.id),["entries"]=new JArray((d.audioEmitters??System.Array.Empty<RoomAudioEmitter>()).Select(e=>new JObject {["emitter"]=e.id,["source"]=e.source}))},Type("{\"revision\":\"number\",\"entries\":{\"list\":{\"record\":{\"emitter\":\"text\",\"source\":\"text\"}}}}"));},features:Features);
        internal static BehaviourCatalog.FactDefinition Emitter()=>new("object.audioEmitter",Type("{\"revision\":\"number\",\"configured\":\"boolean\",\"definition\":{\"record\":{\"source\":\"text\",\"part\":\"text\",\"joint\":\"text\",\"position\":{\"record\":{\"x\":\"number\",\"y\":\"number\",\"z\":\"number\"}},\"role\":\"text\",\"spatial\":\"boolean\",\"gain\":\"number\",\"distance\":{\"record\":{\"minimum\":\"number\",\"maximum\":\"number\"}}}}}"),"Sound emitter settings","Saved attachment and current object edit revision. configured=false returns inert default fields and an empty source ID for editing; it does not add an emitter.",Query(),Example(),(c,a)=>{var d=c.Editor?c.Editor.Read((string)a["target"]):null;if(d==null)return null;var e=d.audioEmitters?.FirstOrDefault(x=>x.id==(string)a["emitter"]);return ProgramValue.Literal(new JObject {["revision"]=c.Editor.ObjectRevision(d.id),["configured"]=e!=null,["definition"]=AudioSchema.Encode(e??new RoomAudioEmitter {source=""})});},features:Features);
        internal static JObject Query()=>Object(new JObject {["target"]=AudioSchema.Target(),["emitter"]=AudioSchema.Key()});
        static JObject Example()=>new(){["target"]="maestro",["emitter"]="beep"};
        internal static BehaviourCatalog.FactDefinition Playback()=>new("audio.playback",Type("{\"playing\":\"boolean\",\"instance\":\"text\",\"source\":\"text\",\"sourceRevision\":\"number\",\"seconds\":\"number\"}"),"Active sound playback","Current transient instance and consumed PCM cursor for this emitter. playing=false gives empty identity fields when no instance is active. Completed/cancelled/failed outcomes belong to the owning action's receipt/trace. This is not proof that the user heard sound. Neither saving nor reading this fact starts audio.",Query(),Example(),(c,a)=>{if(!c.Editor||c.Editor.Read((string)a["target"])==null)return null;var audio=c.Editor.GetComponent<WorldAudio>();var v=audio?audio.Current((string)a["target"],(string)a["emitter"]):null;return ProgramValue.Literal(new JObject {["playing"]=v!=null,["instance"]=v?.Id??"",["source"]=v?.Source??"",["sourceRevision"]=v?.SourceRevision??0,["seconds"]=v?.Cursor??0});},features:Features);
    }
}
