// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using System.Collections.Generic;
using System.Linq;
using Maestro.Quest.Creation;
using Maestro.Quest.Interaction;
using Newtonsoft.Json.Linq;
using UnityEngine;
using static Maestro.Quest.Programs.CapabilitySchema;
namespace Maestro.Quest.Programs {
    internal sealed class ConnectionCapability:CapabilityModule {
        internal const string Feature="physicalConnections.v1",SliderFeature="physicalSliders.v1";
        public override string Id=>"object.connection.edit";
        public override string Label=>"Connect physical pieces";
        public override string Duration=>"instant";
        public override IReadOnlyList<string> Channels=>new[]{"wholeTarget"};
        public override IReadOnlyList<string> Requirements=>new[]{"target.created","target.unheld","source.revision.current","storage.writable"};
        public override string Description=>"One connection component for fixed joins, rotating hinges and bounded sliders. Configure saved local frames without moving; attach creates a fixed join at the two CURRENT poses while physics is paused; align explicitly moves the owner to its connected frame (angle must be zero for fixed joins). The slide operation explicitly aligns a slider at distance within its saved limits. Slider distances, target and speed use connected-object local metres along its frame +X; world distance/speed scales with that object. Spring gains are N/m and N*s/m; force caps drive force in N. Motor uses damped velocity control and can stall under load. Owner needs solid/bouncy physics; the other member may be fixed. Zero breakForce/breakTorque means unbreakable; positive limits are newtons/newton-metres. A PhysX break releases the body, emits object.connection.broken and stays broken through pause/resume. Rearm requires the exact members already aligned and clears only the live break latch; it does not save, teleport or add Undo. Configure/attach/align/slide save once with one live-pose Undo and explicitly reset break state after successful persistence. Remove releases the component. Failed edits leave the original poses/connection. Connected-body collisions are suppressed; other collisions remain. Missing, misaligned or animation-owned members freeze the owner. Sixteen total connections, one outgoing link per creation, no cycles. Frames use +X as hinge axis and +Y as zero direction. Scaling/teleporting can require repair. Break state is runtime play state, not a saved damage field: workspace reload reconstructs the saved definition and still requires alignment. No automatic socket search, welding mesh merge or guessed identity. Temporary saved edits stay in their fork.";
        internal static JObject Frame()=>Object(new JObject{["position"]=DrawingData.Point(),["rotation"]=Vector(true)});
        static JObject Limits()=>Object(new JObject{["enabled"]=new JObject{["type"]="boolean"},["minimum"]=Number(-170,170),["maximum"]=Number(-170,170)});
        static JObject Drive()=>Object(new JObject{["mode"]=Choice("passive","spring","motor"),["target"]=Number(-170,170),["spring"]=Number(0,100),["damper"]=Number(0,20),["speed"]=Number(-360,360),["force"]=Number(0,20)});
        static JObject Slider()=>Object(new JObject{["minimum"]=Number(-1,1),["maximum"]=Number(-1,1),["mode"]=Choice("passive","spring","motor"),["target"]=Number(-1,1),["spring"]=Number(0,500),["damper"]=Number(0,50),["speed"]=Number(-.5,.5),["force"]=Number(0,100)});
        static JObject DefinitionVariant(string kind){var fields=new JObject{["kind"]=Choice(kind),["enabled"]=new JObject{["type"]="boolean"},["breakForce"]=Number(0,10000),["breakTorque"]=Number(0,10000),["ownerFrame"]=Frame(),["connectedFrame"]=Frame()};fields["kind"]["x-static"]=true;if(kind=="hinge"){fields["limits"]=Limits();fields["drive"]=Drive();}if(kind=="slider")fields["slide"]=Slider();var schema=Object(fields);schema["title"]=kind=="fixed"?"Rigid connection":kind=="slider"?"Sliding connection":"Rotating hinge";if(kind=="slider")schema["x-features"]=new JArray(SliderFeature);return schema;}
        internal static JObject DefinitionSchema()=>new(){["type"]="object",["title"]="Connection type",["x-discriminators"]=new JArray("kind"),["oneOf"]=new JArray(DefinitionVariant("hinge"),DefinitionVariant("fixed"),DefinitionVariant("slider"))};
        static JObject Variant(string operation){var fields=new JObject{["operation"]=Choice(operation),["target"]=DrawingData.Target(),["revision"]=Revision()};fields["operation"]["x-static"]=true;
            if(operation!="remove")fields["connected"]=DrawingData.Target();if(operation=="configure")fields["definition"]=DefinitionSchema();if(operation=="align")fields["angle"]=Number(-170,170);if(operation=="slide")fields["distance"]=Number(-1,1);if(operation=="attach"){fields["breakForce"]=Number(0,10000);fields["breakTorque"]=Number(0,10000);}
            var schema=CurrentInputs(Object(fields),"object.connection","revision",new JObject{["target"]="target"});schema["format"]="connectionConfiguration";schema["title"]=operation;schema["x-features"]=operation=="slide"?new JArray(Feature,SliderFeature):new JArray(Feature);return schema;}
        public override JObject InputSchema=>new(){["type"]="object",["x-discriminators"]=new JArray("operation"),["oneOf"]=new JArray(Variant("configure"),Variant("attach"),Variant("align"),Variant("slide"),Variant("rearm"),Variant("remove"))};
        internal static JObject Definition(RoomConnection definition){var result=JObject.Parse(JsonUtility.ToJson(definition));result.Remove("version");result.Remove("connected");if(definition.kind!="hinge"){result.Remove("limits");result.Remove("drive");}if(definition.kind!="slider")result.Remove("slide");return result;}
        public override JObject Example=>new(){["operation"]="configure",["target"]=new string('0',32),["revision"]=1,["connected"]=new string('1',32),["definition"]=Definition(new RoomConnection())};
        static RoomConnection Read(JObject args){if((string)args["operation"]=="attach")return new RoomConnection{kind="fixed",connected=(string)args["connected"],breakForce=(float)args["breakForce"],breakTorque=(float)args["breakTorque"]};if((string)args["operation"]!="configure")return null;var value=JsonUtility.FromJson<RoomConnection>(args["definition"].ToString());value.connected=(string)args["connected"];return value;}
        public override bool Validate(JObject args,out string error){error="Choose different connection members";if(args["connected"]!=null&&(string)args["target"]==(string)args["connected"])return false;error=null;return (string)args["operation"]!="configure"||Read(args).Validate((string)args["target"],out error);}
        public override BehaviourCatalog.Claim[] Claims(JObject args)=>args["connected"]==null?base.Claims(args):new[]{new BehaviourCatalog.Claim((string)args["target"],"wholeTarget"),new BehaviourCatalog.Claim((string)args["connected"],"wholeTarget")};
        public override bool CanRun(CapabilityContext context,JObject args,out string error)=>context.Target(args,out _,out error)&&context.Editor.PrepareConnection((string)args["target"],(int)args["revision"],(string)args["operation"],(string)args["connected"],Read(args),(float?)args["distance"]??(float?)args["angle"]??0,out _,out error);
        public override bool Start(CapabilityContext context,string run,JObject args,out CapabilityOperation operation,out string error){operation=null;if(!CanRun(context,args,out error)||!context.Editor.EditConnection((string)args["target"],(int)args["revision"],(string)args["operation"],(string)args["connected"],Read(args),(float?)args["distance"]??(float?)args["angle"]??0,out error))return false;operation=new CompletedCapability();return true;}
        static JObject SettingsSchema()=>Object(new JObject{["enabled"]=new JObject{["type"]="boolean"},["kind"]=Choice("hinge","fixed","slider"),["breakForce"]=Number(0,10000),["breakTorque"]=Number(0,10000)});
        static JObject Settings(RoomConnection h)=>new(){["enabled"]=h.enabled,["kind"]=h.kind,["breakForce"]=h.breakForce,["breakTorque"]=h.breakTorque};
        static RoomObjectData Data(BehaviourCatalog.FactContext context,JObject args)=>context.Editor?context.Editor.Read((string)args["target"]):null;
        static JObject TargetSchema()=>Object(new JObject{["target"]=DrawingData.Target()});
        static JObject TargetExample()=>new(){["target"]=new string('0',32)};
        static JObject FactSchema()=>Object(new JObject{["revision"]=Revision(),["configured"]=new JObject{["type"]="boolean"},["connected"]=Text(null,32),["definition"]=SettingsSchema()});
        public static BehaviourCatalog.FactDefinition Fact()=>new("object.connection",OutputType(FactSchema()),"Saved physical connection","Shared settings and current object revision. configured=false returns inert defaults. connected is the exact ID or empty. Read frames with object.connection.frame and type-specific settings with object.connection.hinge or object.connection.slider. Broken play state is read separately.",TargetSchema(),TargetExample(),(c,a)=>{var d=Data(c,a);if(d==null||d.IsBuiltIn)return null;var h=d.connections?.FirstOrDefault();return ProgramValue.Literal(new JObject{["revision"]=c.Editor.ObjectRevision(d.id),["configured"]=h!=null,["connected"]=h?.connected??"",["definition"]=Settings(h??new RoomConnection{enabled=false})});},features:new[]{Feature});
        public static BehaviourCatalog.FactDefinition TuningFact()=>new("object.connection.hinge",OutputType(Object(new JObject{["revision"]=Revision(),["limits"]=Limits(),["drive"]=Drive()})),"Rotating hinge settings","Limits and drive settings for a configured rotating hinge; unavailable for fixed or absent connections. Read this and the local frames at the same object revision before configuring.",TargetSchema(),TargetExample(),(c,a)=>{var d=Data(c,a);var h=d?.connections?.FirstOrDefault();if(h==null||h.kind!="hinge")return null;return ProgramValue.Literal(new JObject{["revision"]=c.Editor.ObjectRevision(d.id),["limits"]=JObject.Parse(JsonUtility.ToJson(h.limits)),["drive"]=JObject.Parse(JsonUtility.ToJson(h.drive))});},features:new[]{Feature});
        public static BehaviourCatalog.FactDefinition SliderFact()=>new("object.connection.slider",OutputType(Object(new JObject{["revision"]=Revision(),["slide"]=Slider()})),"Sliding connection settings","Limits span at least 0.005 connected-object local metres. Positive travel/speed follows the connected frame +X. Spring target must be inside its limits. Read frames at this same revision before editing. Unavailable for other connection kinds.",TargetSchema(),TargetExample(),(c,a)=>{var d=Data(c,a);var h=d?.connections?.FirstOrDefault();if(h?.kind!="slider")return null;return ProgramValue.Literal(new JObject{["revision"]=c.Editor.ObjectRevision(d.id),["slide"]=JObject.Parse(JsonUtility.ToJson(h.slide))});},features:new[]{Feature,SliderFeature});
        public static BehaviourCatalog.FactDefinition TravelFact()=>new("object.connection.travel",ProgramType.Number,"Live sliding distance","Signed anchor distance along the connected frame +X, in connected-object local metres. Unavailable unless the slider and exact other object are loaded. Read object.connection.state to distinguish active, paused or broken; a distance alone does not prove a press or contact cause. Use ordinary condition waits with separate press/release thresholds for hysteresis.",TargetSchema(),TargetExample(),(c,a)=>{var item=c.Editor?c.Editor.Find((string)a["target"]):null;var v=item?item.GetComponent<RoomConnectionView>():null;return v&&v.HasTravel?new ProgramValue(v.Travel):null;},features:new[]{Feature,SliderFeature});
        public static BehaviourCatalog.FactDefinition FrameFact()=>new("object.connection.frame",OutputType(Object(new JObject{["revision"]=Revision(),["configured"]=new JObject{["type"]="boolean"},["frame"]=Frame()})),"Saved connection frame","One local frame within the program-value budget. Use the same object revision for both sides; reading never aligns or starts physics.",Object(new JObject{["target"]=DrawingData.Target(),["side"]=Choice("owner","connected")}),new JObject{["target"]=new string('0',32),["side"]="owner"},(c,a)=>{var d=Data(c,a);if(d==null||d.IsBuiltIn)return null;var h=d.connections?.FirstOrDefault();var frame=h==null?new ConnectionFrame():(string)a["side"]=="owner"?h.ownerFrame:h.connectedFrame;return ProgramValue.Literal(new JObject{["revision"]=c.Editor.ObjectRevision(d.id),["configured"]=h!=null,["frame"]=JObject.Parse(JsonUtility.ToJson(frame))});},features:new[]{Feature});
        public static BehaviourCatalog.FactDefinition State()=>new("object.connection.state",ProgramDataType.Read(JObject.Parse("{\"record\":{\"phase\":\"text\",\"active\":\"boolean\",\"broken\":\"boolean\",\"angle\":\"number\",\"error\":\"text\"}}")),"Live physical connection","active means an admitted native constraint. broken is latched until an explicit successful configure/attach/align/rearm or workspace recreation. angle is signed degrees about the saved +X axis, not a revolution count or fixed-joint freedom. This reading does not authorize edits or identify the cause of a break.",TargetSchema(),TargetExample(),(c,a)=>{var item=c.Editor?c.Editor.Find((string)a["target"]):null;if(!item)return null;var v=item.GetComponent<RoomConnectionView>();return ProgramValue.Literal(new JObject{["phase"]=v?v.Phase:"absent",["active"]=v&&v.Active,["broken"]=v&&v.Broken,["angle"]=v?v.Angle:0,["error"]=v?v.Error:""});},features:new[]{Feature});
        public static BehaviourCatalog.EventDefinition BreakEvent()=>new("object.connection.broken","Physical connection broke","A native physical connection broke while room physics was running. Value/source is its owner object ID. connected is the exact other ID; kind is hinge, fixed or slider; forceLimit and torqueLimit are configured limits, not measured impact or proof of cause. Emitted once per admitted break; pause/Stop/retirement do not emit it and missed events are not replayed. Rearm or align explicitly to reconnect.",Object(new JObject{["connected"]=Text("^[a-f0-9]{32}$",32),["kind"]=Choice("hinge","fixed","slider"),["forceLimit"]=Number(0,10000),["torqueLimit"]=Number(0,10000)}),objectEvent:true,features:new[]{Feature});
    }
}
