// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using Newtonsoft.Json.Linq;
using static Maestro.Quest.Programs.CapabilitySchema;
namespace Maestro.Quest.Programs {
    internal static class ContainerPouringFacts {
        internal const string Feature="containerPouring.v1";
        internal static BehaviourCatalog.FactDefinition Live()=>new("object.container.live",OutputType(Object(new JObject{
            ["sessionId"]=Text("^[a-f0-9]{32}$",32),["phase"]=Choice("idle","flowing","failed"),["contents"]=Object(new JObject{["amountMl"]=Number(0,1000000),["savedAmountMl"]=Number(0,1000000),["capacityMl"]=Number(1,1000000),["transferredMl"]=Number(0,8000000),["spilledMl"]=Number(0,8000000)}),["temporary"]=new JObject{["type"]="boolean"},["error"]=Text("^.{0,128}$",128)})),"Live container contents","Current native liquid quantity during physical pouring or scooping, separate from the last accepted object.container definition. Flowing contents are published together after 0.3 seconds without flow, at grip release, pause or Save, at bounded ten-second checkpoints, and before an empty participating vessel adopts a different liquid identity or colour; one Undo restores that episode. Failed publication reverts all episode quantities and stops further pouring until physics is restarted. transferredMl/spilledMl are outgoing pouring totals for this source in the current episode, reset after publication. Scooping has separate object.container.scooping counters. No per-drop rigidbodies, terrain pools, carried fluid mass or mixing. Shared bounded buoyancy/drag is described by object.medium. Amounts use logical millilitres independent of visual resizing.",Object(new JObject{["target"]=DrawingData.Target()}),new JObject{["target"]=new string('0',32)},(c,a)=>{var data=c.Editor?c.Editor.Liquids?.Observe((string)a["target"]):null;return data==null?null:ProgramValue.Literal(data);},features:new[]{Feature});
        internal static BehaviourCatalog.EventDefinition Poured()=>new("object.container.poured","A physical pour was saved","A native pouring episode was accepted by the shared room journal (or temporary fork). Value/source is the outgoing vessel ID. transferredMl is the total received by containers; spilledMl left the bounded container model, and does not imply a persistent puddle. receivers counts distinct receiving containers. Emitted after successful publication only; failed saves, cancellation, Undo and reload do not emit/replay it. Continuous flow checkpoints after ten seconds. Before an empty participating vessel changes liquid identity or colour, the prior episode publishes first; new intake is reconsidered next tick. Each outgoing total therefore retains its own liquid identity. Paused lifecycle listeners may miss the event; inspect current contents instead.",Object(new JObject{["transferredMl"]=Number(0,8000000),["spilledMl"]=Number(0,8000000),["receivers"]=Number(0,16,true),["liquid"]=Text("^[a-zA-Z][a-zA-Z0-9_]{0,31}$",32),["temporary"]=new JObject{["type"]="boolean"}}),objectEvent:true,features:new[]{Feature});
    }
}
