// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using System;
using System.Linq;
using Maestro.Quest.Creation;
using Newtonsoft.Json.Linq;
using UnityEngine;
using static Maestro.Quest.Programs.CapabilitySchema;
namespace Maestro.Quest.Programs
{
    internal static class DrawingSurfaceFacts
    {
        static ProgramDataType Type(string fields)=>ProgramDataType.Read(JObject.Parse("{\"record\":"+fields+"}"));
        static readonly ProgramDataType OverviewType=Type("{\"target\":\"text\",\"revision\":\"number\",\"surfaces\":{\"list\":{\"record\":{\"id\":\"text\",\"part\":\"text\",\"enabled\":\"boolean\",\"strokes\":\"number\"}}}}");
        static readonly ProgramDataType StrokesType=Type("{\"revision\":\"number\",\"total\":\"number\",\"offset\":\"number\",\"strokes\":{\"list\":{\"record\":{\"id\":\"text\",\"points\":\"number\",\"radius\":\"number\"}}}}");
        static readonly ProgramDataType StrokeType=Type("{\"revision\":\"number\",\"total\":\"number\",\"offset\":\"number\",\"radius\":\"number\",\"color\":{\"record\":{\"r\":\"number\",\"g\":\"number\",\"b\":\"number\",\"a\":\"number\"}},\"points\":{\"list\":{\"record\":{\"x\":\"number\",\"y\":\"number\",\"z\":\"number\"}}}}");
        static JObject Query(bool surface=false,bool stroke=false){var p=new JObject {["target"]=DrawingData.Target()};if(surface)p["surface"]=Text("^[a-zA-Z][a-zA-Z0-9_]{0,31}$",32);if(stroke){p["revision"]=Revision();p["stroke"]=Text("^[a-f0-9]{32}$",32);p["offset"]=Number(0,512,true);}return Object(p);}
        static JObject Example(bool surface=false,bool stroke=false){var p=new JObject {["target"]=new string('0',32)};if(surface)p["surface"]="Front";if(stroke){p["revision"]=1;p["stroke"]=new string('1',32);p["offset"]=0;}return p;}
        static RoomObjectData Read(BehaviourCatalog.FactContext c,JObject a)=>c.Editor?c.Editor.Read((string)a["target"]):null;
        public static BehaviourCatalog.FactDefinition Overview()=>new("object.surfaces",OverviewType,"Object drawing surfaces",
            "All configured drawing patches (at most four), with the current object revision. Reads do not infer surfaces from a mesh or collider. part is empty for object-local coordinates. Mark counts remain when drawing is disabled. Read object.surface and object.surface.strokes for exact editable definitions.",Query(),Example(),(c,a)=>{var d=Read(c,a);return d==null?null:ProgramValue.Literal(new JObject {["target"]=d.id,["revision"]=c.Editor.ObjectRevision(d.id),["surfaces"]=new JArray((d.surfaces??Array.Empty<DrawingSurface>()).Select(s=>new JObject {["id"]=s.id,["part"]=s.part,["enabled"]=s.enabled,["strokes"]=s.strokes.Length}))},OverviewType);},features:new[]{DrawingSurfaceCapability.Feature});
        public static BehaviourCatalog.FactDefinition Definition()=>new("object.surface",Type("{\"revision\":\"number\",\"part\":\"text\",\"position\":{\"record\":{\"x\":\"number\",\"y\":\"number\",\"z\":\"number\"}},\"rotation\":{\"record\":{\"x\":\"number\",\"y\":\"number\",\"z\":\"number\",\"w\":\"number\"}},\"width\":\"number\",\"height\":\"number\",\"enabled\":\"boolean\",\"geometry\":{\"record\":{\"shape\":\"text\",\"curvatureRadius\":\"number\"}}}"),"Drawing surface definition",
            "Exact plane/cylinder/sphere configuration in its object's or recipe part's local axes. The tangent origin faces -Z; shape and curvatureRadius define the same editable surface mapping. This is saved configuration, not the current animated world pose; a patch does not follow skin deformation or imported bones.",Query(true),Example(true),(c,a)=>{var d=Read(c,a);var s=d?.surfaces?.FirstOrDefault(x=>x.id==(string)a["surface"]);if(s==null)return null;var j=JObject.Parse(JsonUtility.ToJson(s));foreach(var key in new[]{"version","id","strokes"})j.Remove(key);j.Remove("shape");j.Remove("curvatureRadius");j["geometry"]=new JObject {["shape"]=s.Kind,["curvatureRadius"]=s.curvatureRadius};j["revision"]=c.Editor.ObjectRevision(d.id);return ProgramValue.Literal(j);},features:new[]{DrawingSurfaceCapability.Feature});
        public static BehaviourCatalog.FactDefinition Strokes(){var q=Query(true);((JObject)q["properties"])["revision"]=Revision();((JObject)q["properties"])["offset"]=Number(0,32,true);((JArray)q["required"]).Add("revision");((JArray)q["required"]).Add("offset");var example=Example(true);example["revision"]=1;example["offset"]=0;
            return new("object.surface.strokes",StrokesType,"Surface stroke identities","Read up to six saved stroke identities in creation order. Exact current object revision is required; offset equal to total returns an empty page. Read object.surface.stroke for colour and points; IDs survive object copying within their own surface.",q,example,(c,a)=>{var d=Read(c,a);var s=d?.surfaces?.FirstOrDefault(x=>x.id==(string)a["surface"]);int offset=(int)a["offset"];if(s==null||c.Editor.ObjectRevision(d.id)!=(int)a["revision"]||offset>s.strokes.Length)return null;return ProgramValue.Literal(new JObject {["revision"]=(int)a["revision"],["total"]=s.strokes.Length,["offset"]=offset,["strokes"]=new JArray(s.strokes.Skip(offset).Take(6).Select(x=>new JObject {["id"]=x.id,["points"]=x.points.Length,["radius"]=x.radius}))},StrokesType);},features:new[]{DrawingSurfaceCapability.Feature});
        }
        public static BehaviourCatalog.FactDefinition Stroke()=>new("object.surface.stroke",StrokeType,"Surface stroke point page",
            "Read colour, radius and up to six exact surface-coordinate points. Points use patch-local arc metres (equatorial X on spheres); radius uses geometric local metres; z=0, X/Y remain inside the patch including radius. Paged reads refuse stale object revisions. No projection, simplification or ownership is implied.",Query(true,true),Example(true,true),(c,a)=>{var d=Read(c,a);var s=d?.surfaces?.FirstOrDefault(x=>x.id==(string)a["surface"])?.strokes.FirstOrDefault(x=>x.id==(string)a["stroke"]);int offset=(int)a["offset"];if(s==null||c.Editor.ObjectRevision(d.id)!=(int)a["revision"]||offset>s.points.Length)return null;return ProgramValue.Literal(new JObject {["revision"]=(int)a["revision"],["total"]=s.points.Length,["offset"]=offset,["radius"]=s.radius,["color"]=JObject.Parse(JsonUtility.ToJson(s.color)),["points"]=new JArray(s.points.Skip(offset).Take(6).Select(p=>new JObject {["x"]=p.x,["y"]=p.y,["z"]=p.z}))},StrokeType);},features:new[]{DrawingSurfaceCapability.Feature});
    }
}
