// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using System;
using System.Collections.Generic;
using System.Linq;
using Maestro.Quest.Creation;
using Newtonsoft.Json.Linq;
using UnityEngine;
using static Maestro.Quest.Programs.CapabilitySchema;
namespace Maestro.Quest.Programs {
    internal sealed class HeightFieldCapability:CapabilityModule {
        internal const string Feature="heightFields.v1";
        public override string Id=>"object.field.edit";
        public override string Label=>"Configure or reset a sculptable surface";
        public override string Duration=>"instant";
        public override IReadOnlyList<string> Channels=>new[]{"wholeTarget"};
        public override IReadOnlyList<string> Requirements=>new[]{"target.created","target.unheld","source.revision.current","storage.writable","target.physics.fixed"};
        public override string Description=>"Configure one saved height surface on a fixed created object, or remove it. Configure replaces all heights with fillHeight: it is an explicit reset, not a conserving simulation. Frame is root-local; +Y is height and X/Z span width/depth. Choose 4, 8 or 16 cells per side, up to four fields per room. The mesh and its nonconvex collision use the same saved heights; the owner must remain fixed while the field exists. Existing object collision remains separate and can intersect the surface if authored that way. Snow, sand and similar appearance use an editable colour/material label, not different simulators. Fields support shared sculpting, exact paged heights, copy/prototypes, Undo and temporary rooms. There is no gravity flow, melting, fluid pressure, mass, bare-hand sculpting or material transfer in this capability. Moving/scaling the owner moves/scales the surface. Authored local volume is geometric, not conserved physical quantity.";
        internal static JObject DefinitionSchema(){var s=Object(new JObject{["frame"]=Object(new JObject{["position"]=DrawingData.Point(),["rotation"]=Vector(true)}),["width"]=Number(.1,4),["depth"]=Number(.1,4),["cells"]=Number(4,16,true),["maxHeight"]=Number(.005,.5),["material"]=Text("^[a-zA-Z][a-zA-Z0-9_]{0,31}$",32),["color"]=Object(new JObject{["r"]=Number(0,1),["g"]=Number(0,1),["b"]=Number(0,1),["a"]=Number(1,1)})});s["format"]="heightFieldDefinition";return s;}
        internal static JObject SavedSchema(){var s=DefinitionSchema();((JObject)s["properties"])["version"]=Number(1,1,true);((JObject)s["properties"])["heights"]=List(Number(0,.5),25,RoomHeightField.MaximumSamples);((JArray)s["required"]).Add("version");((JArray)s["required"]).Add("heights");s["format"]="heightFieldSaved";s["x-features"]=new JArray(Feature);return s;}
        internal static JObject Definition(RoomHeightField field){var j=JObject.Parse(JsonUtility.ToJson(field));j.Remove("version");j.Remove("heights");return j;}
        static JObject Variant(string mode){var p=new JObject{["operation"]=Choice(mode),["target"]=DrawingData.Target(),["revision"]=Revision()};p["operation"]["x-static"]=true;if(mode=="configure"){p["definition"]=DefinitionSchema();p["fillHeight"]=Number(0,.5);}var s=CurrentInputs(Object(p),"object.field","revision",new JObject{["target"]="target"});if(mode=="configure")s["format"]="heightFieldReset";s["title"]=mode=="configure"?"Configure / reset heights":"Remove height surface";s["x-features"]=new JArray(Feature);return s;}
        public override JObject InputSchema=>new(){["type"]="object",["x-discriminators"]=new JArray("operation"),["oneOf"]=new JArray(Variant("configure"),Variant("remove"))};
        public override JObject Example=>new(){["operation"]="configure",["target"]=new string('0',32),["revision"]=1,["definition"]=Definition(new RoomHeightField()),["fillHeight"]=.08};
        static RoomHeightField Read(JObject args){if((string)args["operation"]=="remove")return null;var field=JsonUtility.FromJson<RoomHeightField>(args["definition"].ToString());field.heights=Enumerable.Repeat((float)args["fillHeight"],(field.cells+1)*(field.cells+1)).ToArray();return field;}
        public override bool Validate(JObject a,out string error){var field=Read(a);error=null;return field==null||field.Validate(out error);}
        public override bool CanRun(CapabilityContext c,JObject a,out string error)=>c.Editor.PrepareHeightField((string)a["target"],(int)a["revision"],Read(a),out _,out error);
        public override bool Start(CapabilityContext c,string run,JObject a,out CapabilityOperation operation,out string error){operation=null;if(!c.Editor.EditHeightField((string)a["target"],(int)a["revision"],Read(a),out error))return false;operation=new CompletedCapability();return true;}
        internal static BehaviourCatalog.FactDefinition Fact()=>new("object.field",OutputType(Object(new JObject{["revision"]=Revision(),["configured"]=new JObject{["type"]="boolean"},["definition"]=DefinitionSchema(),["count"]=Number(0,289,true),["minimum"]=Number(0,.5),["maximum"]=Number(0,.5),["volumeLitres"]=Number(0,8000)})),"Sculptable surface","Saved field geometry, local geometric volume, height range and current object revision. Missing fields return inert editable defaults with configured=false/count=0. Exact heights are paged through object.field.samples. Volume is in unscaled local litres; prop scale does not rewrite heights. Read-only; no reset or simulation.",Object(new JObject{["target"]=DrawingData.Target()}),new JObject{["target"]=new string('0',32)},(c,a)=>{var d=c.Editor?c.Editor.Read((string)a["target"]):null;if(d==null||d.IsBuiltIn)return null;var f=d.heightFields?.FirstOrDefault();return ProgramValue.Literal(new JObject{["revision"]=c.Editor.ObjectRevision(d.id),["configured"]=f!=null,["definition"]=Definition(f??new RoomHeightField()),["count"]=f?.heights.Length??0,["minimum"]=f?.heights.Min()??0,["maximum"]=f?.heights.Max()??0,["volumeLitres"]=f?.VolumeLitres??0});},features:new[]{Feature});
        internal static BehaviourCatalog.FactDefinition Samples(){var type=OutputType(Object(new JObject{["revision"]=Revision(),["offset"]=Number(0,289,true),["count"]=Number(25,289,true),["heights"]=List(Number(0,.5),0,16)}));return new("object.field.samples",type,"Exact surface heights","Read at most 16 saved grid-vertex heights in row-major order, X first then Z, in local metres along frame +Y. Matching revision required. Offset equal to count returns an empty page; later offsets, missing fields or stale revisions are unavailable. Read all pages to reconstruct the exact source; this never sculpts or advances a revision.",Object(new JObject{["target"]=DrawingData.Target(),["revision"]=Revision(),["offset"]=Number(0,289,true)}),new JObject{["target"]=new string('0',32),["revision"]=1,["offset"]=0},(c,a)=>{string id=(string)a["target"];int offset=(int)a["offset"];var f=c.Editor&&c.Editor.ObjectRevision(id)==(int)a["revision"]?c.Editor.Read(id)?.heightFields?.FirstOrDefault():null;if(f==null||offset>f.heights.Length)return null;return ProgramValue.Literal(new JObject{["revision"]=(int)a["revision"],["offset"]=offset,["count"]=f.heights.Length,["heights"]=new JArray(f.heights.Skip(offset).Take(16))},type);},features:new[]{Feature});}
    }
    internal sealed class SculptFieldCapability:CapabilityModule {
        public override string Id=>"object.field.sculpt";
        public override string Label=>"Sculpt a surface path";
        public override string Duration=>"instant";
        public override IReadOnlyList<string> Channels=>new[]{"wholeTarget"};
        public override IReadOnlyList<string> Requirements=>new[]{"target.created","target.unheld","source.revision.current","storage.writable","target.physics.fixed"};
        public override string Description=>"Raise, lower or level a configured surface along one swept local X/Z path. radius is in local metres; height is the maximum raise/lower amount or the target level. Smooth falloff reaches zero at the brush rim. Every grid vertex is affected at most once by the union of the path, so duplicate points or self-crossings do not multiply strength. Values clamp to 0..maxHeight. All path points must be inside the configured rectangle. A sub-grid brush can miss every vertex and is refused without saving. One action is one saved edit and one Undo, with the same rebuilt mesh/collision. Authoring can add/remove geometric volume; it is not conserved snow transfer. Current revision and exclusive object ownership are required. No playback, physics start or delayed repetition is implied.";
        public override JObject InputSchema{get{var s=CurrentInputs(Object(new JObject{["target"]=DrawingData.Target(),["revision"]=Revision(),["mode"]=Choice("raise","lower","level"),["radius"]=Number(.005,2),["height"]=Number(0,.5),["path"]=List(Object(new JObject{["x"]=Number(-2,2),["z"]=Number(-2,2)}),1,32)}),"object.field","revision",new JObject{["target"]="target"});s["x-features"]=new JArray(HeightFieldCapability.Feature);return s;}}
        public override JObject OutputSchema=>Object(new JObject{["changedVertices"]=Number(1,289,true)});
        public override JObject Example=>new(){["target"]=new string('0',32),["revision"]=1,["mode"]="lower",["radius"]=.08,["height"]=.03,["path"]=new JArray(new JObject{["x"]=-.25,["z"]=0},new JObject{["x"]=.25,["z"]=0})};
        static Vector2[] Path(JObject a)=>((JArray)a["path"]).Select(p=>new Vector2((float)p["x"],(float)p["z"])).ToArray();
        public override bool CanRun(CapabilityContext c,JObject a,out string error)=>c.Editor.PrepareSculpt((string)a["target"],(int)a["revision"],(string)a["mode"],Path(a),(float)a["radius"],(float)a["height"],out _,out _,out error);
        public override bool Start(CapabilityContext c,string run,JObject a,out CapabilityOperation operation,out string error){operation=null;if(!c.Editor.SculptHeightField((string)a["target"],(int)a["revision"],(string)a["mode"],Path(a),(float)a["radius"],(float)a["height"],out var changed,out error))return false;operation=new CompletedCapability(new JObject{["changedVertices"]=changed});return true;}
    }
}
