// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using Newtonsoft.Json.Linq;
using static Maestro.Quest.Programs.CapabilitySchema;
namespace Maestro.Quest.Programs {
    internal static class MediumContactFacts {
        internal const string Feature="liquidContacts.v1";
        static JObject Fields()=>CapabilitySchema.Object(new JObject{
            ["known"]=new JObject{["type"]="boolean"},["immersed"]=new JObject{["type"]="boolean"},["bodyId"]=Text("^.{0,64}$",64),["kind"]=Text("^.{0,32}$",32),["liquid"]=Text("^.{0,32}$",32),["depthMetres"]=Number(0,100),["sampleSpeedMetresPerSecond"]=Number(0,30),["surface"]=CapabilitySchema.Object(new JObject{["x"]=Number(-1000,1000),["y"]=Number(-1000,1000),["z"]=Number(-1000,1000)}),["reason"]=Text("^.{0,256}$",256)});
        const string Sampling="Contacts sample at up to 20 Hz: rigid props use the shared 4x4x4 occupancy grid; Maestro uses six visible mapped joints (feet, hands, hips and head); each hand uses its tracked index fingertip, each controller its aim-pose origin. This is bounded sampled contact, not whole-skin or fluid simulation. known=false means unavailable, never dry. Samples expire after 0.2 seconds; tracking expires after 0.15 seconds. Physics, participant and vessel environment policies, geometry, lifecycle and workspace holds apply. Spawn, reload, geometry/ownership changes and tracking reacquisition establish a baseline without entry/exit events. Nested water chooses the smallest containing cavity then stable ID. Contacts change no quantities or velocities. Transient ripples use at most eight one-second waves per vessel on its clipped surface.";
        internal static BehaviourCatalog.FactDefinition Object()=>new("object.medium.contactState",OutputType(Fields()),"Object or Maestro water contact",Sampling+" Read the last sampled aggregate for a created prop or Maestro. surface is an authored-coordinate projection, depth is physical metres. When dry, surface is only the first sampled position.",CapabilitySchema.Object(new JObject{["target"]=Text("^([a-f0-9]{32}|maestro)$",32)}),new JObject{["target"]="maestro"},(c,a)=>c.Editor?.Liquids?.ObserveContact((string)a["target"]) is JObject value?ProgramValue.Literal(value):null,features:new[]{Feature});
        internal static BehaviourCatalog.FactDefinition Input()=>new("input.medium.contactState",OutputType(Fields()),"Tracked hand or controller water contact",Sampling+" Pointing a ray at distant water does not touch it. Tracked physical inputs use the global real-room policy.",CapabilitySchema.Object(new JObject{["side"]=Choice("left","right")}),new JObject{["side"]="left"},(c,a)=>c.Editor?.Liquids?.ObserveContact("input:"+(string)a["side"]) is JObject value?ProgramValue.Literal(value):null,features:new[]{Feature});
        internal static BehaviourCatalog.EventDefinition Event()=>new("object.medium.contact","Water contact changed",Sampling+" Value/source is the vessel ID. participantId identifies a created prop, maestro, input:left or input:right; kind distinguishes object/avatar/hand/controller. phase is entered/exited for aggregate membership changes, or crossed when a sampled point travels across the finite free surface and ends dry beyond the cavity between samples. Multiple samples collapse to one representative event per phase and participant; this is not exhaustive continuous collision detection. speed is sampled physical metres/second capped at 30, depth is sampled metres, x/y/z is a representative surface point in authored coordinates. A queued point remains in its authored room. Use a condition on phase/kind/participantId to attach a sound or behavior; ongoing submerged movement only refreshes ripples, not event spam.",CapabilitySchema.Object(new JObject{["participantId"]=Text("^([a-f0-9]{32}|maestro|input:left|input:right)$",32),["kind"]=Choice("object","avatar","hand","controller"),["phase"]=Choice("entered","exited","crossed"),["speed"]=Number(0,30),["depth"]=Number(0,100),["x"]=Number(-1000,1000),["y"]=Number(-1000,1000),["z"]=Number(-1000,1000)}),objectEvent:true,features:new[]{Feature});
    }
}
