// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using Newtonsoft.Json.Linq;
using UnityEngine;
using static Maestro.Quest.Programs.CapabilitySchema;
namespace Maestro.Quest.Programs {
    internal static class MediumFacts {
        internal const string Feature="liquidMedium.v1";
        static JObject Point()=>Object(new JObject{["x"]=Number(-1000,1000),["y"]=Number(-1000,1000),["z"]=Number(-1000,1000)});
        internal static BehaviourCatalog.FactDefinition World()=>new("world.medium",OutputType(Object(new JObject{["worldId"]=Text("^.{0,128}$",128),["regionId"]=Text("^.{0,128}$",128),["found"]=new JObject{["type"]="boolean"},["active"]=new JObject{["type"]="boolean"},["bodyId"]=Text("^.{0,128}$",128),["liquid"]=Text("^.{0,128}$",128),["depthMetres"]=Number(0,100),["surface"]=Point(),["densityKgM3"]=Number(0,20000),["reason"]=Text("^.{0,128}$",128)})),
            "Liquid medium at a point","Read finite live liquid at an authored world-coordinate point. Cylindrical/rectangular container geometry and the shared free surface use current pouring/rain quantities, not a second water store. target optionally selects the actor whose real-room readiness applies; empty uses global policy. found is geometric containment; active additionally requires unpaused admitted physics for both actor and medium. Nested or overlapping cavities select the smallest physical cavity, then stable object ID, never added densities. surface is projected along gravity and depth is in physical metres. Logical ml/capacity determine fill fraction; visual scale changes geometric displacement without creating contents. No terrain reservoir, fluid level displacement, route clearance, swimming or automatic mixing is implied.",Object(new JObject{["position"]=DrawingData.Point(),["target"]=Text("^([a-zA-Z0-9_-]{1,64})?$",64)}),new JObject{["position"]=new JObject{["x"]=0,["y"]=0,["z"]=0},["target"]=""},
            (c,a)=>c.Editor?.Liquids?.ObserveMedium(new Vector3((float)a["position"]["x"],(float)a["position"]["y"],(float)a["position"]["z"]),(string)a["target"]) is JObject value?ProgramValue.Literal(value):null,features:new[]{Feature});
        internal static BehaviourCatalog.FactDefinition Body()=>new("object.medium",OutputType(Object(new JObject{["applied"]=new JObject{["type"]="boolean"},["submergedFraction"]=Number(0,1),["displacementM3"]=Number(0,1000000),["buoyancyNewtons"]=Point(),["reason"]=Text("^.{0,128}$",128)})),
            "Rigid prop medium response","Last native physics sample for a created prop. A cached 4x4x4 occupancy grid approximates the union of accepted box/sphere/capsule/convex-mesh colliders; thin geometry can have no supported samples. Existing mass and explicitly configured fluid density determine buoyancy, with linear/angular drag. Lift and linear drag acceleration are capped at 30 m/s2. Forces never alter saved poses/quantities or bypass fixed, held, animation-owned, paused or unavailable physics. A prop excludes its own liquid. applied is rechecked against current ownership/readiness; submergedFraction and displacementM3 describe the last sample. No carried-liquid mass or fluid-level displacement. Actor locomotion requires a separate traversal policy and is not proven by this fact.",Object(new JObject{["target"]=DrawingData.Target()}),new JObject{["target"]=new string('0',32)},(c,a)=>c.Editor?.Liquids?.ObserveMediumBody((string)a["target"]) is JObject value?ProgramValue.Literal(value):null,features:new[]{Feature});
    }
}
