// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using System.Collections.Generic;
using Maestro.Quest.Creation;
using Newtonsoft.Json.Linq;
using static Maestro.Quest.Programs.CapabilitySchema;
namespace Maestro.Quest.Programs {
    internal sealed class SculptToolCapability:CapabilityModule {
        public override string Id=>"field.tool.set";
        public override string Label=>"Choose the physical sculpt tool";
        public override string Duration=>"instant";
        public override IReadOnlyList<string> Requirements=>new[]{"authoring.idle","room.active"};
        public override string Description=>"Choose off/raise/lower/level plus local brush radius and height for the next physical gesture. Controller: hold trigger with its pointer within 25 cm of the accepted field. Tracked hands: touch the accepted top with an index fingertip (15 mm contact band), move, and lift to finish; first separate after enabling or interruption. These use the same object.field.sculpt evaluator and one save/Undo per gesture, at most 32 sampled points. A stationary contact does not repeatedly add/remove height. Visible geometry previews the draft; collision and saved data update together only after successful publication. Failed or interrupted drafts require explicit Retry/Discard; no automatic retry after pause or tracking loss. Solid obstructions block physical contact. Settings are session-local and independent of saved object sculpt tips. Enabling sculpting puts away the pencil and construction selection; changing modes requires finishing/discarding an active draft. No shape changes, physics start or playback happen merely from choosing a mode. These controls are the same as the physical tray.";
        public override JObject InputSchema{get{var s=Object(new JObject{["mode"]=Choice("off","raise","lower","level"),["radius"]=Number(.005,2),["height"]=Number(0,.5)});s["x-features"]=new JArray(SculptTipCapability.Feature);return s;}}
        public override JObject Example=>new(){["mode"]="lower",["radius"]=.08,["height"]=.03};
        public override bool CanRun(CapabilityContext c,JObject a,out string error)=>c.Editor.Sculpting.CanConfigure(out error);
        public override bool Start(CapabilityContext c,string run,JObject a,out CapabilityOperation operation,out string error){operation=null;if(!c.Editor.Sculpting.Configure((string)a["mode"],(float)a["radius"],(float)a["height"],out error))return false;operation=new CompletedCapability();return true;}
        internal static BehaviourCatalog.FactDefinition Fact()=>new("field.tool",OutputType(Object(new JObject{["mode"]=Choice("off","raise","lower","level"),["radius"]=Number(.005,2),["height"]=Number(0,.5)})),"Current physical sculpt tool","Session-local trigger/fingertip sculpt settings shared with the tray. Reads do not enable input or modify a surface.",null,null,(c,a)=>c.Editor&&c.Editor.GetComponent<SpatialSculpting>() is SpatialSculpting tool?ProgramValue.Literal(new JObject{["mode"]=tool.Mode,["radius"]=tool.Radius,["height"]=tool.Height}):null,features:new[]{SculptTipCapability.Feature});
    }
    internal sealed class SculptResolveCapability:CapabilityModule {
        public override string Id=>"object.field.resolve";
        public override string Label=>"Retry or discard an unsaved sculpt gesture";
        public override string Duration=>"instant";
        public override IReadOnlyList<string> Requirements=>new[]{"sculpt.retained","sculpt.session.current"};
        public override string Description=>"Read object.field.capture and resolve its exact retained sessionId. Retry uses the same frozen sampled path and object.field.sculpt evaluator, with one saved edit/Undo; the saved field must still match the original and ownership must be reacquired. Discard restores the accepted visual and removes only the in-memory draft. Collision has remained on the accepted mesh throughout preview. Changed/missing fields and a different room session refuse retry. A successful receipt cannot resolve a later draft. Active gestures cannot be resolved. Retained drafts block workspace/temporary-room changes; destroying the app/room loses unsaved memory. For a material scoop/deposit, retry instead publishes the frozen field and carrier balance together after verifying both originals and the saved tip. Both are restored by one Undo. For hand/controller packing, retry invokes object.material.pack with the frozen footprint, quantity and position; the source pose must match and the ball space must still be clear. One Undo restores the field and removes the ball. Inspect material.pack.capture for its last saved session/object identity; inspect object.material.capture for scoop amounts. This does not enable a tool, start physics or play an animation.";
        public override JObject InputSchema{get{var s=CurrentInputs(Object(new JObject{["operation"]=Choice("retry","discard"),["sessionId"]=Text("^[a-f0-9]{32}$",32)}),"object.field.capture","sessionId");s["x-features"]=new JArray(SculptTipCapability.Feature);return s;}}
        public override JObject OutputSchema=>Object(new JObject{["sessionId"]=Text("^[a-f0-9]{32}$",32),["phase"]=Choice("saved","discarded"),["target"]=Text("^(|[a-f0-9]{32})$",32),["points"]=Number(1,32,true),["changedVertices"]=Number(0,289,true),["temporary"]=new JObject{["type"]="boolean"}});
        public override JObject Example=>new(){["operation"]="retry",["sessionId"]=new string('0',32)};
        public override bool CanRun(CapabilityContext c,JObject a,out string error)=>c.Editor.Sculpting.CanResolve((string)a["sessionId"],(string)a["operation"]=="discard",out error);
        public override bool Start(CapabilityContext c,string run,JObject a,out CapabilityOperation operation,out string error){operation=null;if(!c.Editor.Sculpting.Resolve((string)a["sessionId"],(string)a["operation"]=="discard",out var result,out error))return false;operation=new CompletedCapability(result);return true;}
        internal static BehaviourCatalog.FactDefinition Fact()=>new("object.field.capture",OutputType(Object(new JObject{["sessionId"]=Text("^[a-f0-9]{32}$",32),["phase"]=Choice("idle","sculpting","unsaved"),["target"]=Text("^(|[a-f0-9]{32})$",32),["brush"]=Object(new JObject{["mode"]=Choice("none","raise","lower","level","take","deposit","pack"),["radius"]=Number(0,2),["height"]=Number(0,.5)}),["points"]=Number(0,32,true),["temporary"]=new JObject{["type"]="boolean"},["error"]=Text("^.{0,128}$",128)})),"Physical sculpt draft","Current shared shape or material gesture, field target, brush settings, sampled point count and bounded error. Material take/deposit/pack has one point and zero height; inspect object.material.capture or material.pack.capture for quantities and the last packed ball identity. Preview is visible only; collision/saved heights remain accepted. Unsaved needs explicit Retry/Discard. Read object.field.capture.path for exact points. Reads do not change the draft.",null,null,(c,a)=>c.Editor&&c.Editor.GetComponent<SpatialSculpting>() is SpatialSculpting tool?ProgramValue.Literal(tool.Observe()):null,features:new[]{SculptTipCapability.Feature});
        internal static BehaviourCatalog.FactDefinition Path(){var type=OutputType(Object(new JObject{["sessionId"]=Text("^[a-f0-9]{32}$",32),["offset"]=Number(0,32,true),["count"]=Number(1,32,true),["points"]=List(Object(new JObject{["x"]=Number(-2,2),["z"]=Number(-2,2)}),0,8)}));return new("object.field.capture.path",type,"Exact sculpt gesture path","Read eight local X/Z points of the active or retained sculpt draft. Exact sessionId required; offset=count is an empty page and later offsets are unavailable. A live path can grow; freeze it by finishing the gesture before reconstructing a retained failed draft. No sampled path can exceed 32 points.",Object(new JObject{["sessionId"]=Text("^[a-f0-9]{32}$",32),["offset"]=Number(0,32,true)}),new JObject{["sessionId"]=new string('0',32),["offset"]=0},(c,a)=>{var value=c.Editor?c.Editor.GetComponent<SpatialSculpting>()?.PathPage((string)a["sessionId"],(int)a["offset"]):null;return value==null?null:ProgramValue.Literal(value,type);},features:new[]{SculptTipCapability.Feature});}
    }
}
