// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using System.Linq;
using Maestro.Quest.Creation;
using Newtonsoft.Json.Linq;
using UnityEngine;
using static Maestro.Quest.Programs.CapabilitySchema;
namespace Maestro.Quest.Programs
{
    internal static class RecipeEditFacts
    {
        internal static JObject Summary(RoomEditor editor,string target){var r=editor.Read(target).recipe;return new JObject {["target"]=target,["revision"]=editor.ObjectRevision(target),["parts"]=r.parts.Length,["tracks"]=r.tracks.Length,["duration"]=r.duration,["loop"]=r.loop,["playing"]=editor.Find(target).GetComponent<RecipeObject>().IsPlaying,["autoplay"]=r.playing};}
        static JObject VectorType(bool rotation=false){var fields=new JObject {["x"]="number",["y"]="number",["z"]="number"};if(rotation)fields["w"]="number";return new JObject {["record"]=fields};}
        static JObject Input(bool page,bool track=false){var props=new JObject {["target"]=RecipeEditCapability.Target()};if(page){props["revision"]=Number(1,1000000,true);props["index"]=Number(0,track?16:31,true);if(track)props["offset"]=Number(0,16,true);}return Object(props);}
        static JObject Example(bool page,bool track=false){var args=new JObject {["target"]=new string('0',32)};if(page){args["revision"]=1;args["index"]=0;if(track)args["offset"]=0;}return args;}
        static RoomRecipe Read(BehaviourCatalog.FactContext context,JObject args){string target=(string)args["target"];return context.Editor&&context.Editor.Find(target)&&(!args.ContainsKey("revision")||context.Editor.ObjectRevision(target)==(int)args["revision"])?context.Editor.Read(target)?.recipe:null;}
        public static BehaviourCatalog.FactDefinition Overview()=>new("object.recipe",ProgramDataType.Read(JObject.Parse("{\"record\":{\"target\":\"text\",\"revision\":\"number\",\"parts\":\"number\",\"tracks\":\"number\",\"duration\":\"number\",\"loop\":\"boolean\",\"playing\":\"boolean\",\"autoplay\":\"boolean\"}}")),"Editable recipe summary","Saved recipe counts, timing, loop and autoplay preference plus actual playback. Reads the temporary fork when active. Exact revision guards edits and paged part/track reads; missing/non-recipe targets are unavailable.",Input(false),Example(false),(context,args)=>Read(context,args)!=null?ProgramValue.Literal(Summary(context.Editor,(string)args["target"])):null);
        public static BehaviourCatalog.FactDefinition Part(){var partType=new JObject {["id"]="text",["parent"]="text",["shape"]="text",["position"]=VectorType(),["size"]=VectorType(),["rotation"]=VectorType(true),["color"]=new JObject {["record"]=new JObject {["r"]="number",["g"]="number",["b"]="number",["a"]="number"}}};var type=new JObject {["revision"]="number",["index"]="number",["total"]="number",["part"]=new JObject {["record"]=partType}};return new("object.recipe.part",ProgramDataType.Read(new JObject {["record"]=type}),"Recipe part","Read one exact saved part by index and revision. Root parent is empty text. Coordinates/dimensions are local metres; rotation is a unit quaternion. All 32 base part records remain readable without simplification. For lathe geometry also read object.recipe.profile at the same revision; this base record omits profile and segments. Missing targets, stale revisions and later indexes are unavailable.",Input(true),Example(true),(context,args)=>{var r=Read(context,args);int index=(int)args["index"];if(r==null||index>=r.parts.Length)return null;var p=JObject.Parse(JsonUtility.ToJson(r.parts[index]));p["parent"]=(string)p["parent"]??"";p.Remove("profile");p.Remove("segments");return ProgramValue.Literal(new JObject {["revision"]=(int)args["revision"],["index"]=index,["total"]=r.parts.Length,["part"]=p});});}
        public static BehaviourCatalog.FactDefinition Track(){var key=new JObject {["record"]=new JObject {["time"]="number",["rotation"]=VectorType(true)}};var type=new JObject {["revision"]="number",["part"]="text",["offset"]="number",["count"]="number",["keys"]=new JObject {["list"]=key}};return new("object.recipe.track",ProgramDataType.Read(new JObject {["record"]=type}),"Recipe track key page","Read up to four exact saved rotation keys for the indexed track and revision. count is this track's full key count, offset is the first returned key. Offset equal to count returns an empty page; later offsets/indexes, stale revisions and missing recipes are unavailable. Read all 17 tracks and 16 keys without simplification. No playback or editing occurs.",Input(true,true),Example(true,true),(context,args)=>{var r=Read(context,args);int index=(int)args["index"],offset=(int)args["offset"];if(r==null||index>=r.tracks.Length)return null;var track=r.tracks[index];if(offset>track.keys.Length)return null;return ProgramValue.Literal(new JObject {["revision"]=(int)args["revision"],["part"]=track.part,["offset"]=offset,["count"]=track.keys.Length,["keys"]=new JArray(track.keys.Skip(offset).Take(4).Select(k=>JObject.Parse(JsonUtility.ToJson(k))))},BehaviourCatalog.Fact("object.recipe.track").Type);});}
    }
}
