// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using Maestro.Quest.Diagnostics;
using Maestro.Quest.Imports;
using Newtonsoft.Json.Linq;
namespace Maestro.Quest.Programs
{
    public static class RuntimeDiagnosticFacts
    {
        public const string Feature="runtimeDiagnostics.v1";
        static readonly string[] Features={Feature};
        static RuntimeDiagnostics Sampler(BehaviourCatalog.FactContext context)=>context.Editor?context.Editor.GetComponentInParent<RuntimeDiagnostics>():null;
        public static BehaviourCatalog.FactDefinition Acoustics()=>new("runtime.acoustics",ProgramDataType.Read(JObject.Parse("{\"record\":{\"active\":\"boolean\",\"geometry\":\"number\",\"triangles\":\"number\",\"omitted\":\"number\",\"map\":{\"record\":{\"computing\":\"boolean\",\"ready\":\"boolean\",\"geometry\":\"number\",\"omitted\":\"number\",\"issue\":\"text\"}},\"reflections\":\"boolean\",\"issue\":\"text\"}}")),
            "Room sound obstruction","Last native acoustic synchronization: active renderer, uploaded mesh/triangle counts and omitted or pending registered surfaces. Bounded direct speech obstruction uses approximate hard-surface materials, independently of collision and overlay visibility. map.geometry and map.omitted describe reflection boundaries: accepted scans, the virtual floor, and fixed unheld creations without active model/recipe/object animation. Dynamic objects still obstruct direct sound but do not rebuild reflections. Stable boundaries are mapped after two seconds, with up to four listener points, movement settling and failure backoff. While map.computing, geometry inputs are retained for the worker and active is false. map.ready confirms calculated map data, not audible reflections: the reflection mixer remains disabled. Skinned meshes, alpha-cutout imports, drawing overlays and unscanned moving real objects are not acoustic geometry; omitted does not count those unsupported categories. Counts do not verify room alignment, device audibility or performance. Reads never upload, compute, load or change the scene.",null,null,
            (context,args)=>{var room=context.Editor?context.Editor.GetComponentInParent<Book.RoomAcoustics>():null;if(!Sampler(context)||!room)return null;return ProgramValue.Literal(new JObject {
                ["active"]=room.Ready,["geometry"]=room.GeometryCount,["triangles"]=room.TriangleCount,["omitted"]=room.OmittedCount,["map"]=new JObject {["computing"]=room.MapComputing,["ready"]=room.MapReady,["geometry"]=room.BoundaryCount,["omitted"]=room.OmittedBoundaries,["issue"]=room.MapIssue??""},["reflections"]=false,["issue"]=room.Issue??""});},features:Features);
        static ProgramDataType Record(params string[] names){var fields=new JObject();foreach(var name in names)fields[name]="number";return ProgramDataType.Read(new JObject {["record"]=fields});}
        public static BehaviourCatalog.FactDefinition CollisionResources()=>new("runtime.collisionResources",Record("entries","preparing","ready","retiring","colliders","meshColliders","sourceTriangles","activeColliders"),
            "Authored collision resources","Process-wide retained collision geometry from authored compound shapes, accepted height fields and rigid imported-model collision. Includes disabled and prepared replacements. Source collider/triangle counts are not measured RAM, PhysX cooked size, unique mesh assets or enforced admission limits. Repeated mesh instances count separately. Default bounds, book/avatar proxies, scanned room geometry and navigation maps are excluded. Preparing costs are declared; ready costs come from actual accepted colliders; retiring costs remain until all owned collider components are destroyed. activeColliders counts enabled components in active hierarchies, not proof of simulation or contact. Reads may forget completed destruction metadata but never destroy geometry, evict, load or modify saved world data. Regional admission/streaming remains separate.",null,null,
            (context,args)=>!Sampler(context)?null:ProgramValue.Literal(Creation.CollisionResources.Observe()),features:Features);
        public static BehaviourCatalog.FactDefinition CollisionResource()=>new("runtime.collisionResource",ProgramDataType.Read(JObject.Parse("{\"record\":{\"leaseId\":\"text\",\"worldId\":\"text\",\"regionId\":\"text\",\"target\":\"text\",\"role\":\"text\",\"kind\":\"text\",\"phase\":\"text\",\"colliders\":\"number\",\"meshColliders\":\"number\",\"sourceTriangles\":\"number\",\"activeColliders\":\"number\"}}")),
            "Authored collision owner","Read one retained authored collision lease by index (zero to runtime.collisionResources.entries minus one). Indices may shift; leaseId is an ephemeral runtime identity, never a saved object reference. World/region/target copy the owning authored entity; unscoped desktop geometry has empty identifiers. role is collision or unscoped; kind is compound, terrain or imported; phase is preparing, ready or retiring. A replacement can retain two leases for one target. Disabled geometry retains its source costs. Retiring source costs remain until all owned collider components are gone; activeColliders reflects actual enabled components in active hierarchies. Same accounting scope and exclusions as runtime.collisionResources; not measured RAM or admission limits. Reads return detached metadata and never delete assets, saved objects or geometry.",
            CapabilitySchema.Object(new JObject{["index"]=CapabilitySchema.Number(0,int.MaxValue,true)}),new JObject{["index"]=0},
            (context,args)=>{if(!Sampler(context))return null;var value=Creation.CollisionResources.ObserveEntry((int)args["index"]);return value==null?null:ProgramValue.Literal(value);},features:Features);
        public static BehaviourCatalog.FactDefinition Frames()=>new("runtime.frameIntervals",ProgramDataType.Read(JObject.Parse("{\"record\":{\"active\":\"boolean\",\"hasSamples\":\"boolean\",\"samples\":\"number\",\"seconds\":\"number\",\"milliseconds\":{\"record\":{\"mean\":\"number\",\"p95\":\"number\",\"max\":\"number\"}},\"capacityLimited\":\"boolean\",\"ageSeconds\":\"number\",\"editor\":\"boolean\"}}")),
            "Unity frame intervals","Local Unity Update intervals ending in the last 30 seconds, at most 4096 samples. Reads are cached for up to one second. seconds sums retained intervals (the oldest can start before the window); p95 uses nearest rank. ageSeconds is the last-sample age at the cached reading. No samples means zero placeholders, not healthy timing. Pause, focus loss, disable and invalid/backwards or over-1000-second clock gaps reset the window. capacityLimited reports discarded samples still inside the window. editor distinguishes desktop test evidence. These are not GPU times, compositor/display FPS, refresh rate, memory or a Store performance verdict. No automatic settings changes or persistence.",null,null,
            (context,args)=>{var sampler=Sampler(context);return sampler?ProgramValue.Literal(sampler.ObserveFrames()):null;},features:Features);
        static JObject Budget(int models,int vertices,int pixels,int morphs)=>new() {["models"]=models,["vertices"]=vertices,["textureMiPixels"]=pixels/1048576.0,["morphMillionVertices"]=morphs/1000000.0};
        public static BehaviourCatalog.FactDefinition Models()=>new("runtime.modelBudget",ProgramDataType.Read(JObject.Parse("{\"record\":{\"reserved\":{\"record\":{\"models\":\"number\",\"vertices\":\"number\",\"textureMiPixels\":\"number\",\"morphMillionVertices\":\"number\"}},\"limits\":{\"record\":{\"models\":\"number\",\"vertices\":\"number\",\"textureMiPixels\":\"number\",\"morphMillionVertices\":\"number\"}}}}")),
            "Imported model budgets","Process-wide model reservations including avatar, previews and in-flight imports, with enforced limits. Source vertices, decoded texture MiPixels (1048576 pixels), morph million-vertices (1000000) and instance counts are budgets, not measured RAM/VRAM. Does not include procedural objects, book textures, WebView or operating-system memory. Reading never loads, evicts or changes anything.",null,null,
            (context,args)=>{if(!Sampler(context))return null;var live=ImportedModel.LiveBudget;return ProgramValue.Literal(new JObject {
                ["reserved"]=Budget(live.Models,live.Vertices,live.TexturePixels,live.MorphVertices),
                ["limits"]=Budget(ImportedModel.MaximumLiveModels,ImportedModel.MaximumLiveVertices,ImportedModel.MaximumLiveTexturePixels,ImportedModel.MaximumLiveMorphVertices)});},features:Features);
        public static BehaviourCatalog.FactDefinition ModelReservation()=>new("runtime.modelReservation",ProgramDataType.Read(JObject.Parse("{\"record\":{\"reservationId\":\"text\",\"worldId\":\"text\",\"regionId\":\"text\",\"target\":\"text\",\"role\":\"text\",\"modelHash\":\"text\",\"state\":\"text\",\"vertices\":\"number\",\"textureMiPixels\":\"number\",\"morphMillionVertices\":\"number\"}}")),
            "Imported model reservation","Read one process-wide model lease by index (0 to runtime.modelBudget.reserved.models minus one). Indices may shift between reads; reservationId is a runtime-only identity, never an authored entity reference. World/region/target identify the owning object or avatar; previews have an empty target, and unscoped desktop imports have empty world/region. role is object, avatar, preview or unscoped. loading reserves before native import; ready means imported geometry exists, not that a candidate is visible or usable as collision; retiring retains costs until an abandoned in-flight importer drains. Avatar replacement can temporarily hold two leases for the same target. Waiting requests that have not acquired the serialized importer have no reservation. Source costs are conservative limits, not measured RAM/VRAM. Reads are detached and never load, cancel, evict or change settings. Regional streaming remains separate.",
            CapabilitySchema.Object(new JObject{["index"]=CapabilitySchema.Number(0,ImportedModel.MaximumLiveModels-1,true)}),new JObject{["index"]=0},
            (context,args)=>{if(!Sampler(context))return null;var value=ModelReservations.Observe((int)args["index"]);return value==null?null:ProgramValue.Literal(value);},features:Features);
        public static BehaviourCatalog.FactDefinition Images()=>new("runtime.imageBudget",Record("entries","owners","textureBytes","entryLimit","ownerLimitPerImage","textureByteLimit"),
            "Current room appearance image budget","Current workspace appearance-image cache and its enforced limits. Multiple object leases share one decoded texture for an exact image hash. entries includes loading and failed bindings; owners counts leases, including a brief old/new overlap during refresh. textureBytes is a conservative RGBA-plus-mipmap estimate for ready textures, not measured RAM/VRAM or peak memory. It excludes file reads, decode scratch space, previews, imported-model textures, book/browser images and other workspaces. Reading never decodes, retries, evicts or changes anything.",null,null,
            (context,args)=>{var images=context.Editor?context.Editor.ImageTextures:null;return Sampler(context)&&images?ProgramValue.Literal(images.ObserveBudget()):null;},features:Features);
        public static BehaviourCatalog.FactDefinition ImageReservation()=>new("runtime.imageReservation",ProgramDataType.Read(JObject.Parse("{\"record\":{\"reservationId\":\"text\",\"imageHash\":\"text\",\"state\":\"text\",\"owners\":\"number\",\"textureBytes\":\"number\"}}")),
            "Shared appearance image reservation","Read one current-workspace image cache entry by index (zero to runtime.imageBudget.entries minus one). Indices may shift. reservationId identifies this runtime entry until its last lease is released; reloading the same hash gets a new ID. state is loading, ready or failed. Loading/failed entries report zero textureBytes; ready reports one shared conservative texture estimate, never multiplied by owners. Ready means decoded pixels exist, not that every renderer has refreshed. Use runtime.imageOwner with the returned reservationId to inspect holders. Reads are detached and do not load, retry, evict or persist. Regional activation remains separate.",
            CapabilitySchema.Object(new JObject{["index"]=CapabilitySchema.Number(0,Art.AppearanceImages.MaximumEntries-1,true)}),new JObject{["index"]=0},
            (context,args)=>{var images=context.Editor?context.Editor.ImageTextures:null;if(!Sampler(context)||!images)return null;var value=images.ObserveReservation((int)args["index"]);return value==null?null:ProgramValue.Literal(value);},features:Features);
        public static BehaviourCatalog.FactDefinition ImageOwner()=>new("runtime.imageOwner",ProgramDataType.Read(JObject.Parse("{\"record\":{\"reservationId\":\"text\",\"leaseId\":\"text\",\"imageHash\":\"text\",\"worldId\":\"text\",\"regionId\":\"text\",\"target\":\"text\",\"role\":\"text\"}}")),
            "Appearance image owner","Read one lease of the exact runtime.imageReservation.reservationId, by index zero to its owners minus one. Indices and leaseId can change on a renderer refresh; these are runtime identities, not saved entity references. World/region/target are copied authored ownership; role is appearance, or unscoped for native fixtures with no authored owner. The owning object can be offscreen: this is resource retention, not visibility or permission to unload. A released reservation ID is unavailable and never redirects to a newer load. Texture costs are counted once by runtime.imageReservation, not per holder. This current-workspace read does not change anything.",
            CapabilitySchema.Object(new JObject{["reservationId"]=CapabilitySchema.Text("^[a-f0-9]{32}$",32),["index"]=CapabilitySchema.Number(0,Art.AppearanceImages.MaximumOwnersPerImage-1,true)}),new JObject{["reservationId"]=new string('a',32),["index"]=0},
            (context,args)=>{var images=context.Editor?context.Editor.ImageTextures:null;if(!Sampler(context)||!images)return null;var value=images.ObserveOwner((string)args["reservationId"],(int)args["index"]);return value==null?null:ProgramValue.Literal(value);},features:Features);
        public static BehaviourCatalog.FactDefinition Audio()=>new("runtime.audioBudget",ProgramDataType.Read(JObject.Parse("{\"record\":{\"sources\":\"number\",\"owners\":\"number\",\"retiring\":\"number\",\"reservedPcmBytes\":\"number\",\"readyPcmBytes\":\"number\",\"sourceLimit\":\"number\",\"ownerLimit\":\"number\",\"pcmByteLimit\":\"number\"}}")),
            "Shared room audio budget","Process-wide admission for procedural and imported room-sound decoders and their voice owners, including older workspaces whose cancelled tasks are still draining. Owners share a decoded source inside one workspace when its exact saved definition matches. reservedPcmBytes budgets mono 24 kHz signed-16 PCM from declared duration plus four samples for rounding/tolerance; readyPcmBytes counts actual decoded samples once per source. These are not measured or peak memory and exclude file bytes, decoder/tone scratch arrays, voice ring buffers, Unity carriers, speech/Live/browser audio and native DSP. Eight sources and eight owners are shared across workspaces. Retiring work keeps source/PCM admission until it drains, with no active voice owners. No inspection starts, stops, pauses or unloads audio.",null,null,
            (context,args)=>Sampler(context)?ProgramValue.Literal(Creation.AudioReservations.ObserveBudget()):null,features:Features);
        public static BehaviourCatalog.FactDefinition AudioReservation()=>new("runtime.audioReservation",ProgramDataType.Read(JObject.Parse("{\"record\":{\"reservationId\":\"text\",\"worldId\":\"text\",\"regionId\":\"text\",\"sourceId\":\"text\",\"kind\":\"text\",\"assetHash\":\"text\",\"definitionHash\":\"text\",\"state\":\"text\",\"owners\":\"number\",\"reservedPcmBytes\":\"number\",\"readyPcmBytes\":\"number\"}}")),
            "Room sound reservation","Read one shared room-sound buffer by index zero to runtime.audioBudget.sources minus one. Indices may shift; reservationId identifies only this runtime allocation. World/region and exact source ID/definitionHash describe the copied source; assetHash is empty for tones. State is loading, ready, failed or retiring. ready confirms decoded samples, not audible playback. Multiple owners share its PCM cost. A stopped final owner retires the source; pending work remains admitted until its task finishes even if its workspace is gone. Use runtime.audioOwner for active instance holders. Reads are detached and never trigger decoding, eviction, replay or persistence. This is not regional streaming.",
            CapabilitySchema.Object(new JObject{["index"]=CapabilitySchema.Number(0,Creation.AudioReservations.MaximumSources-1,true)}),new JObject{["index"]=0},
            (context,args)=>{if(!Sampler(context))return null;var value=Creation.AudioReservations.ObserveReservation((int)args["index"]);return value==null?null:ProgramValue.Literal(value);},features:Features);
        public static BehaviourCatalog.FactDefinition AudioOwner()=>new("runtime.audioOwner",ProgramDataType.Read(JObject.Parse("{\"record\":{\"reservationId\":\"text\",\"instanceId\":\"text\",\"worldId\":\"text\",\"regionId\":\"text\",\"target\":\"text\",\"role\":\"text\",\"emitter\":\"text\",\"sourceId\":\"text\",\"sourceRevision\":\"number\"}}")),
            "Room sound owner","Read one active holder of an exact runtime.audioReservation.reservationId, by index zero to its owners minus one. instanceId is the actual audio.instance identity; its phase, lifetime, progress and controls remain in audio.instance. World/region/target, emitter, role audio and source revision are copied ownership, never a saved replacement for entity references. Several voices can share one buffer and each can stop independently. Retiring entries have zero owners. A released reservation ID stays unavailable; reloading creates a new ID. Reading cannot make an offscreen sound eligible for removal or change its playback.",
            CapabilitySchema.Object(new JObject{["reservationId"]=CapabilitySchema.Text("^[a-f0-9]{32}$",32),["index"]=CapabilitySchema.Number(0,Creation.AudioReservations.MaximumOwners-1,true)}),new JObject{["reservationId"]=new string('a',32),["index"]=0},
            (context,args)=>{if(!Sampler(context))return null;var value=Creation.AudioReservations.ObserveOwner((string)args["reservationId"],(int)args["index"]);return value==null?null:ProgramValue.Literal(value);},features:Features);
        public static BehaviourCatalog.FactDefinition Motions()=>new("runtime.motionCache",Record("clips","curveValues","clipLimit","curveValueLimit"),
            "Current room motion cache","Current room library cache entries and declared curve values, including in-flight loads, with enforced limits. Excludes embedded model clips, other workspace generations, source files and actual native/GPU byte usage. Reading does not load or evict clips.",null,null,
            (context,args)=>{var library=context.Editor?context.Editor.Motions:null;if(!Sampler(context)||library==null)return null;return ProgramValue.Literal(new JObject {
                ["clips"]=library.ResidentClipCount,["curveValues"]=library.ResidentCurveValues,["clipLimit"]=MotionLibrary.MaximumResidentClips,["curveValueLimit"]=MotionLibrary.MaximumResidentCurveValues});},features:Features);
    }
}
