// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using Maestro.Quest.Persistence;
using Maestro.Quest.Rules;
using Newtonsoft.Json.Linq;
using static Maestro.Quest.Programs.CapabilitySchema;
namespace Maestro.Quest.Programs
{
    internal sealed class WorkspaceRetentionCapability:CapabilityModule
    {
        readonly string mode;internal WorkspaceRetentionCapability(string mode){this.mode=mode;}
        public override string Id=>"workspace.retention."+mode;
        public override string Label=>mode switch {"inspect"=>"Inspect retained workspaces","export"=>"Export retained workspace","reviewRemoval"=>"Review permanent workspace removal",_=>"Permanently discard retained workspace"};
        public override string Domain=>"workspace";
        public override string Duration=>"completion";
        internal override float CompletionTimeoutSeconds=>600;
        public override string Description=>mode=="reviewRemoval"?
            "Read-only preview of permanent disposal for one inspected generation. Hashes its complete tree, including private recovery evidence and action history. Returns eligible, reason, file count, size, previewId and fingerprint. Protects selected, previous, pointer-backup and live workspaces plus tracked operation dependencies; refuses unavailable or changed history. Historical reservations alone do not permanently prohibit explicit disposal. Export is optional: a portable export omits private recovery files. Preview does not authorize deletion.":mode=="remove"?
            "Permanently discard exactly the eligible generation from workspace.retention.reviewRemoval. Requires that previewId, generationId and fingerprint, and confirmation equal to delete followed by a space and the exact generationId. Obtain explicit user intent to permanently discard this generation and its private recovery evidence/action history; never infer permission from inspection, export or a request to free space. No Undo. Rechecks all files and live dependencies before deletion. Does not touch selected/previous/pointer-backup roots or pending restores. Stop cannot undo deletion after it starts; failure may leave a partial generation. Inspect current state and obtain a fresh preview/confirmation before another attempt. Never automatically replay or retry an uncertain result.":mode=="inspect"?
            "List up to 65 retained generations (64 ordinary slots plus one reserved for explicit recovery), without initializing or changing selection. Read workspace.retention.entry with the returned inspectionId and each index. Metadata availability is not content verification. Roles distinguish active, previous, pointer-backup, inactive or unknown; reservation describes stored activation/recovery dependencies, not deletion permission. A new inspection replaces this session inventory. No private paths or documents are exposed.":
            "Export one inspected inactive generation as an importable portable workspace ZIP in Downloads/Maestro. Validates its actual current saved documents/models/motions/modules and creates a new manifest: originalManifestHash identifies its original import, while output manifestHash identifies exported content, which may include newer autosaves. Refuses active/live sources, changed selection, unavailable required documents and invalid assets; never falls back to old manifests, backup files or empty defaults. excludedFiles counts other files inside its data directory omitted from the portable archive; generation metadata, recovery preservation, action receipts, scans, Undo and chat are not portable content. They remain on-device. Missing-reference and unavailable-program counts describe preserved unresolved references, not repaired content. This is not a full raw backup or permission to delete a generation. Completion means native publication; after interrupted publication check Downloads and the matching receipt instead of assuming failure.";
        public override JObject InputSchema {get{
            var fields=mode=="inspect"?new JObject():mode=="remove"?new JObject {["previewId"]=Text("^[a-f0-9]{32}$",32),["generationId"]=Text("^[a-f0-9]{32}$",32),["fingerprint"]=Text("^[a-f0-9]{64}$",64),["confirmation"]=Text("^delete [a-f0-9]{32}$",39)}:new JObject {["inspectionId"]=Text("^[a-f0-9]{32}$",32),["generationId"]=Text("^[a-f0-9]{32}$",32)};
            if(mode=="export")fields["originalManifestHash"]=Text("^[a-f0-9]{64}$",64);
            var value=Object(fields);value["x-features"]=new JArray(mode is "reviewRemoval" or "remove"?"workspaceDisposal.v1":"workspaceRetention.v1");
            if(mode=="remove")value["x-confirmation"]="Permanently discard this saved workspace, including private recovery files and action history? Export is optional and may omit those files. No Undo. Stop cannot roll back deletion after it starts.";return value;
        }}
        internal static JObject RemovalSchema()=>Object(new JObject {["previewId"]=Text("^[a-f0-9]{32}$",32),["generationId"]=Text("^[a-f0-9]{32}$",32),["fingerprint"]=Text("^([a-f0-9]{64})?$",64),["eligible"]=new JObject {["type"]="boolean"},["reason"]=Text("^[^\\u0000-\\u001f]{0,256}$",256),["files"]=Number(0,16384,true),["sizeMiB"]=Number(0,2048)});
        public override JObject OutputSchema=>mode=="reviewRemoval"?RemovalSchema():mode=="remove"?Object(new JObject {["generationId"]=Text("^[a-f0-9]{32}$",32),["fingerprint"]=Text("^[a-f0-9]{64}$",64),["removed"]=new JObject {["type"]="boolean"}}):mode=="inspect"?Object(new JObject {["inspectionId"]=Text("^[a-f0-9]{32}$",32),["count"]=Number(0,WorkspaceGenerationStore.MaximumRetainedGenerations,true),["selectionReadable"]=new JObject {["type"]="boolean"}}):Object(new JObject {
            ["generationId"]=Text("^[a-f0-9]{32}$",32),["originalManifestHash"]=Text("^[a-f0-9]{64}$",64),["manifestHash"]=Text("^[a-f0-9]{64}$",64),["sourceFingerprint"]=Text("^[a-f0-9]{64}$",64),["location"]=Text("^Downloads/Maestro/.+\\.zip$",128),["archiveHash"]=Text("^[a-f0-9]{64}$",64),["sizeKiB"]=Number(1d/1024,524288),["excludedFiles"]=Number(0,4096,true),["missingImages"]=Number(0,1000000,true),["missingSounds"]=Number(0,4096,true),["missingModels"]=Number(0,4096,true),["missingMotions"]=Number(0,4096,true),["missingControllerPrograms"]=Number(0,4096,true),["unavailablePrograms"]=Number(0,4096,true)});
        public override JObject Example {get{var value=mode=="inspect"?new JObject():mode=="remove"?new JObject {["previewId"]=new string('0',32),["generationId"]=new string('0',32),["fingerprint"]=new string('0',64),["confirmation"]="delete "+new string('0',32)}:new JObject {["inspectionId"]=new string('0',32),["generationId"]=new string('0',32)};if(mode=="export")value["originalManifestHash"]=new string('0',64);return value;}}
        public override bool CanRun(CapabilityContext context,JObject args,out string error){error="Retained workspace operations are unavailable.";return context.Workspace?.Retention?.CanStart(mode,args,out error)==true;}
        public override bool Start(CapabilityContext context,string runId,JObject args,out CapabilityOperation operation,out string error)
        {operation=null;if(!CanRun(context,args,out error))return false;try{operation=new RetentionOperation(context.Workspace.Retention,context.Workspace.Retention.Start(mode,args,runId));return true;}catch(System.Exception){error="Retained workspace operation could not start. Inspect its current state.";return false;}}
        sealed class RetentionOperation:CapabilityOperation
        {
            readonly WorkspaceRetention service;readonly WorkspaceRetention.Job job;
            internal RetentionOperation(WorkspaceRetention service,WorkspaceRetention.Job job){this.service=service;this.job=job;}
            public override float Seconds=>0;
            public override RuleActionState State(out string error){service.Poll();error=job.Error;return job.Pending?RuleActionState.Preparing:error!=null?RuleActionState.Failed:RuleActionState.Ready;}
            public override JObject Result=>job.Result??new JObject();
            public override void Stop(bool preservePlacement)=>service.Cancel(job);
            public override string InterruptionStatus=>"Stopped waiting. Publication or disposal may have happened; inspect workspace.retention, the retained inventory and Downloads before continuing. Never automatically retry disposal.";
        }
    }
    internal static class WorkspaceRetentionFacts
    {
        internal static BehaviourCatalog.FactDefinition Status()=>new("workspace.retention",ProgramDataType.Read(new JObject {["record"]=new JObject {["requestId"]="text",["phase"]="text",["status"]="text",["inspectionId"]="text",["generationId"]="text",["manifestHash"]="text",["location"]="text",["archiveHash"]="text"}}),
            "Retained workspace status","Latest session-local inspection, publication or disposal. requestId is its native execution runId. Exported does not mean restored, reviewed, or removable. Cancelled waits may still finish publication or disposal. Restart clears this status/inventory; durable action receipts remain inspectable.",Object(new JObject()),new JObject(),(context,args)=>context.Workspace?.Retention==null?null:ProgramValue.Literal(context.Workspace.Retention.Status()),domain:"workspace");
        internal static BehaviourCatalog.FactDefinition Removal()=>new("workspace.retention.removal",ProgramDataType.Read(new JObject {["record"]=new JObject {["previewId"]="text",["generationId"]="text",["fingerprint"]="text",["eligible"]="boolean",["reason"]="text",["files"]="number",["sizeMiB"]="number"}}),
            "Permanent removal preview","The latest completed removal preview in this session. eligible is a snapshot, not deletion permission; native removal rechecks the exact fingerprint and dependencies. Protected entries have no fingerprint or file count. Restart, a new inspection or a removal attempt clears this preview. No private paths or file contents are exposed.",Object(new JObject()),new JObject(),(context,args)=>{var value=context.Workspace?.Retention?.Removal();return value==null?null:ProgramValue.Literal(value);},domain:"workspace");
        internal static BehaviourCatalog.FactDefinition Entry()=>new("workspace.retention.entry",ProgramDataType.Read(new JObject {["record"]=new JObject {["generationId"]="text",["originalManifestHash"]="text",["metadataAvailable"]="boolean",["role"]="text",["reservation"]="text"}}),
            "Retained workspace entry","Read one metadata entry from the exact completed inspection. metadataAvailable never asserts valid saved contents. role is active, previous, pointer-backup, inactive or unknown; reservation is reserved, unreserved or unknown. Unknown means evidence could not be interpreted. Original manifest hashes can differ from the actual saved content. None of these fields grants deletion permission; an inactive export verifies content separately.",Object(new JObject {["inspectionId"]=Text("^[a-f0-9]{32}$",32),["index"]=Number(0,WorkspaceGenerationStore.MaximumRetainedGenerations-1,true)}),new JObject {["inspectionId"]=new string('0',32),["index"]=0},(context,args)=>{var value=context.Workspace?.Retention?.Entry((string)args["inspectionId"],(int)args["index"]);return value==null?null:ProgramValue.Literal(value);},domain:"workspace");
    }
}
