// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using System;using System.Collections;using System.IO;using System.Linq;using Maestro.Quest.Creation;using Maestro.Quest.Interaction;using Maestro.Quest.Programs;using Newtonsoft.Json.Linq;using NUnit.Framework;using UnityEngine;using UnityEngine.TestTools;
namespace Maestro.Quest.Tests {public sealed partial class RoomRulesTests {
 JObject FieldCall(string target,string mode="lower",float height=.04f)=>new(){["id"]="object.field.sculpt",["version"]=1,["arguments"]=new JObject{["target"]=target,["revision"]=editor.ObjectRevision(target),["mode"]=mode,["radius"]=.14,["height"]=height,["path"]=new JArray(new JObject{["x"]=-.3,["z"]=0},new JObject{["x"]=.3,["z"]=0})}};
 string Snow(RoomAgentExecutor executor)=>(string)TemplateRun(executor,TemplateCall("snow-patch",new Vector3(4,2,4)))["selected"]["output"]["objectId"];
 [UnityTest] public IEnumerator SharedSculptReadbackCopySaveAndUndoKeepTheSameGrid(){
  var ex=new RoomAgentExecutor(editor);string id=Snow(ex);var before=editor.Read(id).heightFields[0].heights;var request=ContainerRequest(FieldCall(id));Assert.That(ex.Execute(request,out var error,out _),Is.True,error);Assert.That(ex.Execute(request,out error,out _),Is.True,error);var after=editor.Read(id).heightFields[0].heights;Assert.That(after[144],Is.EqualTo(.04f).Within(.000001));Assert.That(new RoomStorage(directory).Load(out _).objects.Single(o=>o.id==id).heightFields[0].heights,Is.EqualTo(after));
  var context=new BehaviourCatalog.FactContext(editor:editor);Assert.That(BehaviourCatalog.TryRead("object.field",1,new JObject{["target"]=id},context,out var summary),Is.True);Assert.That(summary.Characters,Is.LessThanOrEqualTo(1024));var values=new System.Collections.Generic.List<float>();int revision=editor.ObjectRevision(id);
  for(int offset=0;offset<=289;offset+=Math.Min(16,Math.Max(1,289-offset))){Assert.That(BehaviourCatalog.TryRead("object.field.samples",1,new JObject{["target"]=id,["revision"]=revision,["offset"]=offset},context,out var page),Is.True);Assert.That(page.Characters,Is.LessThanOrEqualTo(1024));values.AddRange(((JObject)page.Value)["heights"].Values<float>());if(offset==289)break;}Assert.That(values,Is.EqualTo(after));
  editor.Undo();Assert.That(editor.Read(id).heightFields[0].heights,Is.EqualTo(before));Assert.That(BehaviourCatalog.TryRead("object.field.samples",1,new JObject{["target"]=id,["revision"]=revision,["offset"]=0},context,out _),Is.False);editor.Redo();Assert.That(editor.Read(id).heightFields[0].heights,Is.EqualTo(after));
  Assert.That(editor.CopyObject(id,editor.ObjectRevision(id),"Independent snow",new Vector3(6,2,4),out var copy,out error),Is.True,error);ContainerRun(ex,FieldCall(copy,"raise",.01f));Assert.That(editor.Read(id).heightFields[0].heights,Is.EqualTo(after));yield return null;
 }
 [UnityTest] public IEnumerator FailedOrStaleSculptAndTemporaryDiscardDoNotPublishChanges(){
  var ex=new RoomAgentExecutor(editor);string id=Snow(ex);var before=editor.Read(id).heightFields[0].heights;var stale=FieldCall(id);ContainerRun(ex,FieldCall(id));Assert.That(ex.Execute(ContainerRequest(stale),out _,out _),Is.False);editor.Undo();
  string pending=Path.Combine(directory,RoomStorage.FileName+".pending");Directory.CreateDirectory(pending);try{Assert.That(ex.Execute(ContainerRequest(FieldCall(id)),out _,out _),Is.False);Assert.That(editor.Read(id).heightFields[0].heights,Is.EqualTo(before));}finally{Directory.Delete(pending);}
  Assert.That(editor.BeginTemporaryRoom(out var error),Is.True,error);while(editor.TemporarySavePending)yield return null;ContainerRun(ex,FieldCall(id));Assert.That(editor.Read(id).heightFields[0].heights,Is.Not.EqualTo(before));Assert.That(editor.DiscardTemporaryRoom(out error),Is.True,error);Assert.That(editor.Read(id).heightFields[0].heights,Is.EqualTo(before));
  Assert.That(editor.Ownership.TryAcquire("human","Your edit",RoomActorRole.Control,new[]{new BehaviourCatalog.Claim(id,"wholeTarget")},null,out var lease,out error),Is.True,error);try{Assert.That(ex.Execute(ContainerRequest(FieldCall(id)),out _,out _),Is.False);}finally{lease.Dispose();}
 }
 [UnityTest] public IEnumerator SculptedSnowHasMatchingCollisionAndSupportsAFallingBall(){
  var ex=new RoomAgentExecutor(editor);string id=Snow(ex);ContainerRun(ex,FieldCall(id));var item=editor.Find(id);var field=item.GetComponent<HeightFieldView>();var collider=(MeshCollider)field.Collision;Assert.That(collider.sharedMesh.vertexCount,Is.EqualTo(549));Assert.That(collider.sharedMesh.triangles.Length/3,Is.EqualTo(642));Assert.That(item.Grab.colliders.Contains(collider),Is.True);Assert.That(item.GetComponent<Rigidbody>().isKinematic,Is.True);Assert.That(editor.SetItemPhysics(id,new ObjectPhysicsSettings{mode="solid",shape="automatic",mass=1}),Is.False);
  Physics.SyncTransforms();Assert.That(collider.Raycast(new Ray(item.transform.position+Vector3.up,Vector3.down),out var hit,2),Is.True);Assert.That(hit.point.y,Is.EqualTo(2.04f).Within(.00001));
  Assert.That(editor.CreatePrimitive(RoomObjectKind.Ball,"Snow collision probe",item.transform.position+new Vector3(0,.45f,0),1,Color.red,out var ball,out var error),Is.True,error);Assert.That(editor.SetItemPhysics(ball,new ObjectPhysicsSettings{mode="solid",shape="automatic",mass=.2f}),Is.True);physics.SetSurfaces(true,"Synthetic surface-field setup");physics.StartPhysics();
  // An aimed throw starting in the field must fail without calling unsupported
  // ClosestPoint on a nonconvex mesh. Real overlap geometry is authoritative.
  var ballItem=editor.Find(ball);ballItem.transform.position=item.transform.position+Vector3.up*.06f;ballItem.GetComponent<RigidRoomItem>().Teleported();
  Assert.That(new RoomBallistics().Prepare(ballItem,physics,leftAnchor.transform,ballItem.transform.position+Vector3.forward*.5f,.4f,8,out error),Is.False);StringAssert.Contains("blocked",error);
  ballItem.transform.position=item.transform.position+Vector3.up*.45f;ballItem.GetComponent<RigidRoomItem>().Teleported();
  for(int i=0;i<140;i++)yield return new WaitForFixedUpdate();Assert.That(editor.Find(ball).transform.position.y,Is.InRange(2.10f,2.12f));// Removing support during active play must wake the settled ball and let gravity act.
  ContainerRun(ex,FieldCall(id,"lower",.04f));for(int i=0;i<100;i++)yield return new WaitForFixedUpdate();Assert.That(ballItem.transform.position.y,Is.InRange(2.060f,2.08f));physics.PausePhysics();
  string output=Environment.GetEnvironmentVariable("MAESTRO_HEIGHT_FIELD_PREVIEW");if(!string.IsNullOrEmpty(output)){
   var camera=new GameObject("Sculpted surface acceptance",typeof(Camera)).GetComponent<Camera>();camera.orthographic=true;camera.orthographicSize=.72f;camera.nearClipPlane=.01f;camera.farClipPlane=5;camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(.16f,.22f,.27f);camera.transform.position=item.transform.position+new Vector3(1,1.1f,-1.3f);camera.transform.LookAt(item.transform.position);
   var render=new RenderTexture(1024,1024,24);var pixels=new Texture2D(1024,1024,TextureFormat.RGB24,false);var prior=RenderTexture.active;try{camera.targetTexture=render;camera.Render();RenderTexture.active=render;pixels.ReadPixels(new Rect(0,0,1024,1024),0,0);pixels.Apply();File.WriteAllBytes(output,pixels.EncodeToPNG());}finally{RenderTexture.active=prior;camera.targetTexture=null;render.Release();UnityEngine.Object.Destroy(render);UnityEngine.Object.Destroy(pixels);UnityEngine.Object.Destroy(camera.gameObject);}
  }
  var ownedMesh=collider.sharedMesh;var ownedMaterial=collider.GetComponent<Renderer>().sharedMaterial;Assert.That(editor.PaintObject(id,Color.magenta,out error),Is.True,error);Assert.That(ownedMaterial.GetColor("_Color").g,Is.Zero);
  var remove=new JObject{["id"]="object.field.edit",["version"]=1,["arguments"]=new JObject{["operation"]="remove",["target"]=id,["revision"]=editor.ObjectRevision(id)}};ContainerRun(ex,remove);Assert.That(collider.gameObject.activeSelf,Is.False);Assert.That(item.Grab.colliders.Contains(collider),Is.False);Assert.That(editor.SetItemPhysics(id,new ObjectPhysicsSettings{mode="solid",shape="automatic",mass=1}),Is.True);yield return null;Assert.That(ownedMesh==null,Is.True);Assert.That(ownedMaterial==null,Is.True);
 }
}}
