// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using System;
using System.Collections;
using System.IO;
using System.Linq;
using Maestro.Quest.Creation;
using Maestro.Quest.Interaction;
using Maestro.Quest.Programs;
using Newtonsoft.Json.Linq;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using UnityEngine.XR.Interaction.Toolkit.Interactors;
namespace Maestro.Quest.Tests {public sealed partial class RoomRulesTests {
    (string id,SculptTipView view) MaterialScoopProp(){var result=TemplateRun(new RoomAgentExecutor(editor),TemplateCall("material-scoop",new Vector3(6,2,4)));string id=(string)result["selected"]["output"]["objectId"];var view=editor.Find(id).GetComponent<SculptTipView>();view.Sample(false,RoomActorRole.Control);return(id,view);}
    void PlaceMaterialScoop(string id,HeightFieldView field,bool deposit=false,float lift=0,float x=0){var item=editor.Find(id);var tip=editor.Read(id).sculptTips[0];item.transform.rotation=field.Surface.rotation*(deposit?Quaternion.Euler(180,0,0):Quaternion.identity);item.transform.position=SculptContact(field,x)+field.Surface.up*lift-item.transform.TransformVector(tip.position);Physics.SyncTransforms();}
    double MaterialAmount(string id)=>editor.Read(id).materialStores[0].amountLitres;
    [UnityTest] public IEnumerator MaterialScoopRealGripTakesOnceShowsContentsAndDepositsWithAtomicUndo(){
        var(field,view,capture)=SculptStage();var(tool,contact)=MaterialScoopProp();var item=editor.Find(tool);var contents=item.GetComponent<MaterialToolContentsView>();var before=editor.Read(field).heightFields[0];var collider=(MeshCollider)view.Collision;var accepted=collider.sharedMesh;
        PlaceMaterialScoop(tool,view);contact.SendMessage("LateUpdate");Assert.That(capture.Busy,Is.False);Assert.That(contents.Visible,Is.False);
        var hand=Hand(1,item.transform.position);manager.SelectEnter((IXRSelectInteractor)hand,item.Grab);contact.SendMessage("LateUpdate");Assert.That(capture.Active,Is.True);Assert.That(MaterialAmount(tool),Is.Zero);Assert.That(contents.Visible,Is.True);Assert.That(collider.sharedMesh,Is.SameAs(accepted));
        var fact=SculptFact("object.material.capture");Assert.That((string)fact["direction"],Is.EqualTo("take"));Assert.That((double)fact["balance"]["previewLitres"],Is.InRange(.24999,.25));for(int i=0;i<20;i++)contact.SendMessage("LateUpdate");Assert.That(SculptFact("object.material.capture"),Is.EqualTo(fact));Assert.That(editor.PaintObject(tool,Color.red,out _),Is.False);
        PlaceMaterialScoop(tool,view,false,.15f);contact.SendMessage("LateUpdate");Assert.That(capture.Busy,Is.False);double taken=MaterialAmount(tool);Assert.That(taken,Is.InRange(.24999,.25));Assert.That(before.VolumeLitres-editor.Read(field).heightFields[0].VolumeLitres,Is.EqualTo(taken).Within(.000001));Assert.That(contents.Visible,Is.True);Assert.That((string)SculptFact("object.material.capture")["phase"],Is.EqualTo("idle"));
        var saved=new RoomStorage(directory).Load(out var error);Assert.That(saved.objects.Single(o=>o.id==tool).materialStores[0].amountLitres,Is.EqualTo(taken).Within(1e-12),error);Assert.That(saved.objects.Single(o=>o.id==tool).position,Is.EqualTo(item.transform.localPosition));
        PlaceMaterialScoop(tool,view,true,0,.25f);contact.SendMessage("LateUpdate");Assert.That((string)SculptFact("object.material.capture")["direction"],Is.EqualTo("deposit"));Assert.That(MaterialAmount(tool),Is.EqualTo(taken));Assert.That(contents.Visible,Is.False);
        PlaceMaterialScoop(tool,view,true,.15f,.25f);contact.SendMessage("LateUpdate");manager.SelectExit((IXRSelectInteractor)hand,item.Grab);contact.SendMessage("LateUpdate");Assert.That(capture.Busy,Is.False);Assert.That(MaterialAmount(tool),Is.LessThan(.000001));Assert.That(editor.Read(field).heightFields[0].VolumeLitres,Is.EqualTo(before.VolumeLitres).Within(.000002));
        editor.Undo();Assert.That(MaterialAmount(tool),Is.EqualTo(taken));Assert.That(contents.Visible,Is.True);editor.Undo();Assert.That(MaterialAmount(tool),Is.Zero);Assert.That(editor.Read(field).heightFields[0].heights,Is.EqualTo(before.heights));Assert.That(contents.Visible,Is.False);editor.Redo();Assert.That(MaterialAmount(tool),Is.EqualTo(taken));yield return null;
    }
    [UnityTest] public IEnumerator MaterialScoopFailedSaveRetainsBothDraftsAndExplicitRetryCannotReplay(){
        var(field,view,capture)=SculptStage();var(tool,contact)=MaterialScoopProp();var before=editor.Read(field).heightFields[0];PlaceMaterialScoop(tool,view);contact.Sample(true,RoomActorRole.Control);Assert.That(capture.Active,Is.True);string pending=Path.Combine(directory,RoomStorage.FileName+".pending");Directory.CreateDirectory(pending);
        try{PlaceMaterialScoop(tool,view,false,.15f);contact.Sample(true,RoomActorRole.Control);Assert.That(capture.Retained,Is.True);Assert.That(MaterialAmount(tool),Is.Zero);Assert.That(editor.Read(field).heightFields[0].heights,Is.EqualTo(before.heights));Assert.That(editor.PaintObject(tool,Color.red,out _),Is.False);Assert.That(editor.BeginTemporaryRoom(out _),Is.False);}finally{Directory.Delete(pending);}
        string session=capture.SessionId;for(int i=0;i<4;i++)contact.Sample(false,RoomActorRole.Control);Assert.That(capture.SessionId,Is.EqualTo(session));Assert.That(MaterialAmount(tool),Is.Zero);var request=ContainerRequest(SculptResolve(capture));var executor=new RoomAgentExecutor(editor);Assert.That(executor.Execute(request,out var error,out _),Is.True,error);int revision=editor.ObjectRevision(tool);double amount=MaterialAmount(tool);Assert.That(amount,Is.GreaterThan(0));Assert.That(executor.Execute(request,out error,out _),Is.True,error);Assert.That(editor.ObjectRevision(tool),Is.EqualTo(revision));Assert.That(MaterialAmount(tool),Is.EqualTo(amount));editor.Undo();Assert.That(MaterialAmount(tool),Is.Zero);Assert.That(editor.Read(field).heightFields[0].heights,Is.EqualTo(before.heights));yield return null;
    }
    [UnityTest] public IEnumerator MaterialScoopObstructionsAndActorTakeoverRequireExplicitRecoveryAndSeparation(){
        var(field,view,capture)=SculptStage();var(tool,contact)=MaterialScoopProp();PlaceMaterialScoop(tool,view);var wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.transform.SetParent(root.transform);wall.transform.position=SculptContact(view)+view.Surface.up*.012f;wall.transform.localScale=new Vector3(.1f,.004f,.1f);contact.Sample(true,RoomActorRole.Program);Assert.That(capture.Busy,Is.False);UnityEngine.Object.DestroyImmediate(wall);
        contact.Sample(true,RoomActorRole.Program);Assert.That(capture.Active,Is.True);contact.Sample(true,RoomActorRole.Control);Assert.That(capture.Retained,Is.True);Assert.That(MaterialAmount(tool),Is.Zero);capture.ResolveManual(true);contact.Sample(true,RoomActorRole.Control);Assert.That(capture.Busy,Is.False);PlaceMaterialScoop(tool,view,false,.1f);contact.Sample(true,RoomActorRole.Control);PlaceMaterialScoop(tool,view);contact.Sample(true,RoomActorRole.Control);Assert.That(capture.Active,Is.True);contact.enabled=false;Assert.That(capture.Retained,Is.True);Assert.That(MaterialAmount(tool),Is.Zero);capture.ResolveManual(true);yield return null;
    }
    [UnityTest] public IEnumerator MaterialScoopProgramCannotPreemptHumanOrOverwriteAChangedSurface(){
        var(field,view,capture)=SculptStage();var(tool,contact)=MaterialScoopProp();var claims=new[]{new BehaviourCatalog.Claim(field,"wholeTarget")};Assert.That(editor.Ownership.TryAcquire("human","Human edit",RoomActorRole.Control,claims,null,out var lease,out var error),Is.True,error);
        PlaceMaterialScoop(tool,view);contact.Sample(true,RoomActorRole.Program);Assert.That(capture.Busy,Is.False);lease.Dispose();contact.Sample(true,RoomActorRole.Program);Assert.That(capture.Busy,Is.False);PlaceMaterialScoop(tool,view,false,.1f);contact.Sample(true,RoomActorRole.Program);PlaceMaterialScoop(tool,view);contact.Sample(true,RoomActorRole.Program);Assert.That(capture.Active,Is.True);
        Assert.That(editor.Ownership.TryAcquire("human","Human edit",RoomActorRole.Control,claims,null,out lease,out error),Is.True,error);Assert.That(capture.Retained,Is.True);Assert.That(capture.CanResolve(capture.SessionId,false,out _),Is.False);
        Assert.That(editor.SculptHeightField(field,editor.ObjectRevision(field),"lower",new[]{Vector2.zero},.1f,.01f,out _,out error),Is.True,error);lease.Dispose();var changed=editor.Read(field).heightFields[0].heights;Assert.That(capture.Resolve(capture.SessionId,false,out _,out _),Is.False);Assert.That(MaterialAmount(tool),Is.Zero);capture.ResolveManual(true);Assert.That(editor.Read(field).heightFields[0].heights,Is.EqualTo(changed));Assert.That(view.Surface.GetComponent<MeshFilter>().sharedMesh,Is.SameAs(((MeshCollider)view.Collision).sharedMesh));yield return null;
    }
    [UnityTest] public IEnumerator MaterialScoopTemporaryDiscardRestoresBothObjectsAndCapacityStopsAnotherDose(){
        var(field,view,capture)=SculptStage();var(tool,contact)=MaterialScoopProp();var before=editor.Read(field).heightFields[0];Assert.That(editor.BeginTemporaryRoom(out var error),Is.True,error);float deadline=Time.realtimeSinceStartup+5;while(editor.TemporarySavePending&&Time.realtimeSinceStartup<deadline)yield return null;Assert.That(editor.TemporarySavePending,Is.False);Assert.That(editor.TemporarySaveError,Is.Null);PlaceMaterialScoop(tool,view);contact.Sample(true,RoomActorRole.Control);PlaceMaterialScoop(tool,view,false,.1f);contact.Sample(true,RoomActorRole.Control);Assert.That(MaterialAmount(tool),Is.GreaterThan(.24999));int revision=editor.ObjectRevision(tool);PlaceMaterialScoop(tool,view);contact.Sample(true,RoomActorRole.Control);Assert.That(capture.Busy,Is.False);Assert.That(editor.ObjectRevision(tool),Is.EqualTo(revision));contact.Sample(false,RoomActorRole.Control);Assert.That(editor.DiscardTemporaryRoom(out error),Is.True,error);Assert.That(MaterialAmount(tool),Is.Zero);Assert.That(editor.Read(field).heightFields[0].heights,Is.EqualTo(before.heights));yield return null;
    }
}}
