// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using System;using System.Collections;using System.IO;using System.Linq;
using Maestro.Quest.Creation;using Maestro.Quest.Interaction;using Maestro.Quest.Programs;
using Newtonsoft.Json.Linq;using NUnit.Framework;using UnityEngine;using UnityEngine.TestTools;
using UnityEngine.XR.Interaction.Toolkit.Interactors;
namespace Maestro.Quest.Tests {public sealed partial class RoomRulesTests {
 (string id,HeightFieldView view,SpatialSculpting capture) SculptStage(){var id=Snow(new RoomAgentExecutor(editor));var capture=editor.Sculpting;Assert.That(capture.Configure("lower",.12f,.03f,out var error),Is.True,error);return(id,editor.Find(id).GetComponent<HeightFieldView>(),capture);}
 Ray SculptRay(HeightFieldView view,float x=0,float z=0)=>new(view.Surface.TransformPoint(new Vector3(x,.20f,z)),-view.Surface.up);
 Vector3 SculptContact(HeightFieldView view,float x=0,float z=0)=>view.Surface.TransformPoint(new Vector3(x,view.Accepted.HeightAt(new Vector2(x,z)),z));
 JObject SculptResolve(SpatialSculpting capture,bool discard=false)=>new(){["id"]="object.field.resolve",["version"]=1,["arguments"]=new JObject{["sessionId"]=capture.SessionId,["operation"]=discard?"discard":"retry"}};
 JObject SculptFact(string id,JObject args=null){Assert.That(BehaviourCatalog.TryRead(id,1,args,new BehaviourCatalog.FactContext(editor:editor),out var fact),Is.True,id);Assert.That(fact.Characters,Is.LessThanOrEqualTo(1024));return (JObject)fact.Value;}
 [UnityTest] public IEnumerator PhysicalSculptPreviewPublishesOneExactEditAndUndo(){
  var(id,view,capture)=SculptStage();var before=editor.Read(id).heightFields[0];int revision=editor.ObjectRevision(id);var collider=(MeshCollider)view.Collision;var accepted=collider.sharedMesh;float initial=accepted.vertices[144].y;
  capture.Begin(0,SculptRay(view));Assert.That(capture.Active,Is.True);Assert.That(view.Surface.GetComponent<MeshFilter>().sharedMesh,Is.Not.SameAs(accepted));Assert.That(collider.sharedMesh,Is.SameAs(accepted));Assert.That(accepted.vertices[144].y,Is.EqualTo(initial));Assert.That(editor.ObjectRevision(id),Is.EqualTo(revision));
  for(int i=0;i<20;i++)capture.Move(0,SculptRay(view));Assert.That((int)SculptFact("object.field.capture")["points"],Is.EqualTo(1));capture.Move(0,SculptRay(view,.2f));Assert.That((string)SculptFact("object.field.capture")["brush"]["mode"],Is.EqualTo("lower"));
  var path=SculptFact("object.field.capture.path",new JObject{["sessionId"]=capture.SessionId,["offset"]=0})["points"].Select(p=>new Vector2((float)p["x"],(float)p["z"])).ToArray();Assert.That(SculptFact("object.field.capture.path",new JObject{["sessionId"]=capture.SessionId,["offset"]=path.Length})["points"],Is.Empty);
  var expected=before.Copy();Assert.That(expected.Sculpt("lower",path,.12f,.03f,out _,out var error),Is.True,error);capture.End(0);Assert.That(capture.Busy,Is.False);Assert.That(editor.Read(id).heightFields[0].heights,Is.EqualTo(expected.heights));Assert.That(collider.sharedMesh.vertices[144].y,Is.EqualTo(expected.heights[144]));Assert.That(new RoomStorage(directory).Load(out _).objects.Single(o=>o.id==id).heightFields[0].heights,Is.EqualTo(expected.heights));
  editor.Undo();Assert.That(editor.Read(id).heightFields[0].heights,Is.EqualTo(before.heights));editor.Redo();Assert.That(editor.Read(id).heightFields[0].heights,Is.EqualTo(expected.heights));yield return null;
 }
 [UnityTest] public IEnumerator PhysicalSculptFailureRetainsExactDraftAndSharedRetryIsIdempotent(){
  var(id,view,capture)=SculptStage();var before=editor.Read(id).heightFields[0].heights;capture.Begin(0,SculptRay(view));capture.Move(0,SculptRay(view,.2f));string pending=Path.Combine(directory,RoomStorage.FileName+".pending");Directory.CreateDirectory(pending);
  try{capture.End(0);Assert.That(capture.Retained,Is.True);Assert.That(editor.Read(id).heightFields[0].heights,Is.EqualTo(before));Assert.That(((MeshCollider)view.Collision).sharedMesh.vertices[144].y,Is.EqualTo(before[144]));Assert.That((string)SculptFact("object.field.capture")["phase"],Is.EqualTo("unsaved"));Assert.That(editor.BeginTemporaryRoom(out _),Is.False);editor.Undo();Assert.That(editor.Read(id),Is.Not.Null);}finally{Directory.Delete(pending);}
  string session=capture.SessionId;capture.Begin(1,SculptRay(view));Assert.That(capture.SessionId,Is.EqualTo(session));var request=ContainerRequest(SculptResolve(capture));var ex=new RoomAgentExecutor(editor);Assert.That(ex.Execute(request,out var error,out _),Is.True,error);Assert.That(capture.Busy,Is.False);int revision=editor.ObjectRevision(id);Assert.That(ex.Execute(request,out error,out _),Is.True,error);Assert.That(editor.ObjectRevision(id),Is.EqualTo(revision));editor.Undo();Assert.That(editor.Read(id).heightFields[0].heights,Is.EqualTo(before));yield return null;
 }
 [UnityTest] public IEnumerator PhysicalSculptFingerRequiresSeparationAndTrackingLossRetains(){
  var(id,view,capture)=SculptStage();var contact=SculptContact(view);capture.Finger(0,contact);Assert.That(capture.Active,Is.False);capture.Finger(0,contact+view.Surface.up*.1f);capture.Finger(0,contact);Assert.That(capture.Active,Is.True);capture.Finger(0,null);Assert.That(capture.Retained,Is.True);Assert.That((string)SculptFact("object.field.capture")["phase"],Is.EqualTo("unsaved"));ContainerRun(new RoomAgentExecutor(editor),SculptResolve(capture,true));Assert.That(view.Surface.GetComponent<MeshFilter>().sharedMesh,Is.SameAs(((MeshCollider)view.Collision).sharedMesh));
  capture.Finger(0,contact);Assert.That(capture.Active,Is.False);capture.Finger(0,contact+view.Surface.up*.1f);capture.Finger(0,contact);Assert.That(capture.Active,Is.True);capture.Finger(0,contact+view.Surface.up*.1f);Assert.That(capture.Busy,Is.False);Assert.That(editor.Read(id).heightFields[0].heights[144],Is.EqualTo(.05f).Within(.00001));yield return null;
 }
 [UnityTest] public IEnumerator PhysicalSculptContactUsesAcceptedRotatedGeometryAndSolidOcclusion(){
  var(id,view,capture)=SculptStage();var item=editor.Find(id);item.transform.rotation=Quaternion.Euler(18,35,12);item.transform.localScale=Vector3.one*1.5f;var contact=SculptContact(view,.11f,.08f);Assert.That(editor.FindHeightFieldNear(contact,null,out var found,out var local),Is.True);Assert.That(found,Is.EqualTo(id));Assert.That(local.x,Is.EqualTo(.11f).Within(.00001));Assert.That(editor.FindHeightFieldNear(contact+view.Surface.up*.02f,null,out _,out _),Is.False);Assert.That(editor.FindHeightField(new Ray(contact-view.Surface.up*.1f,view.Surface.up),.2f,null,out _,out _,out _),Is.False);
  var wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.transform.SetParent(root.transform);wall.transform.SetPositionAndRotation(contact+view.Surface.up*.035f,view.Surface.rotation);wall.transform.localScale=new Vector3(.1f,.02f,.1f);Assert.That(editor.FindHeightField(new Ray(contact+view.Surface.up*.1f,-view.Surface.up),.2f,null,out _,out _,out _),Is.False);UnityEngine.Object.DestroyImmediate(wall);
  view.Collision.enabled=false;Assert.That(editor.FindHeightFieldNear(contact,null,out _,out _),Is.False);view.Collision.enabled=true;capture.Begin(0,SculptRay(view));Assert.That(capture.Active,Is.True);capture.Cancel(0);ContainerRun(new RoomAgentExecutor(editor),SculptResolve(capture,true));yield return null;
 }
 (string id,SculptTipView view) SculptProp(){var result=TemplateRun(new RoomAgentExecutor(editor),TemplateCall("sculpt-brush",new Vector3(6,2,4)));string id=(string)result["selected"]["output"]["objectId"];var view=editor.Find(id).GetComponent<SculptTipView>();view.Sample(false,RoomActorRole.Control);return(id,view);}
 void PlaceSculptProp(string id,HeightFieldView field,float x=0,float lift=0){var item=editor.Find(id);var tip=editor.Read(id).sculptTips[0];item.transform.rotation=Quaternion.LookRotation(-field.Surface.up,field.Surface.forward);item.transform.position=SculptContact(field,x)+field.Surface.up*lift-item.transform.TransformVector(tip.position);}
 [UnityTest] public IEnumerator PhysicalSculptRealGripUsesSavedTipAndLooseToolsStayInert(){
  var(id,field,capture)=SculptStage();Assert.That(capture.Configure("off",.3f,.2f,out var error),Is.True,error);var(tool,view)=SculptProp();PlaceSculptProp(tool,field);view.SendMessage("LateUpdate");Assert.That(capture.Active,Is.False);var item=editor.Find(tool);var hand=Hand(1,item.transform.position);manager.SelectEnter((IXRSelectInteractor)hand,item.Grab);view.SendMessage("LateUpdate");Assert.That(capture.OwnsTool(tool),Is.True);PlaceSculptProp(tool,field,.2f);view.SendMessage("LateUpdate");manager.SelectExit((IXRSelectInteractor)hand,item.Grab);view.SendMessage("LateUpdate");Assert.That(capture.Busy,Is.False);Assert.That(capture.Mode,Is.EqualTo("off"));Assert.That(capture.Height,Is.EqualTo(.2f));Assert.That(editor.Read(id).heightFields[0].heights[144],Is.EqualTo(.05f).Within(.00001));editor.Undo();Assert.That(editor.Read(id).heightFields[0].heights[144],Is.EqualTo(.08f).Within(.00001));yield return null;
 }
 [UnityTest] public IEnumerator PhysicalSculptProgramToolCannotPreemptHumanAndInterruptionNeverAutoSaves(){
  var(id,field,capture)=SculptStage();var(tool,view)=SculptProp();var claims=new[]{new BehaviourCatalog.Claim(id,"wholeTarget")};Assert.That(editor.Ownership.TryAcquire("human","Human edit",RoomActorRole.Control,claims,null,out var lease,out var error),Is.True,error);PlaceSculptProp(tool,field);view.Sample(true,RoomActorRole.Program);Assert.That(capture.Busy,Is.False);lease.Dispose();view.Sample(true,RoomActorRole.Program);Assert.That(capture.Busy,Is.False);PlaceSculptProp(tool,field,0,.1f);view.Sample(true,RoomActorRole.Program);PlaceSculptProp(tool,field);view.Sample(true,RoomActorRole.Program);Assert.That(capture.Active,Is.True);
  Assert.That(editor.Ownership.TryAcquire("human","Human edit",RoomActorRole.Control,claims,null,out lease,out error),Is.True,error);Assert.That(capture.Retained,Is.True);Assert.That(capture.CanResolve(capture.SessionId,false,out _),Is.False);lease.Dispose();capture.ResolveManual(true);view.Sample(true,RoomActorRole.Program);Assert.That(capture.Busy,Is.False);PlaceSculptProp(tool,field,0,.1f);view.Sample(true,RoomActorRole.Program);PlaceSculptProp(tool,field);view.Sample(true,RoomActorRole.Program);Assert.That(capture.Active,Is.True);int revision=editor.ObjectRevision(id);view.enabled=false;Assert.That(capture.Retained,Is.True);Assert.That(editor.ObjectRevision(id),Is.EqualTo(revision));capture.ResolveManual(true);yield return null;
 }
 [UnityTest] public IEnumerator PhysicalSculptBoundedPathCannotRestartWithoutAnotherGesture(){
  var(id,view,capture)=SculptStage();Assert.That(capture.Configure("lower",.02f,.01f,out var error),Is.True,error);capture.Begin(0,SculptRay(view,-.4f));for(int i=1;i<32;i++)capture.Move(0,SculptRay(view,-.4f+i*.02f));Assert.That(capture.Busy,Is.False);int revision=editor.ObjectRevision(id);capture.Move(0,SculptRay(view,.3f));Assert.That(editor.ObjectRevision(id),Is.EqualTo(revision));editor.Undo();Assert.That(editor.Read(id).heightFields[0].heights.All(h=>Mathf.Approximately(h,.08f)),Is.True);yield return null;
 }
}}
