// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
import {ProgramEditor} from './ProgramEditor';
import {capabilityResources} from '../../../shared/capabilities';
import type {OpenCatalog} from './CapabilityBrowser';
import {parseProgram,sequenceProgram,simpleProgramSteps,withSimpleProgramSteps} from '../../core-sdk/room/programs';
import {useCallback,useEffect,useState,useSyncExternalStore} from 'react';
import {RoomOwnershipDetails} from './RoomOwnershipDetails';
import type {RoomAgentState} from '../../core-sdk/room/roomAgent';
import {copySequence,newRuleStep,validSequence,ruleActions,ruleGestures,ruleEvents,ruleConditions,rulePolicies,ruleMounts,type RuleSequence,type RuleEdit,type RuleRequest,type RuleStep} from '../../core-sdk/room/rules';
import type {RoomAgentClient} from './roomAgentBridge';

type Draft={sequence:RuleSequence;source:RoomAgentState;revision:number};
const draftOf=(state:RoomAgentState):Draft|null=>state.rules?.selected?{sequence:copySequence(state.rules.selected),source:state,revision:state.rules.revision}:null;
export function RuleWorkspace({client,onCatalog}:{client:RoomAgentClient;onCatalog?:OpenCatalog}) {
 const {state,pending}=useSyncExternalStore(client.subscribe,client.getSnapshot);
 const [draft,setDraft]=useState<Draft|null>(null),[dirty,setDirty]=useState(false),[error,setError]=useState('');
 const [advanced,setAdvanced]=useState(false);
 const [programEditing,setProgramEditing]=useState(false),[editorReset,setEditorReset]=useState(0);
 const editProgram=useCallback((value:boolean)=>{setProgramEditing(value);if(value)setDirty(true);},[]);
 const [trigger,setTrigger]=useState(0),[condition,setCondition]=useState(0),[source,setSource]=useState('maestro'),[whileState,setWhileState]=useState(false);
 useEffect(()=>{if(!dirty&&state)setDraft(draftOf(state));},[state?.rules?.revision,state?.rules?.selected?.id,dirty]);
 if(!state?.visible||!state.rules)return null;
 const rules=state.rules,sequence=draft?.sequence,steps=sequence?simpleProgramSteps(sequence.program):null;
 const supported=state.capabilities?.includes('behaviourPrograms.v3')===true;
 const stale=Boolean(draft&&(draft.source.session!==state.session||draft.revision!==rules.revision)),blocked=pending||rules.readOnly||stale||!supported;
 const send=async(rule:RuleRequest,expected?:RoomAgentState)=>{setError('');try {const result=await client.request([{action:'rules',rule}],expected);if(!result.ok)setError(result.status);return result;}catch(e){setError(e instanceof Error?e.message:'This action could not be completed.');return null;}};
 const edit=async(edits:RuleEdit[],expected=state)=>send({action:'edit',revision:expected.rules!.revision,edits},expected);
 const change=(fn:(value:RuleSequence)=>void)=>{if(!draft)return;const value=copySequence(draft.sequence);fn(value);setDraft({...draft,sequence:value});setDirty(true);};
 const save=async()=>{if(!draft||!validSequence(draft.sequence,true)){setError('Check the name, targets and durations before applying.');return;}const result=await edit([{kind:'save',sequence:draft.sequence}],draft.source);if(result?.ok){setDirty(false);setDraft(draftOf(result));}};
 const changeSteps=(fn:(steps:RuleStep[])=>void)=>change(value=>{const steps=simpleProgramSteps(value.program);if(steps===null)return;fn(steps);value.program=withSimpleProgramSteps(value.program,steps);});
 const updateStep=(index:number,fn:(step:RuleStep)=>void)=>changeSteps(steps=>fn(steps[index]));
 const create=async()=>{const target=state.objects.find(o=>o.kind==='Assembly');const step=newRuleStep(target?8:1);step.targetId=target?.id??'maestro';await edit([{kind:'save',reference:'newBehaviour',sequence:{id:'',name:'New behaviour',interruption:0,repeat:false,program:JSON.stringify(sequenceProgram([step]))}}]);};
 const browse=()=>onCatalog?.(draft&&!blocked?call=>{
  const parsed=parseProgram(draft.sequence.program);if(!parsed.program)return parsed.error??'Invalid draft.';
  const program=parsed.program,entry=program.functions.find(f=>f.name===program.entry)!;
  entry.body.unshift({id:crypto.randomUUID().replace(/-/g,''),op:'invoke',capability:call.id,version:call.version,arguments:call.arguments,bindings:{}});
  program.resources=[...new Set([...program.resources,...capabilityResources(call.id,call.arguments)])];
  const source=JSON.stringify(program),validated=parseProgram(source);if(validated.error)return validated.error;
  setDraft({...draft,sequence:{...draft.sequence,program:source}});setDirty(true);setEditorReset(value=>value+1);return null;
 }:undefined);
 const exit=async(objects:boolean)=>{try {const result=await client.request(objects?[{action:'inspect',target:state.selectedId??state.objects[0]?.id??'maestro'}]:[{action:'workspace',visible:false}]);if(!result.ok)setError(result.status);else setDirty(false);}catch(e){setError(e instanceof Error?e.message:'The book is unavailable.');}};
 return <div className="room-workspace rule-workspace" aria-label="Behaviour workspace">
  <section className="room-workspace-page room-hierarchy" aria-label="Behaviours and triggers">
   <div className="room-workspace-heading"><div><span className="room-eyebrow">WHEN THIS HAPPENS</span><h1>Behaviours</h1></div><button disabled={pending} onClick={()=>void exit(false)}>{dirty?'Discard & return':'Back to chat'}</button></div>
   <p className="room-workspace-intro">Build actions together. The agent, these blocks and your physical buttons use the same behaviours.</p>
   <div className="room-workspace-actions">{onCatalog&&<button disabled={pending||programEditing||!state.capabilities?.includes('catalog.v1')} onClick={browse}>Action catalog</button>}<button disabled={pending||dirty||programEditing} onClick={()=>void exit(true)}>Objects</button><button disabled={pending||dirty||rules.readOnly||programEditing||!supported} onClick={()=>void create()}>+ Behaviour</button><button disabled={pending||dirty||!rules.canUndo} onClick={()=>void send({action:'undo',revision:rules.revision})}>Undo</button><button disabled={pending||dirty||!rules.canRedo} onClick={()=>void send({action:'redo',revision:rules.revision})}>Redo</button></div>
   <RoomOwnershipDetails state={state}/>
   <div className="room-object-list" aria-label="Behaviours">{rules.sequences.map(value=><button key={value.id} disabled={pending||dirty||programEditing} aria-pressed={sequence?.id===value.id} onClick={()=>void send({action:'inspect',target:value.id})}><span>{value.name}</span><small>{value.steps} {value.program?'blocks':'steps'}{value.repeat?' · Repeats':''}{value.error?' · Unavailable':''}{rules.running.some(run=>run.sequenceId===value.id)?' · Running':''}</small></button>)}</div>
   {sequence&&<>
    <h2 className="rule-section-title">Triggers</h2>
    {rules.bindings.map(binding=><div className="rule-event-block" key={binding.id}><strong>When {ruleEvents[binding.trigger].toLowerCase()}</strong><p>{binding.trigger>=4?state.objects.find(o=>o.id===binding.sourceId)?.name??'Missing object':'Maestro state'} · If {ruleConditions[binding.condition].toLowerCase()}{binding.stopOnExit?' · Stop on exit':''}</p><div className="room-workspace-actions"><button disabled={blocked||dirty||programEditing} onClick={()=>void edit([{kind:'bind',binding:{...binding,enabled:!binding.enabled}}])}>{binding.enabled?'Disable':'Enable'}</button><button disabled={blocked||dirty||programEditing} onClick={()=>void edit([{kind:'unbind',target:binding.id}])}>Remove trigger</button></div></div>)}
    {rules.bindingCount>8&&<div className="room-workspace-actions"><button disabled={pending||dirty||rules.bindingPage===0} onClick={()=>void send({action:'inspect',target:sequence.id,page:rules.bindingPage-1})}>Previous triggers</button><span>{rules.bindingPage+1} / {Math.ceil(rules.bindingCount/8)}</span><button disabled={pending||dirty||(rules.bindingPage+1)*8>=rules.bindingCount} onClick={()=>void send({action:'inspect',target:sequence.id,page:rules.bindingPage+1})}>Next triggers</button></div>}
    <fieldset disabled={blocked||dirty||programEditing}><legend>Add a trigger</legend><label>When<select value={trigger} onChange={e=>setTrigger(Number(e.target.value))}>{ruleEvents.map((name,index)=><option value={index} key={name}>{name}</option>)}</select></label>{trigger>=4&&<label>Object<select value={source} onChange={e=>setSource(e.target.value)}>{state.objects.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}<label>Only if<select value={condition} onChange={e=>setCondition(Number(e.target.value))}>{ruleConditions.map((name,index)=><option key={name} value={index}>{name}</option>)}</select></label><label className="rule-checkbox"><input type="checkbox" checked={whileState} onChange={e=>setWhileState(e.target.checked)}/>Stop when the state ends</label><button onClick={()=>void edit([{kind:'bind',binding:{id:'',sequenceId:sequence.id,sourceId:trigger>=4?source:null,trigger,condition,cooldown:1,enabled:true,stopOnExit:whileState}}])}>Add trigger</button></fieldset>
    <h2>Physical buttons</h2><p className="room-workspace-intro">Controller buttons can be pressed with the other hand.</p>
    {rules.buttons.map(button=><div className="room-workspace-actions" key={button.id}><span>{ruleMounts[button.mount]}</span><button disabled={blocked||dirty||programEditing} onClick={()=>void edit([{kind:'unbutton',target:button.id}])}>Remove button</button></div>)}
    <div className="room-workspace-actions">{ruleMounts.map((name,mount)=><button disabled={blocked||dirty||programEditing} key={name} onClick={()=>void edit([{kind:'button',target:sequence.id,mount}])}>+ {name}</button>)}</div>
   </>}
  </section>
  <section className="room-workspace-page room-inspector" aria-label="Behaviour blocks">
   <div className="room-workspace-heading"><div><span className="room-eyebrow">DO THESE ACTIONS</span><h2>{sequence?.name??'Choose a behaviour'}</h2></div><button disabled={pending} onClick={()=>void send({action:'stop'})}>Stop all</button></div>
   <div role="status" className={error||stale?'room-message room-message-warning':'room-message'}>{error||(!supported?'Update the native app to edit behaviours.':stale?'Behaviours changed. Your draft is retained; reload before applying.':rules.status)}</div>
   {rules.outcomes?.filter(outcome=>outcome.sequenceId===sequence?.id).slice(-1).map(outcome=><p className="room-message" key={outcome.id}>Last run: {outcome.phase} · {outcome.status}</p>)}
   {rules.queued>0&&<p>{rules.queued} queued actions</p>}
   {sequence&&<>
    {rules.selectedError&&<p role="alert" className="room-message room-message-warning">Unavailable: {rules.selectedError}. Its triggers and buttons cannot run until repaired. You can repair or delete it below.</p>}
    <div className="room-workspace-actions"><button disabled={blocked||!dirty||programEditing} onClick={()=>void save()}>Apply changes</button><button disabled={pending||!dirty&&!stale} onClick={()=>{setDraft(draftOf(state));setDirty(false);setError('');setEditorReset(value=>value+1);}}>{stale?'Reload latest':'Discard draft'}</button><button disabled={blocked||dirty||programEditing||Boolean(rules.selectedError)} onClick={()=>void send({action:'play',target:sequence.id,revision:rules.revision})}>Try behaviour</button>{state.capabilities?.includes('eventPrograms.v1')&&<button disabled={pending||!rules.running.some(run=>run.sequenceId===sequence.id)} onClick={()=>void send({action:'stop',target:sequence.id})}>Stop this behaviour</button>}</div>
    <fieldset disabled={blocked} className="room-edit-body"><label>Name<input maxLength={32} value={sequence.name} onChange={e=>change(value=>{value.name=e.target.value;})}/></label>
    <div className="rule-start-block">{parseProgram(sequence.program).program?.version===3?<p>Use a Forever block to repeat while keeping program state.</p>:<label className="rule-checkbox"><input type="checkbox" checked={sequence.repeat} onChange={e=>change(value=>{value.repeat=e.target.checked;})}/>Repeat until stopped</label>}<label>If triggered again<select value={sequence.interruption} onChange={e=>change(value=>{value.interruption=Number(e.target.value);})}>{rulePolicies.map((name,index)=><option key={name} value={index}>{name}</option>)}</select></label></div>
    {steps!==null&&<button disabled={programEditing} onClick={()=>setAdvanced(value=>!value)}>{advanced?'Simple action editor':'Functions & code'}</button>}
    {steps===null||advanced?<ProgramEditor key={sequence.id+':'+draft!.revision+':'+editorReset} source={sequence.program} targets={state.objects} eventsSupported={state.capabilities?.includes('eventPrograms.v1')} eventFieldsSupported={state.capabilities?.includes('eventFields.v1')} eventSubscriptionsSupported={state.capabilities?.includes('eventSubscriptions.v1')} resultsSupported={state.capabilities?.includes('actionResults.v1')} onSignal={!dirty&&!stale&&state.capabilities?.includes('eventPrograms.v1')?(eventName,value)=>void send({action:'signal',revision:rules.revision,eventName,value},state):undefined} onChange={source=>change(value=>{value.program=source;if(parseProgram(source).program?.version===3)value.repeat=false;})} run={rules.running.find(run=>run.sequenceId===sequence.id)} onEditingChange={editProgram} disabled={blocked}/>:<><ol className="rule-block-list">{steps.map((step,index)=>{const active=rules.running.find(run=>run.sequenceId===sequence.id&&run.nodeId===step.id);return <li key={step.id||`draft-${index}`} className={`rule-action-block${active?' rule-action-active':''}`}>
     <div className="rule-step-heading"><strong>{index+1}. {ruleActions[step.action]}</strong>{active&&<span>{active.preparing?'Loading':'Running'}</span>}</div>
     <label>Action<select aria-label={`Step ${index+1} action`} value={step.action} onChange={e=>updateStep(index,value=>{value.action=Number(e.target.value);value.seconds=[0,3,6,7,8,10,11,12,13,14,15,16,17].includes(value.action)?0:2.5;if([1,4,5,9].includes(value.action))value.targetId='maestro';if([3,10,11,12,13,14,15,16,17].includes(value.action))value.loop=false;if([10,11].includes(value.action)){value.targetId=state.objects.find(o=>!['maestro','book'].includes(o.id))?.id??'';value.impulse={x:0,y:.6,z:0};}if([16,17].includes(value.action))value.targetId=state.objects.find(o=>!['maestro','book'].includes(o.id))?.id??'';if(value.action===14)value.editPosition={...state.objects.find(o=>o.id===value.targetId)?.position??{x:0,y:0,z:0}};if(value.action===15)value.editScale=state.objects.find(o=>o.id===value.targetId)?.scale??1;if(value.action===16)value.editColor={red:1,green:1,blue:1};if(value.action===13)Object.assign(value,newRuleStep(13),{id:value.id});if(value.action===12)value.creation={shape:'ball',name:'Ball',x:.3,y:1.3,z:.65,scale:1,red:.2,green:.6,blue:.9};if(value.action===9&&value.gesture===5)value.gesture=0;if(![0,1,6,7].includes(value.action))value.propId=null;})}>{ruleActions.map((name,action)=><option key={name} value={action} disabled={action>17||action>=14&&!state.capabilities?.includes('objectEdits.v1')||action===13&&!state.capabilities?.includes('recipeCreation.v1')||[10,11,16,17].includes(action)&&!state.objects.some(o=>!["maestro","book"].includes(o.id))||(action===6||action===7)&&step.action!==action}>{name}</option>)}</select></label>
     {![2,12,13].includes(step.action)&&<label>Target<select aria-label={`Step ${index+1} target`} value={step.targetId} onChange={e=>updateStep(index,value=>{value.targetId=e.target.value;if(value.targetId!=='maestro')value.propId=null;})}>{state.objects.filter(o=>[10,11,16,17].includes(step.action)?!['maestro','book'].includes(o.id):![1,4,5,9].includes(step.action)||o.id==='maestro').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
     {[1,9].includes(step.action)&&<label>Gesture<select aria-label={`Step ${index+1} gesture`} value={step.gesture} onChange={e=>updateStep(index,value=>{value.gesture=Number(e.target.value);})}>{ruleGestures.map((name,gesture)=><option key={name} value={gesture} disabled={step.action===9&&gesture===5}>{name}</option>)}</select></label>}
     {![10,11,12,13,14,15,16,17].includes(step.action)&&<label>Seconds<input aria-label={`Step ${index+1} seconds`} type="number" min={[0,3,6,7,8].includes(step.action)?0:.1} max={30} step={.1} disabled={step.action===3} value={step.seconds} onChange={e=>updateStep(index,value=>{value.seconds=Number(e.target.value);})}/></label>}
     {step.action===14&&<fieldset><legend>Position in room metres</legend>{(['x','y','z'] as const).map(axis=><label key={axis}>{axis.toUpperCase()}<input aria-label={'Step '+(index+1)+' position '+axis} type="number" min={-25} max={25} step={.1} value={step.editPosition?.[axis]??0} onChange={e=>updateStep(index,value=>{value.editPosition={...value.editPosition??{x:0,y:0,z:0},[axis]:Number(e.target.value)};})}/></label>)}</fieldset>}
     {step.action===15&&<label>Scale<input aria-label={'Step '+(index+1)+' object scale'} type="number" min={step.targetId==='book'?.65:step.targetId==='maestro'?.3:.1} max={step.targetId==='book'?1.8:step.targetId==='maestro'?1.5:4} step={.1} value={step.editScale??1} onChange={e=>updateStep(index,value=>{value.editScale=Number(e.target.value);})}/></label>}
     {step.action===16&&<fieldset><legend>Object tint</legend>{(['red','green','blue'] as const).map(channel=><label key={channel}>{channel}<input aria-label={'Step '+(index+1)+' tint '+channel} type="number" min={0} max={1} step={.1} value={step.editColor?.[channel]??1} onChange={e=>updateStep(index,value=>{value.editColor={...value.editColor??{red:1,green:1,blue:1},[channel]:Number(e.target.value)};})}/></label>)}</fieldset>}
     {step.action>=14&&<small>{step.action===17?'Deletes this object. Room Undo can restore it.':step.action===16?'Changes tint once and keeps its motion. Room Undo is available.':'Changes placement once and resets velocity. Room Undo is available.'}</small>}
     {step.action===13&&<fieldset><legend>Create recipe object</legend><label>Name<input aria-label={'Step '+(index+1)+' recipe name'} maxLength={80} value={step.creation?.name??''} onChange={e=>updateStep(index,value=>{if(value.creation)value.creation.name=e.target.value;})}/></label>{(['x','y','z','scale'] as const).map(key=><label key={key}>{key}<input aria-label={'Step '+(index+1)+' recipe '+key} type="number" min={key==='scale'?.1:-25} max={key==='scale'?4:25} step={.1} value={step.creation?.[key]??0} onChange={e=>updateStep(index,value=>{if(value.creation)value.creation[key]=Number(e.target.value);})}/></label>)}<p>{step.creationRecipe?.parts.length??0} parts · {step.creationRecipe?.tracks.length??0} animation tracks</p><button onClick={()=>setAdvanced(true)}>Edit recipe in function blocks</button><details><summary>Saved construction recipe</summary><pre>{JSON.stringify(step.creationRecipe,null,2)}</pre></details></fieldset>}
     {step.action===12&&<fieldset><legend>Create shape</legend><label>Shape<select aria-label={'Step '+(index+1)+' shape'} value={step.creation?.shape??'ball'} onChange={e=>updateStep(index,value=>{if(value.creation)value.creation.shape=e.target.value;})}>{['ball','block','cylinder'].map(shape=><option key={shape}>{shape}</option>)}</select></label><label>Name<input value={step.creation?.name??''} maxLength={80} onChange={e=>updateStep(index,value=>{if(value.creation)value.creation.name=e.target.value;})}/></label>{(['x','y','z','scale','red','green','blue'] as const).map(key=><label key={key}>{key}<input aria-label={'Step '+(index+1)+' creation '+key} type="number" step={.1} min={['x','y','z'].includes(key)?-25:key==='scale'?.1:0} max={['x','y','z'].includes(key)?25:key==='scale'?4:1} value={step.creation?.[key]??0} onChange={e=>updateStep(index,value=>{if(value.creation)value.creation[key]=Number(e.target.value);})}/></label>)}</fieldset>}
     {step.action===10&&<fieldset><legend>Impulse in room axes (N·s)</legend>{(['x','y','z'] as const).map(axis=><label key={axis}>{axis.toUpperCase()}<input aria-label={'Step '+(index+1)+' impulse '+axis} type="number" min={-20} max={20} step={.1} value={step.impulse?.[axis]??0} onChange={e=>updateStep(index,value=>{value.impulse={...value.impulse??{x:0,y:0,z:0},[axis]:Number(e.target.value)};})}/></label>)}</fieldset>}
     {[10,11].includes(step.action)&&<small>Applies once. Gravity and collisions continue after this step.</small>}
     {[0,6,7,8].includes(step.action)&&<><small>0 uses the full animation duration.</small><label className="rule-checkbox"><input type="checkbox" checked={step.loop} onChange={e=>updateStep(index,value=>{value.loop=e.target.checked;})}/>Loop during this step</label></>}
     {(step.action===6||step.action===7)&&<p className="room-workspace-intro">The saved imported motion is retained. New motion assignments use the existing motion tools.</p>}
     {step.propId&&<p>Carrying {state.objects.find(o=>o.id===step.propId)?.name??'a missing prop'}; saved hand and release settings are retained.</p>}
     <div className="room-workspace-actions"><button aria-label={`Move step ${index+1} up`} disabled={index===0} onClick={()=>changeSteps(steps=>{[steps[index-1],steps[index]]=[steps[index],steps[index-1]];})}>↑</button><button aria-label={`Move step ${index+1} down`} disabled={index===steps.length-1} onClick={()=>changeSteps(steps=>{[steps[index+1],steps[index]]=[steps[index],steps[index+1]];})}>↓</button><button aria-label={`Remove step ${index+1}`} disabled={steps.length<=1} onClick={()=>changeSteps(steps=>{steps.splice(index,1);})}>Remove</button></div>
    </li>;})}</ol><button disabled={steps.length>=16} onClick={()=>changeSteps(steps=>{steps.push(newRuleStep());})}>+ Wait / action block</button></>}</fieldset>
    <div className="room-workspace-actions"><button disabled={blocked||dirty||programEditing} onClick={()=>void edit([{kind:'delete',target:sequence.id}])}>Delete behaviour · Undo available</button></div>
   </>}
  </section>
 </div>;
}
