// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
import { CHAT_IMAGE_BYTES, CHAT_IMAGE_CHUNK, validChatImageRequest, type ChatImageOffer } from '../../../shared/chatImages';
import type { ChatMessage } from '../../core/types';
import { bytesToHex } from '@noble/hashes/utils.js';
type Source = { messageId: string; name: string; origin: string; dataUrl: string };
/** Current-conversation images already owned by the original app. No URL fetch,
 * provider call, camera capture, or model-generated byte string is accepted. */
export function chatImageSources(messages: readonly ChatMessage[], bookmark?: string | null): Source[] {
  const index = bookmark ? messages.findIndex(m => m.id === bookmark && !m.thinking) : -1;
  const visible = index >= 0 ? messages.slice(index + 1) : messages;
  return visible.filter(m => !m.isGeneratingImage)
    .slice().reverse().flatMap(m => {
      const dataUrl = m.imageUrl?.startsWith('data:image/') ? m.imageUrl : m.storageOptimizedImageUrl;
      return dataUrl && /^data:image\/(png|jpeg);base64,/.test(dataUrl)
        ? [{messageId: m.id.slice(0, 128), name: (m.attachmentName || (m.imageOrigin === 'generated' ? 'Generated chat image' : 'Chat image')).slice(0, 80), origin: m.imageOrigin || 'unknown', dataUrl}] : [];
    }).slice(0, 8);
}
export class ChatImageSource {
  private scope = '';
  private sources: Source[] = [];
  private setId = crypto.randomUUID().replace(/-/g, '');
  private offers: ChatImageOffer[] = [];
  private encoded = new Map<string, string>();
  private pending: Promise<void> = Promise.resolve();
  update(scope: string, sources: Source[]): Promise<void> {
    // Compare references/strings without serializing another copy of all pixels.
    const selected = sources.slice(0, 8);
    if (scope === this.scope && selected.length === this.sources.length && selected.every((v, i) => {
      const old = this.sources[i]; return v.messageId === old.messageId && v.name === old.name && v.origin === old.origin && v.dataUrl === old.dataUrl;
    })) return this.pending;
    this.scope = scope; this.sources = selected; this.setId = crypto.randomUUID().replace(/-/g, '');
    this.offers = []; this.encoded.clear();
    const generation = this.setId;
    this.pending = this.prepare(selected, generation); return this.pending;
  }
  private async prepare(selected: Source[], generation: string) {
    const offers: ChatImageOffer[] = [], encoded = new Map<string, string>();
    for (const source of selected) {
      if (source.dataUrl.length > Math.ceil(CHAT_IMAGE_BYTES / 3) * 4 + 32) continue;
      const match = /^data:image\/(png|jpeg);base64,([A-Za-z0-9+/]+={0,2})$/.exec(source.dataUrl);
      if (!match || match[2].length > Math.ceil(CHAT_IMAGE_BYTES / 3) * 4 || match[2].length % 4 !== 0) continue;
      try {
        const binary = atob(match[2]);
        if (binary.length < 24 || binary.length > CHAT_IMAGE_BYTES) continue;
        const bytes = Uint8Array.from(binary, c => c.charCodeAt(0));
        const imageHash = bytesToHex(new Uint8Array(await crypto.subtle.digest('SHA-256', bytes)));
        if (this.setId !== generation) return;
        if (encoded.has(imageHash)) continue;
        const name = source.name.replace(/[\x00-\x1f<>]/g, '').slice(0, 80) || 'Chat image';
        const messageId = source.messageId.slice(0, 128), origin = source.origin.replace(/[^a-z-]/g, '').slice(0, 32) || 'unknown';
        offers.push({imageHash, name, messageId, origin, bytes: bytes.length}); encoded.set(imageHash, match[2]);
      } catch { /* Unreadable local content is not offered as a native asset. */ }
    }
    if (this.setId === generation) { this.offers = offers; this.encoded = encoded; this.setId = crypto.randomUUID().replace(/-/g, ''); }
  }
  snapshot(request: unknown) {
    let chunk: {requestId: string; imageHash: string; offset: number; data: string} | undefined;
    if (validChatImageRequest(request) && request.offerSet === this.setId) {
      const offer = this.offers.find(v => v.imageHash === request.imageHash);
      const data = this.encoded.get(request.imageHash);
      if (offer && data && offer.bytes === request.bytes) {
        // A 16 KiB offset is not a base64 group boundary; decode only the
        // overlapping groups and encode the exact requested byte interval.
        const first = Math.floor(request.offset / 3) * 4, prefix = request.offset % 3;
        const size = Math.min(CHAT_IMAGE_CHUNK, request.bytes - request.offset);
        const binary = atob(data.slice(first, first + Math.ceil((prefix + size) / 3) * 4));
        chunk = {requestId: request.requestId, imageHash: request.imageHash, offset: request.offset, data: btoa(binary.slice(prefix, prefix + size))};
      }
    }
    return {offerSet: this.setId, offers: this.offers, ...(chunk ? {chunk} : {})};
  }
}
