// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
using System;using System.IO;using System.Linq;using Maestro.Quest.Creation;using Maestro.Quest.Interaction;using Maestro.Quest.Programs;using Newtonsoft.Json.Linq;using NUnit.Framework;using UnityEngine;
namespace Maestro.Quest.Tests {public sealed class HeightFieldTests {
 static RoomDocument Room()=>new(){version=RoomDocument.CurrentVersion,objects=new[]{new RoomObjectData{id="book",kind=RoomObjectKind.Book},new RoomObjectData{id="maestro",kind=RoomObjectKind.Maestro},new RoomObjectData{id=new string('a',32),kind=RoomObjectKind.Block,heightFields=new[]{new RoomHeightField()}}}};
 [Test] public void FieldsAreBoundedFixedComponentsAndExactGridCopies(){
  var room=Room();Assert.That(room.Validate(out var error),Is.True,error);var copy=room.Copy();copy.objects[2].heightFields[0].heights[0]=.1f;Assert.That(room.objects[2].heightFields[0].heights[0],Is.EqualTo(.08f));
  foreach(int cells in new[]{4,8,16}){var f=new RoomHeightField{cells=cells,heights=new float[(cells+1)*(cells+1)]};Assert.That(f.Validate(out error),Is.True,error);f.heights[0]=float.NaN;Assert.That(f.Validate(out _),Is.False);}
  var bad=room.Copy();bad.objects[2].physics=ItemPhysics.Solid;Assert.That(bad.Validate(out _),Is.False);bad=room.Copy();bad.objects[0].heightFields=new[]{new RoomHeightField()};Assert.That(bad.Validate(out _),Is.False);
  foreach(var f in new[]{new RoomHeightField{cells=5},new RoomHeightField{heights=new float[290]},new RoomHeightField{width=float.PositiveInfinity},new RoomHeightField{maxHeight=.01f},new RoomHeightField{material="Snow\n"},new RoomHeightField{frame=new ConnectionFrame{rotation=new Quaternion()}},new RoomHeightField{color=Color.clear}})Assert.That(f.Validate(out _),Is.False);
  room.objects=room.objects.Take(2).Concat(Enumerable.Range(0,4).Select(i=>new RoomObjectData{id=i.ToString("x32"),kind=RoomObjectKind.Block,heightFields=new[]{new RoomHeightField()}})).ToArray();Assert.That(room.Validate(out error),Is.True,error);room.objects=room.objects.Append(new RoomObjectData{id=new string('f',32),kind=RoomObjectKind.Block,heightFields=new[]{new RoomHeightField()}}).ToArray();Assert.That(room.Validate(out _),Is.False);
 }
 [Test] public void SweptBrushIsSamplingIndependentBoundedAndReportsNoChange(){
  var a=new RoomHeightField();var b=a.Copy();var path=new[]{new Vector2(-.3f,0),new Vector2(.3f,0)};Assert.That(a.Sculpt("lower",path,.08f,.03f,out var count,out var error),Is.True,error);Assert.That(count,Is.GreaterThan(10));Assert.That(b.Sculpt("lower",new[]{path[0],path[0],Vector2.zero,path[1],path[0]},.08f,.03f,out _,out error),Is.True,error);Assert.That(b.heights,Is.EqualTo(a.heights));Assert.That(a.heights[8*17+8],Is.EqualTo(.05f).Within(.000001));Assert.That(a.heights[0],Is.EqualTo(.08f));Assert.That(a.VolumeLitres,Is.LessThan(80));
  Assert.That(a.Sculpt("raise",new[]{Vector2.zero},2,.5f,out _,out error),Is.True,error);Assert.That(a.heights.All(h=>h>=0&&h<=.25f),Is.True);Assert.That(a.Sculpt("level",new[]{Vector2.zero},2,0,out _,out error),Is.True,error);Assert.That(a.heights[8*17+8],Is.Zero);
  string before=JsonUtility.ToJson(a);Assert.That(a.Sculpt("lower",new[]{new Vector2(2,0)},.1f,.1f,out _,out _),Is.False);Assert.That(JsonUtility.ToJson(a),Is.EqualTo(before));Assert.That(new RoomHeightField().Sculpt("raise",new[]{new Vector2(.03125f,.03125f)},.005f,.1f,out _,out _),Is.False);
 }
 [Test] public void HeightSurfaceFormatsPreserveSourceAndFutureFieldsAreNotReplacedByBackup(){
  string dir=Path.Combine(Path.GetTempPath(),"MaestroField-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);try{var room=Room();room.version=14;Assert.That(room.Validate(out _),Is.False);room.objects[2].heightFields=Array.Empty<RoomHeightField>();Assert.That(room.Validate(out var error),Is.True,error);room=Room();Assert.That(new RoomStorage(dir).Save(room,out error),Is.True,error);var restored=new RoomStorage(dir).Load(out _);Assert.That(restored.objects[2].heightFields[0].heights,Is.EqualTo(room.objects[2].heightFields[0].heights));room.objects[2].heightFields[0].version=2;string wire=JsonUtility.ToJson(room);File.WriteAllText(Path.Combine(dir,RoomStorage.FileName),wire);var storage=new RoomStorage(dir);Assert.That(storage.Load(out _),Is.Null);Assert.That(storage.ReadOnly,Is.True);Assert.That(File.ReadAllText(Path.Combine(dir,RoomStorage.FileName)),Is.EqualTo(wire));}finally{Directory.Delete(dir,true);}
 }
 [Test] public void CapturedFieldsAreEditablePortableIndependentAndRequireFixedPhysics(){
  var prototype=CreationPrototype.Capture(Room().objects[2]);var encoded=CreationPrototypeSchema.Encode(prototype);Assert.That(CapabilityArguments.Validate(encoded,CreationPrototypeSchema.Schema(),out var error),Is.True,error);var restored=CreationPrototype.Read(encoded);Assert.That(restored.Validate(out error),Is.True,error);var instance=restored.Instantiate("Snow",Vector3.one,Quaternion.identity,1);instance.heightFields[0].heights[0]=0;Assert.That(restored.heightFields[0].heights[0],Is.EqualTo(.08f));encoded["physics"]["mode"]="solid";Assert.That(CapabilityArguments.Validate(encoded,CreationPrototypeSchema.Schema(),out _),Is.False);
 }
 [Test] public void SharedSurfaceContractsCompileWithExactOwnershipAndFeatureGates(){
  foreach(var row in JArray.Parse(File.ReadAllText(Path.Combine(Application.dataPath,"Maestro/Tests/Fixtures/height-field-contract.json")))){var args=(JObject)row["arguments"];bool valid=(bool)row["valid"];string id=(string)row["capability"];Assert.That(BehaviourCatalog.TryCall(id,1,args,out var call,out var error),Is.EqualTo(valid),(string)row["name"]+": "+error);if(!valid)continue;Assert.That(call.Resources,Is.EquivalentTo(new[]{(string)args["target"]}));Assert.That(BehaviourProgram.TryParse(BehaviourProgram.FromInvocation(new JObject{["id"]=id,["version"]=1,["arguments"]=args}),out _,out error),Is.True,error);}
 }
}}
