// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
export const catalogRequestSchema={type:'object',properties:{
 operation:{type:'string',enum:['search','inspect','check']},category:{type:'string',enum:['actions','events','facts']},query:{type:'string',maxLength:80},offset:{type:'integer',minimum:0,maximum:1000000},
 capability:{type:'string'},version:{type:'integer',minimum:1,maximum:1000000},
 call:{type:'object',properties:{id:{type:'string'},version:{type:'integer',minimum:1,maximum:1000000},arguments:{type:'object',additionalProperties:true}},required:['id','version','arguments'],additionalProperties:false}
},required:['operation'],additionalProperties:false};
export const CATALOG_GUIDE=`When catalog.v1 is advertised, send a standalone {action:"catalog",catalog:{operation:"search",query:"avatar",offset:0}} to discover action IDs and versions, then {operation:"inspect",capability:exact ID,version:returned version} to retrieve its typed definition. Pages contain up to six entries; search by ID, label or prerequisite text, then offset+6 for more. Only inspect relevant entries rather than expanding every definition into context.
When catalogVocabulary.v1 is advertised, search and inspect also accept category:"actions"|"events"|"facts". Omission means actions for older clients. For example {operation:"search",category:"events",query:"contact",offset:0}, then {operation:"inspect",category:"events",capability:returned ID,version:returned version}. Keep the same category when paging or inspecting. Search returns at most six ID/version/label entries and no schemas; inspect only relevant results. Event definitions describe valueType, source filtering via objectEvent, required features and optional typed fields. Parameterized event definitions additionally provide input and example for a private native watch; awaitEvent uses the inspected version, arguments and bindings when eventSubscriptions.v1 is present. Inspection does not subscribe, emit or start a program. Use the ID in awaitEvent; saving remains separate from starting. Fact definitions describe their scalar type and meaning; fact inspection also returns available and value using the same native reader as program expressions. value is null when unavailable, and false/zero/empty text remain legitimate available values. Readings refresh in scene.catalog while that fact stays selected, but are only current observations, not future guarantees or subscriptions. Use the exact discovered ID in {fact:id} expressions. Never enumerate every definition into the prompt. If this feature is absent, don't invent newly discovered event/fact support or send scoped queries.
To check concrete arguments use {operation:"check",call:{id,version,arguments:{...}}}. scene.catalog returns valid, available, occupied, resources and status, refreshed against current native state. The check operation is action-only and must omit category. All catalog operations are read-only: they never select, save, reserve, interrupt or start anything. Unknown definitions and invalid/unavailable calls have explicit status. A successful query receipt proves only the query, not availability or action completion; inspect those fields.
Definitions use JSON Schema object/array/string/number/integer/boolean fields and discriminated oneOf variants (x-discriminators lists literal selector paths), optional nullable, and native-authored examples. Arrays declare items, minItems and maxItems. Variant titles label choices, examples provide complete draft values, and x-features lists required native features. Required fields are explicit; extra fields are forbidden. x-resource:"object" marks object references that programs must reserve; x-requires constrains sibling arguments; format boundedOffset requires squared length <=1 and unitQuaternion requires squared length within .01 of 1. The roomRecipe format also checks ordered unique parents, total geometric reach, existing unique track targets and ordered key times spanning the duration. Arrays remain literal. Bind scalar object fields by their exact dotted schema path; x-static selector fields cannot be bound. Variant x-channels and x-requirements apply to that choice, while the definition lists possible channels. Calls remain bounded to 24,000 argument characters, 4,096 value nodes and depth 12, within the unchanged outer command/program size limits.
Ownership channels describe compatible simultaneous actions; wholeTarget conflicts with every channel on that object. One-off calls and version-3 program invocations reserve the declared channels; version-2 saved programs still reserve whole objects for their entire run. Props remain whole objects. An upper-body gesture can coexist with Follow (locomotion plus gaze) or Look (gaze). Full-body gestures, recordings and imported motions remain exclusive; do not claim arbitrary clip layering. Use native check for current readiness and conflicts.
Use the returned stable ID/version and named arguments in a program invoke block. If execution.v1 is available, the same call can run as a one-off action; otherwise execution requires saving/playing a behaviour. For object.create with kind:"recipe", inspect the selected variant's native example, then edit its recipe data. Parts and tracks remain user-editable. Set recipe.playing=false when a later animation.play block with source:{kind:"recipe"},channel:"wholeTarget" controls playback; playing=true explicitly requests saved automatic playback. Creation returns objectId and uses fixed physics. A check is only a snapshot and will be revalidated during execution. Search/inspect/check may be used to clarify an unconfirmed earlier action without replaying it. `;
