// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
import {catalogRequestSchema} from './catalog';
export const executionRequestSchema={type:'object',properties:{
 operation:{type:'string',enum:['start','inspect','cancel','recover']},call:catalogRequestSchema.properties.call,
 runId:{type:'string',pattern:'^[a-f0-9]{32}$'},recoveryId:{type:'string',pattern:'^[a-f0-9]{32}$'}
},required:['operation'],additionalProperties:false};
export const EXECUTION_GUIDE=`When execution.v1 is advertised, a requested one-off action can run without saving a behaviour: standalone {action:"execution",execution:{operation:"start",call:{id:inspected capability ID,version:inspected version,arguments:{...}}}}. Use exact current object/prop IDs. The bridge sends their observed revisions; stale or missing targets are rejected before execution. A preflight check never reserves readiness. Conflicting animation channels, whole-object owners or full capacity reject the call without replacing, queueing or interrupting another action. Never retry an unconfirmed start or create a saved behaviour just to bypass a busy rejection.
The successful acknowledgement selects the actual run in scene.execution.selected; retain its id. Its phase is preparing/running/completed/cancelled/failed/interrupted. "Preparing" and "running" do not mean completion. scene.execution.running contains current one-off runs; outcomes retains recent terminal runs. These share the native scheduler with saved programs and all Stop/grab/pause rules, but never edit saved behaviours. Runtime motion calls do not create Undo entries. Ordinary creations save with one room-object Undo; in an explicit temporary room, creation/edit results are live and unsaved until a snapshot succeeds. When executionReceipts.v1 is advertised, the app attaches the observed one-use scene.execution.nextRunId before saving the task journal and dispatching. Native saves the accepted call before effects and retains up to 16 terminal receipts across restart. A restart turns unfinished calls into interrupted: some effects may have happened, and they were not replayed. This is not completion or rollback. scene.execution.storageError disables new starts if receipt storage fails. Inspect the exact ID from the journal after a lost acknowledgement; never manufacture another start to recover. Without executionReceipts.v1, receipts remain session-only.
When workspaceMaintenance.v1 is advertised, catalog actions with domain:"workspace" use scene.execution.workspace (its own selected, running, outcomes, nextRunId, storageError and recovery). These persistent maintenance actions share the same handlers and receipt rules, and remain available during a room review hold or an unavailable room. App pause still interrupts active actions; no automatic replay occurs. The app chooses the native-issued ID for the catalog domain before journaling. Room-history errors do not block healthy workspace maintenance. Inspect/cancel/recover still use the exact observed ID. A room replacement rotates the room session; inspect retained workspace outcomes again rather than repeating an unconfirmed start.
When actionRecovery.v1 is advertised and the user explicitly requests recovery from the displayed storage error, use {action:"execution",execution:{operation:"recover",recoveryId:scene.execution.recovery.id}}. Recovery is a mutation: it stops active one-off actions, archives their old evidence and establishes fresh history. It does not affect saved programs or undo room objects. A success only means storage was recovered; it does not prove unknown actions completed and never authorizes replaying them. A failed recovery keeps new starts blocked; inspect the actual status. The observed recovery ID prevents stale or duplicate recovery from resetting newer actions. Do not recover automatically just to bypass an error or an unconfirmed prior task.\nObject edit capabilities (object.position.set, object.rotation.set, object.scale.set, object.color.set, object.delete) save before reporting completion outside temporary mode, with one room Undo edit. Inside temporary mode they update the live fork and its local Undo; only a successful room.session keep makes a captured snapshot durable. Painting preserves current motion; placement and resizing reset velocity. Delete cannot remove the included book or Maestro. A completed edit is historical: cancellation/replay does not undo it. Use the current observed object IDs and revisions; later actions on a deleted target fail. Completed actions with a catalog output schema include output in their selected record and receipt. For object.create, output.objectId is the exact created ID; inspect the current room before later edits because the object can be moved or removed after that historical completion. Never recreate it to recover a lost acknowledgement. Use {action:"execution",execution:{operation:"inspect",runId:exact run ID}} for the same action's current status and exact call. Inspect is read-only and uses the query allowance. Use {operation:"cancel",runId:exact run ID} to cancel only that one-off action; an already retained terminal run returns its existing outcome unchanged. Unknown/evicted IDs have unknown outcomes; do not infer completion or replay them. Cancel is an action, not a query. Saving/playing a program remains the route for multi-step chains, reusable behaviours and triggers. Prefer one-off execution for a single requested action; do not add persistence or buttons unless requested. `;
