// Copyright 2025 Roni Tervo
// SPDX-License-Identifier: Apache-2.0

export interface ColorVariable {
  cssVar: string;
  friendlyName: string;
  /** Short description of what this color affects, for non-technical users. */
  description?: string;
}

export interface ColorGroup {
  groupName: string;
  /** Short explanation of this group shown below the group title. */
  groupDescription?: string;
  colors: ColorVariable[];
  /** If true, group starts collapsed in the panel. */
  collapsedByDefault?: boolean;
}

export const COLOR_GROUPS: ColorGroup[] = [
  {
    groupName: 'Page Canvas',
    groupDescription: 'The full-screen paper and main writing color',
    colors: [
      { cssVar: 'page-bg', friendlyName: 'Page Background', description: 'Main app background behind everything' },
      { cssVar: 'page-text', friendlyName: 'Page Text', description: 'Default text color used across the app' },
      { cssVar: 'paper-surface', friendlyName: 'Paper Surface', description: 'Notebook paper areas in the main content' },
      { cssVar: 'paper-stripe', friendlyName: 'Paper Stripe', description: 'Darker paper stripes and paper depth' },
      { cssVar: 'deep-ink', friendlyName: 'Deep Ink', description: 'Strong deep-ink text and marks' },
    ],
  },
  {
    groupName: 'Chat Message Bubbles',
    groupDescription: 'Backgrounds and text for each message type',
    colors: [
      { cssVar: 'user-msg-bg', friendlyName: 'User Message Background', description: 'Background of your sent message bubbles' },
      { cssVar: 'user-msg-text', friendlyName: 'User Message Text', description: 'Text and icons inside your messages' },
      { cssVar: 'ai-msg-bg', friendlyName: 'AI Message Background', description: 'Background of assistant reply bubbles' },
      { cssVar: 'ai-msg-text', friendlyName: 'AI Message Text', description: 'Text inside assistant replies' },
      { cssVar: 'status-msg-bg', friendlyName: 'Status Message Background', description: 'Background of system/status messages' },
      { cssVar: 'status-msg-text', friendlyName: 'Status Message Text', description: 'Text inside system/status messages' },
      { cssVar: 'error-msg-bg', friendlyName: 'Error Message Background', description: 'Background of error message bubbles' },
      { cssVar: 'error-msg-text', friendlyName: 'Error Message Text', description: 'Text color for error messages' },
      { cssVar: 'thinking-bubble-bg', friendlyName: 'Thinking Indicator Background', description: 'Background of the thinking... bubble' },
      { cssVar: 'thinking-bubble-text', friendlyName: 'Thinking Indicator Text', description: 'Text in the thinking... bubble' },
    ],
  },
  {
    groupName: 'Message Sub-elements',
    groupDescription: 'File attachments, image placeholders, and error indicators within messages',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'ai-msg-placeholder', friendlyName: 'AI Image Placeholder', description: 'Placeholder background while AI image loads (focused view)' },
      { cssVar: 'ai-file-bg', friendlyName: 'AI File Attachment', description: 'Background of file attachments in assistant messages' },
      { cssVar: 'ai-file-text', friendlyName: 'AI File Text', description: 'Text and icon color in assistant file attachments' },
      { cssVar: 'img-error-text', friendlyName: 'Image Error Text', description: 'Error text color for image generation failures' },
    ],
  },
  {
    groupName: 'Chat Input Area',
    groupDescription: 'Message composer in chat and suggestion modes',
    colors: [
      { cssVar: 'chat-input-bg', friendlyName: 'Chat Input Background', description: 'Input field background in chat mode' },
      { cssVar: 'chat-input-text', friendlyName: 'Chat Input Text', description: 'Text color in chat mode input' },
      { cssVar: 'chat-input-icon', friendlyName: 'Chat Input Icons', description: 'Icon button color inside chat input' },
      { cssVar: 'chat-input-icon-hover-bg', friendlyName: 'Chat Icon Hover', description: 'Hover background for chat-mode icon buttons' },
      { cssVar: 'sugg-input-bg', friendlyName: 'Suggestion Input Background', description: 'Input field background in suggestion mode' },
      { cssVar: 'sugg-input-text', friendlyName: 'Suggestion Input Text', description: 'Text color in suggestion mode input' },
      { cssVar: 'sugg-input-icon', friendlyName: 'Suggestion Input Icons', description: 'Icon button color in suggestion mode' },
      { cssVar: 'send-btn-bg', friendlyName: 'Send Button Background', description: 'Background of the send message button' },
      { cssVar: 'send-btn-text', friendlyName: 'Send Button Text', description: 'Text/icon color on the send button' },
      { cssVar: 'send-sugg-btn-bg', friendlyName: 'Suggest Send Background', description: 'Background of the send/create button in suggestion mode' },
      { cssVar: 'send-sugg-btn-text', friendlyName: 'Suggest Send Text', description: 'Text/icon color of the suggestion-mode send/create button' },
      { cssVar: 'input-focus-ring', friendlyName: 'Input Focus Ring', description: 'Ring shown when the input field is focused' },
      { cssVar: 'input-error-bg', friendlyName: 'Input Error Background', description: 'Background for error messages in the input area' },
      { cssVar: 'input-error-text', friendlyName: 'Input Error Text', description: 'Text color for input area error messages' },
      { cssVar: 'snapshot-error-bg', friendlyName: 'Snapshot Error Background', description: 'Background tint for snapshot-related input errors' },
      { cssVar: 'chat-outer-bg', friendlyName: 'Chat Mode Container', description: 'Outer container background in chat mode' },
      { cssVar: 'chat-outer-text', friendlyName: 'Chat Mode Container Text', description: 'Text in the outer chat mode container' },
      { cssVar: 'sugg-outer-bg', friendlyName: 'Suggestion Mode Container', description: 'Outer container background in suggestion mode' },
    ],
  },
  {
    groupName: 'Chat Interface Chrome',
    groupDescription: 'History peek, navigation buttons, and suggestion controls',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'history-peek-bg', friendlyName: 'History Peek Background', description: 'Background of the message history peek zone' },
      { cssVar: 'history-peek-icon', friendlyName: 'History Peek Eye Icon', description: 'Eye icon color in the history peek zone' },
      { cssVar: 'history-btn-bg', friendlyName: 'History Button Background', description: 'Background of history navigation buttons' },
      { cssVar: 'history-btn-hover', friendlyName: 'History Button Hover', description: 'Hover color for history navigation buttons' },
      { cssVar: 'delete-msg-bg', friendlyName: 'Delete Message Button', description: 'Background of the delete message button' },
      { cssVar: 'delete-msg-text', friendlyName: 'Delete Message Text', description: 'Icon color on the delete message button' },
      { cssVar: 'save-sugg-bg', friendlyName: 'Save Suggestion Button', description: 'Background of the save suggestion button' },
      { cssVar: 'save-sugg-text', friendlyName: 'Save Suggestion Text', description: 'Text on the save suggestion button' },
      { cssVar: 'clear-sugg-bg', friendlyName: 'Clear Suggestion Button', description: 'Background of the clear suggestion button' },
      { cssVar: 'clear-sugg-text', friendlyName: 'Clear Suggestion Text', description: 'Text on the clear suggestion button' },
      { cssVar: 'web-results-bg', friendlyName: 'Web Results Container', description: 'Background of the web search results area' },
      { cssVar: 'web-results-link', friendlyName: 'Web Results Link', description: 'Link color in web search results' },
    ],
  },
  {
    groupName: 'Audio Player',
    groupDescription: 'Playback controls for recorded audio messages',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'audio-player-bg', friendlyName: 'Audio Player Background', description: 'Background of the audio playback bar' },
      { cssVar: 'audio-play-btn', friendlyName: 'Audio Play Button', description: 'Background of the play/pause button' },
      { cssVar: 'audio-play-text', friendlyName: 'Audio Play Icon', description: 'Icon color on the play/pause button' },
      { cssVar: 'audio-bar', friendlyName: 'Audio Progress Bar', description: 'Color of the audio progress bar' },
      { cssVar: 'audio-time-text', friendlyName: 'Audio Time Display', description: 'Time text in the audio player' },
    ],
  },
  {
    groupName: 'Bookmark Actions',
    groupDescription: 'Bookmark save panel and manage buttons',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'bookmark-bg', friendlyName: 'Bookmark Panel', description: 'Background of the bookmark save panel' },
      { cssVar: 'bookmark-text', friendlyName: 'Bookmark Text', description: 'Text and button color in bookmark panel' },
      { cssVar: 'bookmark-input-bg', friendlyName: 'Bookmark Input', description: 'Background of the bookmark name input field' },
      { cssVar: 'bookmark-input-text', friendlyName: 'Bookmark Input Text', description: 'Text color in the bookmark name field' },
      { cssVar: 'bookmark-divider', friendlyName: 'Bookmark Divider', description: 'Line divider between bookmark sections' },
    ],
  },
  {
    groupName: 'Suggestions List',
    groupDescription: 'Translation suggestion items',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'suggestion-bg', friendlyName: 'Suggestion Background', description: 'Background of individual suggestion lines' },
      { cssVar: 'suggestion-hover', friendlyName: 'Suggestion Hover', description: 'Hover background for suggestion lines' },
      { cssVar: 'suggestion-ring', friendlyName: 'Suggestion Focus Ring', description: 'Focus ring around selected suggestion' },
      { cssVar: 'suggestion-double-ring', friendlyName: 'Suggestion Confirm Ring', description: 'Focus ring for suggestions on double-click/confirm interaction' },
      { cssVar: 'suggestion-active-bg', friendlyName: 'Creating Suggestion', description: 'Background while a suggestion is being created' },
      { cssVar: 'suggestion-active-text', friendlyName: 'Creating Suggestion Text', description: 'Text while a suggestion is being created' },
    ],
  },
  {
    groupName: 'Session Controls',
    groupDescription: 'Profile editing, mode toggle, and sidebar controls',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'profile-label-text', friendlyName: 'Profile Label Text', description: 'Profile heading label color' },
      { cssVar: 'profile-input-accent', friendlyName: 'Profile Input Accent', description: 'Accent color for profile input fields and borders' },
      { cssVar: 'scroll-wheel-target-accent', friendlyName: 'Scroll Wheel Target Accent', description: 'Scroll focus ring for the non-native language wheel' },
      { cssVar: 'globe-native-accent', friendlyName: 'Globe Native Accent', description: 'Border and glow for the native-language marker on the globe' },
      { cssVar: 'globe-target-accent', friendlyName: 'Globe Target Accent', description: 'Border and glow for the target-language marker on the globe' },
      { cssVar: 'maestro-avatar-glow', friendlyName: 'Maestro Avatar Glow', description: 'Glow color around the maestro avatar when an image is present' },
      { cssVar: 'profile-btn-bg', friendlyName: 'Profile Button', description: 'Background of profile edit/label buttons' },
      { cssVar: 'profile-btn-text', friendlyName: 'Profile Button Text', description: 'Text on profile edit/label buttons' },
      { cssVar: 'profile-accept-bg', friendlyName: 'Profile Accept Button', description: 'Background of the profile accept/confirm button' },
      { cssVar: 'profile-accept-text', friendlyName: 'Profile Accept Text', description: 'Text on the profile accept button' },
      { cssVar: 'mode-toggle-bg', friendlyName: 'Mode Toggle Container', description: 'Background of the All/This mode toggle' },
      { cssVar: 'mode-toggle-text', friendlyName: 'Mode Toggle Text', description: 'Text on mode toggle buttons' },
      { cssVar: 'save-chat-text', friendlyName: 'Save Chat Label', description: 'Text color for the save chat action label' },
      { cssVar: 'ctrl-muted-text', friendlyName: 'Controls Muted Text', description: 'Dimmed text in session controls' },
    ],
  },
  {
    groupName: 'Header',
    groupDescription: 'Debug button and loading indicator in the app header',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'debug-btn-bg', friendlyName: 'Debug Button', description: 'Background of the debug logs button' },
      { cssVar: 'debug-btn-text', friendlyName: 'Debug Button Text', description: 'Text on the debug logs button' },
      { cssVar: 'debug-btn-muted', friendlyName: 'Debug Button Muted', description: 'Muted text state of the debug button' },
      { cssVar: 'loading-spinner', friendlyName: 'Loading Spinner', description: 'Color of the loading spinner indicator' },
    ],
  },
  {
    groupName: 'Live Session Idle Button',
    groupDescription: 'Live session button when no session is active',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'live-idle-btn-bg', friendlyName: 'Live Idle Button', description: 'Live session button background when idle' },
      { cssVar: 'live-idle-btn-text', friendlyName: 'Live Idle Button Text', description: 'Live session button text when idle' },
      { cssVar: 'live-idle-sugg-btn-bg', friendlyName: 'Live Suggest Idle Background', description: 'Live session button background when idle in suggestion mode' },
      { cssVar: 'live-idle-sugg-btn-text', friendlyName: 'Live Suggest Idle Text', description: 'Live session button text when idle in suggestion mode' },
      { cssVar: 'live-idle-spinner', friendlyName: 'Live Idle Spinner', description: 'Spinner color while connecting a live session' },
    ],
  },
  {
    groupName: 'Media Attachments',
    groupDescription: 'Media preview containers and camera toggle',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'media-chat-bg', friendlyName: 'Media Preview (Chat)', description: 'Media attachment preview background in chat mode' },
      { cssVar: 'media-sugg-bg', friendlyName: 'Media Preview (Suggest)', description: 'Media attachment preview background in suggestion mode' },
      { cssVar: 'media-empty-bg', friendlyName: 'No Attachment Icon BG', description: 'Placeholder icon background when no media attached' },
      { cssVar: 'media-empty-text', friendlyName: 'No Attachment Icon', description: 'Placeholder icon color when no media attached' },
      { cssVar: 'camera-toggle-text', friendlyName: 'Camera Toggle Active', description: 'Camera toggle button active text color' },
    ],
  },
  {
    groupName: 'API Key Gate',
    groupDescription: 'Setup screen for API key configuration',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'gate-bg', friendlyName: 'Setup Panel Background', description: 'Background of the API key setup panel' },
      { cssVar: 'gate-text', friendlyName: 'Setup Panel Text', description: 'Primary text in the setup panel' },
      { cssVar: 'gate-muted-text', friendlyName: 'Setup Panel Muted', description: 'Supporting text in the setup panel' },
      { cssVar: 'gate-input-bg', friendlyName: 'Setup Input Background', description: 'Input field background in setup panel' },
      { cssVar: 'gate-btn-bg', friendlyName: 'Setup Action Button', description: 'Action button background in setup panel' },
      { cssVar: 'gate-btn-text', friendlyName: 'Setup Action Text', description: 'Action button text in setup panel' },
      { cssVar: 'gate-error-text', friendlyName: 'Setup Error Text', description: 'Error message text in setup panel' },
      { cssVar: 'gate-accent', friendlyName: 'Setup Icon Accent', description: 'Accent color for icons in setup panel' },
    ],
  },
  {
    groupName: 'Theme Customizer',
    groupDescription: 'Theme customization panel colors',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'theme-panel-bg', friendlyName: 'Theme Panel Background', description: 'Background of the theme customizer panel' },
      { cssVar: 'theme-panel-text', friendlyName: 'Theme Panel Text', description: 'Text in the theme customizer panel' },
      { cssVar: 'theme-muted-text', friendlyName: 'Theme Muted Text', description: 'Helper text in the theme customizer' },
      { cssVar: 'theme-input-bg', friendlyName: 'Theme Input Background', description: 'Color input field background' },
      { cssVar: 'theme-input-border', friendlyName: 'Theme Input Border', description: 'Color input field border' },
      { cssVar: 'theme-preset-btn', friendlyName: 'Theme Preset Button', description: 'Preset theme selector button background' },
    ],
  },
  {
    groupName: 'CTA Buttons',
    groupDescription: 'Call-to-action buttons in message bubbles',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'cta-btn-bg', friendlyName: 'CTA Button Background', description: 'Background of call-to-action buttons like Setup Billing' },
      { cssVar: 'cta-btn-text', friendlyName: 'CTA Button Text', description: 'Text on call-to-action buttons' },
    ],
  },
  {
    groupName: 'Annotation Save Button',
    groupDescription: 'Save/confirm button for image annotations',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'annotation-btn-bg', friendlyName: 'Annotation Save Button', description: 'Background of the annotation save button' },
      { cssVar: 'annotation-btn-text', friendlyName: 'Annotation Save Text', description: 'Text on the annotation save button' },
      { cssVar: 'annotation-btn-hover', friendlyName: 'Annotation Save Hover', description: 'Hover background of the annotation save button' },
      { cssVar: 'annotation-btn-focus', friendlyName: 'Annotation Save Focus Ring', description: 'Focus ring color of the annotation save button' },
    ],
  },
  {
    groupName: 'Translation Highlight',
    groupDescription: 'Active word highlighting during audio playback',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'marker-bg', friendlyName: 'Highlighter Background', description: 'Background for actively spoken translation words' },
      { cssVar: 'marker-text', friendlyName: 'Highlighter Text', description: 'Text color for actively spoken words' },
    ],
  },
  {
    groupName: 'Notebook Marks',
    groupDescription: 'Sketch lines, watercolor wash, and correction marks',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'pencil-stroke', friendlyName: 'Pencil Stroke', description: 'Dark sketch strokes and strong notebook outlines' },
      { cssVar: 'pencil-emphasis', friendlyName: 'Pencil Emphasis', description: 'Emphasized pencil strokes and markups' },
      { cssVar: 'sketch-line', friendlyName: 'Sketch Line', description: 'Thin sketchy outlines and subtle notebook lines' },
      { cssVar: 'sketch-shadow', friendlyName: 'Sketch Shadow', description: 'Shadows in hand-drawn elements' },
      { cssVar: 'watercolor-wash', friendlyName: 'Watercolor Wash', description: 'Soft watercolor accent wash' },
      { cssVar: 'correction-pen', friendlyName: 'Correction Pen', description: 'Correction/error red pen color' },
    ],
  },
  {
    groupName: 'Message Tape Effect',
    groupDescription: 'Translucent tape strips, wrinkles, and lifted tape shading on message bubbles',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'tape-bg-light', friendlyName: 'Tape Light Fill', description: 'Lightest translucent tone in the tape gradient' },
      { cssVar: 'tape-bg-mid', friendlyName: 'Tape Mid Fill', description: 'Mid translucent tone in the tape gradient' },
      { cssVar: 'tape-bg-dark', friendlyName: 'Tape Dark Fill', description: 'Darkest translucent tone in the tape gradient' },
      { cssVar: 'tape-border', friendlyName: 'Tape Border', description: 'Thin border line around each tape strip' },
      { cssVar: 'tape-shadow', friendlyName: 'Tape Shadow', description: 'Outer shadow beneath tape strips and lifted corners' },
      { cssVar: 'tape-inset', friendlyName: 'Tape Inset Glow', description: 'Soft inner glow inside tape strips' },
      { cssVar: 'tape-wrinkle', friendlyName: 'Tape Wrinkle', description: 'Crease tint used in wrinkled tape strips' },
      { cssVar: 'tape-highlight', friendlyName: 'Tape Highlight', description: 'Glossy highlight streak inside tape strips' },
      { cssVar: 'tape-crease', friendlyName: 'Tape Crease Shadow', description: 'Lower crease shadow in wrinkled tape strips' },
    ],
  },
  {
    groupName: 'Borders and Focus',
    groupDescription: 'Global outlines and focus glow',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'line-border', friendlyName: 'Default Border', description: 'Most borders and separator lines' },
      { cssVar: 'input-outline', friendlyName: 'Input Outline', description: 'Text input outlines' },
      { cssVar: 'focus-ring', friendlyName: 'Focus Glow', description: 'Glow shown when controls are focused' },
    ],
  },
  {
    groupName: 'Maestro Flag: Hold',
    groupDescription: 'Top-left flag when you pause maestro',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'flag-hold-bg', friendlyName: 'Hold Background', description: 'Flag background in hold mode' },
      { cssVar: 'flag-hold-border', friendlyName: 'Hold Border', description: 'Flag border in hold mode' },
      { cssVar: 'flag-hold-text', friendlyName: 'Hold Text', description: 'Flag icon/text in hold mode' },
    ],
  },
  {
    groupName: 'Maestro Flag: Speaking and Typing',
    groupDescription: 'Top-left flag while maestro is actively responding',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'flag-speaking-bg', friendlyName: 'Speaking Background', description: 'Flag background while maestro is speaking' },
      { cssVar: 'flag-speaking-border', friendlyName: 'Speaking Border', description: 'Flag border while maestro is speaking' },
      { cssVar: 'flag-speaking-text', friendlyName: 'Speaking Text', description: 'Flag icon/text while maestro is speaking' },
      { cssVar: 'flag-typing-bg', friendlyName: 'Typing Background', description: 'Flag background while maestro is typing' },
      { cssVar: 'flag-typing-border', friendlyName: 'Typing Border', description: 'Flag border while maestro is typing' },
      { cssVar: 'flag-typing-text', friendlyName: 'Typing Text', description: 'Flag icon/text while maestro is typing' },
    ],
  },
  {
    groupName: 'Maestro Flag: Listening, Observing, Idle',
    groupDescription: 'Top-left flag for passive or waiting states',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'flag-listening-bg', friendlyName: 'Listening Background', description: 'Flag background while maestro is listening' },
      { cssVar: 'flag-listening-border', friendlyName: 'Listening Border', description: 'Flag border while maestro is listening' },
      { cssVar: 'flag-listening-text', friendlyName: 'Listening Text', description: 'Flag icon/text while maestro is listening' },
      { cssVar: 'flag-observing-bg', friendlyName: 'Observing Background', description: 'Flag background while observing quietly' },
      { cssVar: 'flag-observing-border', friendlyName: 'Observing Border', description: 'Flag border while observing quietly' },
      { cssVar: 'flag-observing-text', friendlyName: 'Observing Text', description: 'Flag icon/text while observing quietly' },
      { cssVar: 'flag-engaging-bg', friendlyName: 'About To Engage Background', description: 'Flag background when maestro is about to engage' },
      { cssVar: 'flag-engaging-border', friendlyName: 'About To Engage Border', description: 'Flag border when maestro is about to engage' },
      { cssVar: 'flag-engaging-text', friendlyName: 'About To Engage Text', description: 'Flag icon/text when maestro is about to engage' },
      { cssVar: 'flag-idle-bg', friendlyName: 'Idle Background', description: 'Flag background when nothing is running' },
      { cssVar: 'flag-idle-border', friendlyName: 'Idle Border', description: 'Flag border when nothing is running' },
      { cssVar: 'flag-idle-text', friendlyName: 'Idle Text', description: 'Flag icon/text when nothing is running' },
      { cssVar: 'flag-busy-bg', friendlyName: 'Busy Background', description: 'Flag background tint while background tasks are active' },
      { cssVar: 'flag-busy-border', friendlyName: 'Busy Border', description: 'Flag border tint while background tasks are active' },
      { cssVar: 'flag-busy-text', friendlyName: 'Busy Text', description: 'Flag icon/text while background tasks are active' },
    ],
  },
  {
    groupName: 'API Key Button',
    groupDescription: 'Top-right button that shows key present/missing',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'apikey-ok-bg', friendlyName: 'Key Present Background', description: 'API key button background when key exists' },
      { cssVar: 'apikey-ok-hover', friendlyName: 'Key Present Hover', description: 'API key button hover color when key exists' },
      { cssVar: 'apikey-ok-text', friendlyName: 'Key Present Text', description: 'API key button text/icon when key exists' },
      { cssVar: 'apikey-missing-bg', friendlyName: 'Key Missing Background', description: 'API key button background when key is missing' },
      { cssVar: 'apikey-missing-hover', friendlyName: 'Key Missing Hover', description: 'API key button hover color when key is missing' },
      { cssVar: 'apikey-missing-text', friendlyName: 'Key Missing Text', description: 'API key button text/icon when key is missing' },
    ],
  },
  {
    groupName: 'Microphone Recording Button',
    groupDescription: 'Hold-to-record and listening mic states',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'mic-record-bg', friendlyName: 'Mic Recording Background', description: 'Mic button while hold-to-record is active' },
      { cssVar: 'mic-record-icon', friendlyName: 'Mic Recording Icon', description: 'Mic icon while hold-to-record is active' },
      { cssVar: 'mic-record-ring', friendlyName: 'Mic Recording Ring', description: 'Ring around mic while hold-to-record is active' },
      { cssVar: 'mic-stt-bg', friendlyName: 'Mic Listening Background', description: 'Mic button while speech-to-text is listening' },
      { cssVar: 'mic-stt-icon', friendlyName: 'Mic Listening Icon', description: 'Mic icon while speech-to-text is listening' },
      { cssVar: 'mic-pulse-outer', friendlyName: 'Mic Pulse Outer', description: 'Outer pulse ring while hold-to-record is active' },
      { cssVar: 'mic-pulse-inner', friendlyName: 'Mic Pulse Inner', description: 'Inner pulse ring while hold-to-record is active' },
    ],
  },
  {
    groupName: 'Live and Attachment Recording Controls',
    groupDescription: 'Live chip, stop squares, remove buttons, and inline recording errors',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'live-badge-bg', friendlyName: 'Live Badge Background', description: 'The small LIVE badge background in live preview' },
      { cssVar: 'live-badge-text', friendlyName: 'Live Badge Text', description: 'Text color inside the LIVE badge' },
      { cssVar: 'live-badge-dot', friendlyName: 'Live Badge Dot', description: 'Blinking dot inside the LIVE badge' },
      { cssVar: 'live-stop-bg', friendlyName: 'Live Stop Button Background', description: 'Round stop button background while live session is active' },
      { cssVar: 'live-stop-hover', friendlyName: 'Live Stop Button Hover', description: 'Round stop button hover color while live session is active' },
      { cssVar: 'live-stop-text', friendlyName: 'Live Stop Button Foreground', description: 'Foreground color on live-session stop button' },
      { cssVar: 'live-stop-icon', friendlyName: 'Live Stop Square Icon', description: 'Square stop icon for live-session stop button' },
      { cssVar: 'vid-stop-bg', friendlyName: 'Video Stop Button Background', description: 'Round stop button background while local video recording is active' },
      { cssVar: 'vid-stop-hover', friendlyName: 'Video Stop Button Hover', description: 'Round stop button hover while local video recording is active' },
      { cssVar: 'vid-stop-text', friendlyName: 'Video Stop Button Foreground', description: 'Foreground color on local-video stop button' },
      { cssVar: 'vid-stop-icon', friendlyName: 'Video Stop Square Icon', description: 'Square stop icon for local-video recording stop button' },
      { cssVar: 'remove-attach-bg', friendlyName: 'Remove Attachment Background', description: 'Round X button background for removing an attachment' },
      { cssVar: 'remove-attach-hover', friendlyName: 'Remove Attachment Hover', description: 'Round X button hover color for removing an attachment' },
      { cssVar: 'remove-attach-icon', friendlyName: 'Remove Attachment Icon', description: 'X icon color on remove-attachment button' },
      { cssVar: 'rec-dot', friendlyName: 'REC Dot', description: 'Tiny REC indicator dot while local recording is active' },
      { cssVar: 'rec-error-bg', friendlyName: 'Recording Error Background', description: 'Inline error background related to recording/live issues' },
      { cssVar: 'rec-error-text', friendlyName: 'Recording Error Text', description: 'Inline error text related to recording/live issues' },
      { cssVar: 'top-live-active-bg', friendlyName: 'Live Button Active Background', description: 'Live-session button background when session is active' },
      { cssVar: 'top-live-active-hover', friendlyName: 'Live Button Active Hover', description: 'Live-session button hover color when session is active' },
      { cssVar: 'top-live-active-text', friendlyName: 'Live Button Active Text', description: 'Live-session button text when session is active' },
      { cssVar: 'top-live-error-bg', friendlyName: 'Top Live Button Error Background', description: 'Top live button background when retry is needed' },
      { cssVar: 'top-live-error-hover', friendlyName: 'Top Live Button Error Hover', description: 'Top live button hover color when retry is needed' },
      { cssVar: 'top-live-error-text', friendlyName: 'Top Live Button Error Text', description: 'Top live button text when retry is needed' },
      { cssVar: 'overlay-live-error-bg', friendlyName: 'Overlay Live Button Error Background', description: 'Overlay LIVE button background when retry is needed' },
      { cssVar: 'overlay-live-error-hover', friendlyName: 'Overlay Live Button Error Hover', description: 'Overlay LIVE button hover color when retry is needed' },
      { cssVar: 'overlay-live-error-text', friendlyName: 'Overlay Live Button Error Text', description: 'Overlay LIVE button text when retry is needed' },
    ],
  },
  {
    groupName: 'Action Confirmation Panels',
    groupDescription: 'Panels for load, delete, export, combine, and trim actions',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'action-load-bg', friendlyName: 'Load Panel', description: 'Panel background for load/import actions' },
      { cssVar: 'action-load-text', friendlyName: 'Load Panel Text', description: 'Text color in load/import panels' },
      { cssVar: 'action-delete-bg', friendlyName: 'Delete Panel', description: 'Panel background for delete/reset actions' },
      { cssVar: 'action-delete-text', friendlyName: 'Delete Panel Text', description: 'Text color in delete/reset panels' },
      { cssVar: 'action-export-bg', friendlyName: 'Export Panel', description: 'Panel background for export actions' },
      { cssVar: 'action-export-text', friendlyName: 'Export Panel Text', description: 'Text color in export panels' },
      { cssVar: 'action-combine-bg', friendlyName: 'Combine Panel', description: 'Panel background for merge/combine actions' },
      { cssVar: 'action-combine-text', friendlyName: 'Combine Panel Text', description: 'Text color in merge/combine panels' },
      { cssVar: 'action-trim-bg', friendlyName: 'Trim Panel', description: 'Panel background for trim actions' },
      { cssVar: 'action-trim-text', friendlyName: 'Trim Panel Text', description: 'Text color in trim panels' },
      { cssVar: 'delete-shortcut-hover-bg', friendlyName: 'Delete Shortcut Hover Background', description: 'Hover background of the small delete shortcut button' },
      { cssVar: 'delete-shortcut-hover-text', friendlyName: 'Delete Shortcut Hover Icon', description: 'Hover icon color of the small delete shortcut button' },
      { cssVar: 'trim-shortcut-hover-bg', friendlyName: 'Trim Shortcut Hover Background', description: 'Hover background of the small trim shortcut button' },
      { cssVar: 'trim-shortcut-hover-text', friendlyName: 'Trim Shortcut Hover Icon', description: 'Hover icon color of the small trim shortcut button' },
    ],
  },
  {
    groupName: 'Voice Identity',
    groupDescription: 'Color ring identity for each voice character',
    collapsedByDefault: true,
    colors: [
      { cssVar: 'voice-zephyr', friendlyName: 'Voice: Zephyr', description: 'Identity color for Zephyr voice' },
      { cssVar: 'voice-puck', friendlyName: 'Voice: Puck', description: 'Identity color for Puck voice' },
      { cssVar: 'voice-charon', friendlyName: 'Voice: Charon', description: 'Identity color for Charon voice' },
      { cssVar: 'voice-kore', friendlyName: 'Voice: Kore', description: 'Identity color for Kore voice' },
      { cssVar: 'voice-fenrir', friendlyName: 'Voice: Fenrir', description: 'Identity color for Fenrir voice' },
    ],
  },
];

export const ALL_COLOR_VARS: ColorVariable[] = COLOR_GROUPS.flatMap(g => g.colors);
