// Copyright 2026 Roni Tervo
// SPDX-License-Identifier: Apache-2.0
import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {isDeepStrictEqual} from 'node:util';
import {HeadlessRoomTransport} from '../src/headless/roomTransport';
import {runRoomActionTask,type RoomCommand} from '../src/core-sdk/room/roomAgent';
import {createHeadlessClient} from '../src/headless/client';
import {capabilityDefinition} from '../shared/capabilities';
import {constructionCaptureCall} from '../shared/roomSelection';
import {insertProgramCapability} from '../src/core-sdk/room/programCapabilityEditing';
import {getGeminiModels} from '../src/core-sdk/modelRegistry';
const directory=process.argv[2];if(!directory)throw new Error('Supply the explicitly started native probe directory.');
const prompt=process.env.MAESTRO_ROOM_PROBE_PROMPT;
const transport=await HeadlessRoomTransport.connect(directory,120000);
const observations:unknown[]=[];
try{
 const lease=transport.lease();const initial=structuredClone(lease.state());
 const execute=async(commands:RoomCommand[])=>{
  const state=lease.state();const result=await lease.execute(commands,state.sceneRevision,state.objects);observations.push(structuredClone(result));
  if(!result.ok)throw new Error('Native action refused: '+result.status);return result;
 };
 let outcome:unknown;
 if(prompt){
  const client=await createHeadlessClient({profileName:process.env.MAESTRO_ROOM_PROBE_PROFILE||'quest-probe'});
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),240000);
  const usage:unknown[]=[];
  try{outcome=await runRoomActionTask({model:getGeminiModels().text.default,prompt,history:[],nativeLanguageCode:'en-US',timeoutMs:45000},
   {aiClient:client.ai},lease,response=>usage.push({model:response.modelUsed,usage:response.usageMetadata}),{signal:controller.signal,onReceipt:receipt=>{observations.push(structuredClone(receipt));}});
  }finally{clearTimeout(timer);await client.save();}
  outcome={accessMode:client.accessMode,usage,result:outcome};
 }else{
  const catalog=await execute([{action:'catalog',catalog:{operation:'inspect',category:'actions',capability:'object.create',version:1}}]);
  const definition=catalog.catalog?.definition as {example?:Record<string,unknown>}|undefined;
  if(!definition?.example)throw new Error('The native create capability has no example.');
  const created=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.create',version:1,arguments:{...definition.example,name:'Native probe ball'}}}}]);
  const selected=created.execution?.selected;
  if(selected?.phase!=='completed'||typeof selected.output?.objectId!=='string')throw new Error('Creation did not produce a completed native receipt.');
  const target=selected.output.objectId;const original=created.objects.find(object=>object.id===target);
  if(!original||created.objects.length!==initial.objects.length+1)throw new Error('The object was not created in the real room.');
  const painted=await execute([{action:'paint',target,color:{r:1,g:0,b:0,a:1}}]);
  if(painted.objects.find(object=>object.id===target)?.color.r!==1)throw new Error('Native paint did not apply.');
  const undoPaint=await execute([{action:'undo'}]);
  if(JSON.stringify(undoPaint.objects.find(object=>object.id===target)?.color)!==JSON.stringify(original.color))throw new Error('Native Undo did not restore the previous paint.');
  const undoCreate=await execute([{action:'undo'}]);
  if(undoCreate.objects.some(object=>object.id===target)||undoCreate.objects.length!==initial.objects.length)throw new Error('Native Undo did not remove the created object.');
  const diagnostic=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'runtime.modelBudget',version:1}}]);
  if(!diagnostic.catalog?.available)throw new Error('Native resource diagnostics are unavailable.');
  const repeat=Number(process.env.MAESTRO_ROOM_PROBE_REPEATS??1);if(!Number.isInteger(repeat)||repeat<1||repeat>32)throw new Error('Probe repeats must be 1–32.');
  for(let cycle=0;cycle<repeat;cycle++){
  const cases=JSON.parse(await readFile('unity/MaestroQuest/Assets/Maestro/Tests/Fixtures/lathe-contract.json','utf8'));
  const cup=cases[0].recipe;
  const lathe=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.create',version:1,arguments:{kind:'recipe',name:'Native profile cup',x:.2,y:1,z:.5,scale:1,recipe:cup}}}}]);
  const cupId=lathe.execution?.selected?.output?.objectId;if(typeof cupId!=='string')throw new Error('Lathe creation did not return an object.');
  const inspected=await execute([{action:'inspect',target:cupId}]);
  if(inspected.inspection?.recipe?.parts[0].shape!=='lathe')throw new Error('The shared client cannot inspect the native lathe.');
  const changed=structuredClone(inspected.inspection.recipe.parts[0]);changed.profile[1].x=.48;changed.segments=32;
  const edited=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.recipe.edit',version:1,arguments:{target:cupId,revision:inspected.inspection.objectRevision,parts:[changed],removeParts:[],tracks:[],removeTracks:[],duration:cup.duration,loop:false}}}}]);
  const revision=edited.objects.find(object=>object.id===cupId)?.objectRevision;
  const profile=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.recipe.profile',version:1,arguments:{target:cupId,revision,part:'Body',offset:0}}}]);
  const value=profile.catalog?.value as {segments?:number;points?:{x:number;y:number}[]}|undefined;
  if(!profile.catalog?.available||value?.segments!==32||Math.abs((value.points?.[1].x??0)-.48)>.00001)throw new Error('Native lathe readback differs from the edit.');
  await execute([{action:'undo'}]);const restored=await execute([{action:'inspect',target:cupId}]);
  if(restored.inspection?.recipe?.parts[0].segments!==24)throw new Error('Lathe Undo did not restore the profile.');
  const collisionCases=JSON.parse(await readFile('unity/MaestroQuest/Assets/Maestro/Tests/Fixtures/collision-contract.json','utf8'));
  const collisionCatalog=await execute([{action:'catalog',catalog:{operation:'search',query:'Edit collision shapes',offset:0}}]);
  const collisionDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.collision.edit',version:1}}]);
  const collisionCurrent=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.collision',version:1,arguments:{target:cupId}}}]);
  const collided=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.collision.edit',version:1,arguments:{target:cupId,revision:restored.inspection!.objectRevision,collision:collisionCases[0].collision}}}}]);
  const collisionRevision=collided.objects.find(object=>object.id===cupId)?.objectRevision;
  const summary=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.collision',version:1,arguments:{target:cupId}}}]);
  const summaryValue=summary.catalog?.value as {pieces?:number;shapes?:number;customActive?:boolean}|undefined;
  if(summaryValue?.pieces!==13||summaryValue.shapes!==2||summaryValue.customActive!==true)throw new Error('Native compound collision summary differs from the edit.');
  const wall=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.collision.shape',version:1,arguments:{target:cupId,revision:collisionRevision,index:1}}}]);
  if((wall.catalog?.value as {shape?:{id?:string;shape?:string}})?.shape?.shape!=='ring')throw new Error('Native collision shape readback is missing the hollow wall.');
  await execute([{action:'undo'}]);
  const collisionRestored=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.collision',version:1,arguments:{target:cupId}}}]);
  if((collisionRestored.catalog?.value as {shapes?:number})?.shapes!==0)throw new Error('Collision Undo did not restore the default proxy.');
  await writeFile(join(directory,'collision-authoring.json'),JSON.stringify({boundary:'Real Unity native states; browser acknowledgements replayed separately. Not headset or provider proof.',before:restored,search:collisionCatalog,definition:collisionDefinition,current:collisionCurrent,after:collided,summary,wall},null,2));
  const removed=await execute([{action:'undo'}]);if(removed.objects.some(object=>object.id===cupId))throw new Error('Lathe Undo did not remove the created geometry.');
  const templateBefore=structuredClone(lease.state());
  const templateSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Create object',offset:0}}]);
  const templateDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.create',version:1}}]);
  const templateSchema=templateDefinition.catalog?.definition as {input:{oneOf:{examples:Record<string,unknown>[]}[]}};
  const templateArgs=templateSchema.input.oneOf.find(branch=>branch.examples[0]?.kind==='template')?.examples[0];if(!templateArgs)throw new Error('Starter templates unavailable');
  const templateAfter=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.create',version:1,arguments:templateArgs}}}]);
  const templateId=templateAfter.execution?.selected?.output?.objectId;if(typeof templateId!=='string')throw new Error('Template creation returned no object');
  const templateRead=await execute([{action:'inspect',target:templateId}]);
  if(templateRead.objects.find(object=>object.id===templateId)?.name!=='Cup'||templateRead.inspection?.recipe?.parts.length!==2)throw new Error('Template geometry did not expand');
  const templateCollision=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.collision',version:1,arguments:{target:templateId}}}]);
  if((templateCollision.catalog?.value as {pieces?:number})?.pieces!==21)throw new Error('Template collision did not expand');
  const templatePhysics=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.physics.settings',version:1,arguments:{target:templateId}}}]);
  if((templatePhysics.catalog?.value as {mode?:string})?.mode!=='solid')throw new Error('Template physics did not expand');
  const templateUndo=await execute([{action:'undo'}]);if(templateUndo.objects.some(object=>object.id===templateId))throw new Error('Single Undo did not remove the whole template');
  await writeFile(join(directory,'template-authoring.json'),JSON.stringify({boundary:'Real Unity native states; browser acknowledgements replayed separately. Not headset or provider proof.',before:templateBefore,search:templateSearch,definition:templateDefinition,after:templateAfter,read:templateRead,collision:templateCollision,physics:templatePhysics,undo:templateUndo},null,2));
  const brickSource=JSON.parse(await readFile('unity/MaestroQuest/Assets/Maestro/Resources/Creation/Templates/brick.json','utf8'));
  const {createHash}=await import('node:crypto');const brickHash=createHash('sha256').update(await readFile('unity/MaestroQuest/Assets/Maestro/Resources/Creation/Templates/brick.json')).digest('hex');
  const chalkSource=JSON.parse(await readFile('unity/MaestroQuest/Assets/Maestro/Resources/Creation/Templates/chalkboard.json','utf8'));
  const chalkHash=createHash('sha256').update(await readFile('unity/MaestroQuest/Assets/Maestro/Resources/Creation/Templates/chalkboard.json')).digest('hex');
  const chalkCreated=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.create',version:1,arguments:{kind:'template',templateHash:chalkHash,name:'',x:.4,y:1,z:.6,scale:1}}}}]);
  const chalkId=chalkCreated.execution?.selected?.output?.objectId;if(typeof chalkId!=='string')throw new Error('Chalkboard template did not create an object');
  const chalkTool=await execute([{action:'execution',execution:{operation:'start',call:{id:'drawing.tool.set',version:1,arguments:{mode:'surface',red:1,green:1,blue:1,radius:.003}}}}]);
  const chalkToolRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'drawing.tool',version:1}}]);
  if((chalkToolRead.catalog?.value as {mode?:string})?.mode!=='surface')throw new Error('Shared pencil mode did not apply');
  const surfaceSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Edit a drawing surface',offset:0}}]);
  const surfaceDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.surface.edit',version:1}}]);
  const surfaceCurrent=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.surfaces',version:1,arguments:{target:chalkId}}}]);
  const surfaceValue=surfaceCurrent.catalog?.value as {revision:number;surfaces:{id:string;part:string}[]};
  if(surfaceValue?.surfaces[0]?.part!==chalkSource.definition.surfaces[0].part)throw new Error('Template drawing patch missing');
  const surfaceArgs={operation:'add',target:chalkId,revision:surfaceValue.revision,surface:'Front',stroke:'',red:1,green:1,blue:1,radius:.003,points:[{x:-.2,y:0,z:0},{x:0,y:.15,z:0},{x:.2,y:0,z:0}]};
  const surfaceAfter=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.surface.edit',version:1,arguments:surfaceArgs}}}]);
  const stroke=surfaceAfter.execution?.selected?.output?.stroke,inkRevision=surfaceAfter.execution?.selected?.output?.revision;
  if(typeof stroke!=='string'||typeof inkRevision!=='number')throw new Error('Surface ink receipt missing');
  const inkRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.surface.stroke',version:1,arguments:{target:chalkId,surface:'Front',stroke,revision:inkRevision,offset:0}}}]);
  const inkValue=inkRead.catalog?.value as {total?:number;points?:unknown[]};if(inkValue?.total!==3||JSON.stringify(inkValue.points)!==JSON.stringify(surfaceArgs.points))throw new Error('Native ink differs from shared authoring');
  const erased=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.surface.edit',version:1,arguments:{operation:'removeStroke',target:chalkId,surface:'Front',stroke,revision:inkRevision}}}}]);
  const erasedRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.surfaces',version:1,arguments:{target:chalkId}}}]);
  if((erasedRead.catalog?.value as {surfaces:{strokes:number}[]})?.surfaces[0].strokes!==0)throw new Error('Surface erasing did not remove ink');
  await execute([{action:'undo'}]);
  const surfaceUndo=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.surfaces',version:1,arguments:{target:chalkId}}}]);
  if((surfaceUndo.catalog?.value as {surfaces:{strokes:number}[]})?.surfaces[0].strokes!==1)throw new Error('Ink Undo did not restore stroke');
  await execute([{action:'undo'}]);await execute([{action:'undo'}]);
  await execute([{action:'execution',execution:{operation:'start',call:{id:'drawing.tool.set',version:1,arguments:{mode:'off',red:1,green:1,blue:1,radius:.003}}}}]);
  await writeFile(join(directory,'surface-authoring.json'),JSON.stringify({boundary:'Real Unity native states and shared transport; browser acknowledgements replayed separately. No headset or provider proof.',before:chalkCreated,tool:chalkTool,toolRead:chalkToolRead,search:surfaceSearch,definition:surfaceDefinition,current:surfaceCurrent,after:surfaceAfter,read:inkRead,erased,erasedRead,undo:surfaceUndo},null,2));
  const tipHash=createHash('sha256').update(await readFile('unity/MaestroQuest/Assets/Maestro/Resources/Creation/Templates/chalk.json')).digest('hex');
  const tipCreated=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.create',version:1,arguments:{kind:'template',templateHash:tipHash,name:'',x:.4,y:1,z:.6,scale:1}}}}]);
  const tipId=tipCreated.execution?.selected?.output?.objectId;if(typeof tipId!=='string')throw new Error('Chalk template did not create a tool');
  const tipSearch=await execute([{action:'catalog',catalog:{operation:'search',query:"Configure an object's drawing tip",offset:0}}]);
  const tipDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.drawingTip.edit',version:1}}]);
  const tipCurrent=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.drawingTip',version:1,arguments:{target:tipId}}}]);
  const tipValue=tipCurrent.catalog?.value as {configured:boolean;revision:number;definition:{part:string;enabled:boolean;color:{r:number;g:number;b:number;a:number}}};
  if(!tipValue?.configured||tipValue.definition.part!=='Chalk')throw new Error('Chalk component missing');
  const tipArgs={operation:'configure',target:tipId,revision:tipValue.revision,definition:{...tipValue.definition,color:{r:.1,g:.5,b:.9,a:1}}};
  const tipEdited=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.drawingTip.edit',version:1,arguments:tipArgs}}}]);
  const tipRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.drawingTip',version:1,arguments:{target:tipId}}}]);
  const tipAfter=tipRead.catalog?.value as typeof tipValue;if(Math.abs(tipAfter?.definition.color.b-.9)>.00001)throw new Error('Shared drawing-tip ink edit failed');
  await execute([{action:'undo'}]);
  const tipUndo=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.drawingTip',version:1,arguments:{target:tipId}}}]);
  if((tipUndo.catalog?.value as typeof tipValue)?.definition.color.b!==1)throw new Error('Drawing-tip Undo failed');
  await execute([{action:'undo'}]);
  await writeFile(join(directory,'drawing-tip-authoring.json'),JSON.stringify({boundary:'Real Unity native configuration/readback/Undo; physical grip tested separately. No headset or provider proof.',before:tipCreated,search:tipSearch,definition:tipDefinition,current:tipCurrent,after:tipEdited,read:tipRead,undo:tipUndo},null,2));
  const layoutIds:string[]=[];let layoutBefore=templateUndo;
  for(let i=0;i<2;i++){
   layoutBefore=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.create',version:1,arguments:{kind:'template',templateHash:brickHash,name:brickSource.name+' '+(i+1),x:.4+i*.25,y:1.2,z:.7,scale:1}}}}]);
   const id=layoutBefore.execution?.selected?.output?.objectId;if(typeof id!=='string')throw new Error('Layout member missing');layoutIds.push(id);
  }
  const hingeSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Connect physical pieces',offset:0}}]);
  const hingeDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.connection.edit',version:1}}]);
  const hingeCurrent=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection',version:1,arguments:{target:layoutIds[0]}}}]);
  const hingeValue=hingeCurrent.catalog?.value as {configured:boolean;revision:number;connected:string;definition:{enabled:boolean;kind:string;breakForce:number;breakTorque:number}};
  if(hingeValue?.configured)throw new Error('New piece unexpectedly has a hinge');
  const hingeFrames:Record<string,unknown>={};for(const side of ['owner','connected']){
   const read=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection.frame',version:1,arguments:{target:layoutIds[0],side}}}]);
   const value=read.catalog?.value as {revision:number;frame:unknown};if(value.revision!==hingeValue.revision)throw new Error('Hinge frame revision changed');hingeFrames[side+'Frame']=value.frame;
  }
  const hingeDefaults=capabilityDefinition('object.connection.edit')!.example!.definition as {limits:Record<string,unknown>;drive:Record<string,unknown>};
  const hingeArgs={operation:'configure',target:layoutIds[0],connected:layoutIds[1],revision:hingeValue.revision,definition:{...hingeValue.definition,...hingeFrames,enabled:true,drive:{...hingeDefaults.drive,mode:'spring',target:20},limits:{...hingeDefaults.limits,enabled:true}}};
  const hingeAfter=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.connection.edit',version:1,arguments:hingeArgs}}}]);
  const hingeRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection',version:1,arguments:{target:layoutIds[0]}}}]);
  const hingeTuning=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection.hinge',version:1,arguments:{target:layoutIds[0]}}}]);
  const hingeSaved=hingeRead.catalog?.value as typeof hingeValue;if(!hingeSaved?.configured||hingeSaved.connected!==layoutIds[1]||(hingeTuning.catalog?.value as {drive:{target:number}}).drive.target!==20)throw new Error('Hinge source did not persist');
  const hingeAligned=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.connection.edit',version:1,arguments:{operation:'align',target:layoutIds[0],connected:layoutIds[1],revision:hingeSaved.revision,angle:30}}}}]);
  const hingeState=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection.state',version:1,arguments:{target:layoutIds[0]}}}]);
  if(Math.abs((hingeState.catalog?.value as {angle:number}).angle-30)>.05)throw new Error('Hinge alignment readback differs');
  await execute([{action:'undo'}]);await execute([{action:'undo'}]);
  const hingeUndo=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection',version:1,arguments:{target:layoutIds[0]}}}]);
  if((hingeUndo.catalog?.value as typeof hingeValue).configured)throw new Error('Hinge Undo did not remove component');
  await writeFile(join(directory,'hinge-authoring.json'),JSON.stringify({boundary:'Real Unity configuration, alignment, readback and Undo. PhysX tested separately; no headset or provider proof.',before:layoutBefore,search:hingeSearch,definition:hingeDefinition,current:hingeCurrent,after:hingeAfter,read:hingeRead,tuning:hingeTuning,aligned:hingeAligned,state:hingeState,undo:hingeUndo},null,2));
  const connectionBefore=hingeUndo;
  const connectionSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Connect physical pieces',offset:0}}]);
  const connectionDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.connection.edit',version:1}}]);
  const connectionCurrent=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection',version:1,arguments:{target:layoutIds[0]}}}]);
  const connectionArgs={operation:'attach',target:layoutIds[0],connected:layoutIds[1],revision:(connectionCurrent.catalog?.value as {revision:number}).revision,breakForce:45,breakTorque:3};
  const connectionAfter=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.connection.edit',version:1,arguments:connectionArgs}}}]);
  const connectionRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection',version:1,arguments:{target:layoutIds[0]}}}]);
  const connectionSaved=connectionRead.catalog?.value as typeof hingeValue;
  if(!connectionSaved?.configured||connectionSaved.definition.kind!=='fixed'||connectionSaved.definition.breakForce!==45||connectionSaved.definition.breakTorque!==3||connectionSaved.connected!==layoutIds[1])throw new Error('Fixed connection did not persist its exact members and break limits');
  for(const id of layoutIds){const before=hingeUndo.objects.find(o=>o.id===id)!,after=connectionAfter.objects.find(o=>o.id===id)!;if(JSON.stringify(before.position)!==JSON.stringify(after.position)||JSON.stringify(before.rotation)!==JSON.stringify(after.rotation))throw new Error('Fixed join moved its members');}
  const connectionState=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection.state',version:1,arguments:{target:layoutIds[0]}}}]);
  if((connectionState.catalog?.value as {active:boolean;broken:boolean}).active)throw new Error('Joining unexpectedly started physics');
  const connectionUndo=await execute([{action:'undo'}]);
  const connectionUndone=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection',version:1,arguments:{target:layoutIds[0]}}}]);
  if((connectionUndone.catalog?.value as typeof hingeValue).configured)throw new Error('Single Undo did not remove fixed connection');
  await writeFile(join(directory,'connection-authoring.json'),JSON.stringify({boundary:'Real Unity native attach/readback/Undo. PhysX break and typed event tested separately; no headset or provider proof.',before:connectionBefore,search:connectionSearch,definition:connectionDefinition,current:connectionCurrent,arguments:connectionArgs,after:connectionAfter,read:connectionRead,state:connectionState,undo:connectionUndo,undone:connectionUndone},null,2));
  const buttonModule=JSON.parse(await readFile('unity/MaestroQuest/Assets/Maestro/Resources/Programs/Modules/SpringButton.json','utf8'));
  const buttonArgs=buttonModule.program.functions.find((f:{name:string})=>f.name==='create').body[0].arguments;
  const buttonCreated=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.batch.create',version:1,arguments:buttonArgs}}}]);
  const buttonIds=buttonCreated.execution?.selected?.output?.objectIds;if(!Array.isArray(buttonIds)||buttonIds.length!==2||!buttonIds.every(id=>typeof id==='string'))throw new Error('Spring button did not create two members');
  const sliderTarget=buttonIds[1] as string,sliderMount=buttonIds[0] as string;
  const sliderBefore=structuredClone(lease.state());
  const sliderSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Connect physical pieces',offset:0}}]);
  const sliderDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.connection.edit',version:1}}]);
  const sliderCurrent=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection',version:1,arguments:{target:sliderTarget}}}]);
  const sliderConfig=structuredClone(buttonArgs.blueprint.connections[0].definition);sliderConfig.slide.target=.01;
  const sliderArguments={operation:'configure',target:sliderTarget,connected:sliderMount,revision:(sliderCurrent.catalog?.value as {revision:number}).revision,definition:sliderConfig};
  const sliderAfter=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.connection.edit',version:1,arguments:sliderArguments}}}]);
  const sliderTuning=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection.slider',version:1,arguments:{target:sliderTarget}}}]);
  const sliderSettings=sliderTuning.catalog?.value as {revision:number;slide:{target:number}};if(Math.abs(sliderSettings.slide.target-.01)>.000001)throw new Error('Slider spring target did not persist');
  const sliderAligned=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.connection.edit',version:1,arguments:{operation:'slide',target:sliderTarget,connected:sliderMount,revision:sliderSettings.revision,distance:.025}}}}]);
  const sliderRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection.travel',version:1,arguments:{target:sliderTarget}}}]);
  if(typeof sliderRead.catalog?.value!=='number'||Math.abs(sliderRead.catalog.value-.025)>.0001)throw new Error('Slider distance readback differs');
  await execute([{action:'undo'}]);const sliderUndo=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection.travel',version:1,arguments:{target:sliderTarget}}}]);
  if(typeof sliderUndo.catalog?.value!=='number'||Math.abs(sliderUndo.catalog.value)>.0001)throw new Error('Slider Undo did not restore its live travel');
  await execute([{action:'undo'}]);const buttonRemoved=await execute([{action:'undo'}]);if(buttonIds.some(id=>buttonRemoved.objects.some(o=>o.id===id)))throw new Error('Button construction was not one Undo');
  await writeFile(join(directory,'slider-authoring.json'),JSON.stringify({boundary:'Real Unity native slider configure/linear alignment/readback/Undo. Physical pressing and program response tested in PlayMode; no headset or provider proof.',before:sliderBefore,search:sliderSearch,definition:sliderDefinition,current:sliderCurrent,after:sliderAfter,tuning:sliderTuning,aligned:sliderAligned,read:sliderRead,undo:sliderUndo,removed:buttonRemoved},null,2));
  const placements=layoutIds.map((target,i)=>({target,position:{x:.3+i*.25,y:1,z:.8},rotation:{x:0,y:0,z:0,w:1},scale:1}));
  const layoutSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Arrange or reset objects',offset:0}}]);
  const layoutDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.layout.apply',version:1}}]);
  const layoutAfter=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.layout.apply',version:1,arguments:{placements}}}}]);
  if(layoutAfter.execution?.selected?.output?.count!==2)throw new Error('Layout did not complete both members');
  const layoutFacts=[];for(const p of placements){
   const fact=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.placement',version:1,arguments:{target:p.target}}}]);
   const value=fact.catalog?.value as {position?:{x:number;y:number;z:number};scale?:number};
   if(!value?.position||Math.abs(value.position.x-p.position.x)>.00001||Math.abs(value.position.y-p.position.y)>.00001||Math.abs(value.position.z-p.position.z)>.00001||value.scale!==1)throw new Error('Layout live readback differs');layoutFacts.push(fact);
  }
  const layoutUndo=await execute([{action:'undo'}]);for(let i=0;i<2;i++)if(Math.abs((layoutUndo.objects.find(o=>o.id===layoutIds[i])?.position.x??0)-(.4+i*.25))>.00001)throw new Error('Single Undo did not restore both layout members');
  await writeFile(join(directory,'layout-authoring.json'),JSON.stringify({boundary:'Real Unity native states; browser acknowledgements replayed separately. Not headset or provider proof.',before:layoutBefore,search:layoutSearch,definition:layoutDefinition,after:layoutAfter,facts:layoutFacts,undo:layoutUndo},null,2));
  await execute([{action:'undo'}]);await execute([{action:'undo'}]);
  const batchProgram=JSON.parse(await readFile('unity/MaestroQuest/Assets/Maestro/Tests/Fixtures/program-batch-create.json','utf8'));
  const batchArgs=batchProgram.functions[0].body[0].arguments,batchBefore=structuredClone(lease.state());
  const batchSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Create a structure',offset:0}}]);
  const batchDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.batch.create',version:1}}]);
  const batchAfter=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.batch.create',version:1,arguments:batchArgs}}}]);
  const batchIds=batchAfter.execution?.selected?.output?.objectIds,batchSlots=batchAfter.execution?.selected?.output?.slots;
  if(!Array.isArray(batchIds)||batchIds.length!==6||!batchIds.every(id=>typeof id==='string')||new Set(batchIds).size!==6||JSON.stringify(batchSlots)!==JSON.stringify(batchArgs.blueprint.pieces.map((p:{slot:string})=>p.slot)))throw new Error('Batch result lost piece identity/order');
  if(batchAfter.objects.length!==batchBefore.objects.length+6||batchIds.some(id=>!batchAfter.objects.some(o=>o.id===id)))throw new Error('Native structure pieces were not all created');
  const batchUndo=await execute([{action:'undo'}]);if(batchIds.some(id=>batchUndo.objects.some(o=>o.id===id))||batchUndo.objects.length!==batchBefore.objects.length)throw new Error('One Undo did not remove the whole batch');
  await writeFile(join(directory,'batch-authoring.json'),JSON.stringify({boundary:'Real Unity native states; browser acknowledgements replayed separately. Not headset or provider proof.',before:batchBefore,search:batchSearch,definition:batchDefinition,after:batchAfter,undo:batchUndo},null,2));
  const structureBefore=structuredClone(lease.state()),structureMembers=structureBefore.objects.filter(o=>!['Book','Maestro'].includes(o.kind)).slice(0,2).map(o=>o.id);
  if(structureMembers.length!==2)throw new Error('Two starter pieces are needed for the structure acceptance');
  const structureArgs={id:'',revision:0,source:{kind:'capture',name:'Native probe castle',positionTolerance:.05,rotationTolerance:15,scaleTolerance:.05,members:structureMembers.map((target,i)=>({slot:'piece_'+i,target}))}};
  const structureSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Save a structure',offset:0}}]);
  const structureDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'structure.save',version:1}}]);
  const structureAfter=await execute([{action:'execution',execution:{operation:'start',call:{id:'structure.save',version:1,arguments:structureArgs}}}]);
  const structureId=structureAfter.execution?.selected?.output?.structureId,structureRevision=structureAfter.execution?.selected?.output?.revision;
  if(typeof structureId!=='string'||typeof structureRevision!=='number')throw new Error('Native structure identity was not returned');
  const readStructure=()=>execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'structure.state',version:1,arguments:{id:structureId}}}]);
  const structureInitial=await readStructure();if((structureInitial.catalog?.value as {displaced?:number})?.displaced!==0)throw new Error('Captured structure should match its live pieces');
  const member=structureBefore.objects.find(o=>o.id===structureMembers[0])!;
  await execute([{action:'execution',execution:{operation:'start',call:{id:'object.position.set',version:1,arguments:{target:member.id,x:member.position.x+.4,y:member.position.y,z:member.position.z}}}}]);
  const structureDisplaced=await readStructure();if((structureDisplaced.catalog?.value as {displaced?:number})?.displaced!==1)throw new Error('Live member movement was not observed');
  const structureReset=await execute([{action:'execution',execution:{operation:'start',call:{id:'structure.reset',version:1,arguments:{id:structureId,revision:structureRevision,members:structureMembers}}}}]);
  const structureRestored=await readStructure();if((structureRestored.catalog?.value as {displaced?:number})?.displaced!==0)throw new Error('Structure reset did not restore its captured baseline');
  const structureUndo=await execute([{action:'undo'}]);if(Math.abs((structureUndo.objects.find(o=>o.id===member.id)?.position.x??0)-member.position.x-.4)>.00001)throw new Error('Structure Undo lost the displaced pose');
  await execute([{action:'undo'}]);await execute([{action:'undo'}]);
  await writeFile(join(directory,'structure-authoring.json'),JSON.stringify({boundary:'Real Unity native states; browser acknowledgements replayed separately. Not headset or provider proof.',before:structureBefore,search:structureSearch,definition:structureDefinition,after:structureAfter,initial:structureInitial,displaced:structureDisplaced,reset:structureReset,restored:structureRestored,undo:structureUndo},null,2));
  const compositionSource=await readFile('unity/MaestroQuest/Assets/Maestro/Tests/Fixtures/program-build-structure.json','utf8');
  const compositionBefore=await execute([{action:'rules',rule:{action:'inspect'}}]);
  const compositionSaved=await execute([{action:'rules',rule:{action:'edit',revision:compositionBefore.rules!.revision,edits:[{kind:'save',reference:'composition',sequence:{id:'',name:'Native build/reset probe',interruption:0,repeat:false,program:compositionSource}}]}}]);
  const compositionId=compositionSaved.rules?.sequences.find(s=>s.name==='Native build/reset probe')?.id;if(!compositionId)throw new Error('Composed program was not saved');
  let compositionAfter=await execute([{action:'rules',rule:{action:'play',revision:compositionSaved.rules!.revision,target:compositionId}}]);
  const compositionDeadline=Date.now()+15000;
  while(!compositionAfter.rules?.outcomes?.some(o=>o.sequenceId===compositionId)&&Date.now()<compositionDeadline){await new Promise(r=>setTimeout(r,100));compositionAfter=await execute([{action:'rules',rule:{action:'inspect',target:compositionId}}]);}
  const compositionOutcome=compositionAfter.rules?.outcomes?.find(o=>o.sequenceId===compositionId);
  if(compositionOutcome?.phase!=='completed'||compositionAfter.objects.length!==compositionBefore.objects.length+6)throw new Error('Composed build/reset failed: '+JSON.stringify(compositionOutcome));
  const compositionList=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'structure.list',version:1,arguments:{offset:0}}}]);
  const compositionGroup=(compositionList.catalog?.value as {entries?:{id:string;name:string;count:number}[]})?.entries?.find(e=>e.name==='Castle'&&e.count===6);
  if(!compositionGroup)throw new Error('Composed structure was not saved');
  const compositionState=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'structure.state',version:1,arguments:{id:compositionGroup.id}}}]);
  if((compositionState.catalog?.value as {displaced?:number})?.displaced!==0)throw new Error('Composed reset did not recover its baseline');
  const watcher=JSON.parse(await readFile('unity/MaestroQuest/Assets/Maestro/Tests/Fixtures/program-structure-watch.json','utf8'));
  const moduleHash=watcher.imports[0].hash;
  const includedModule=await execute([{action:'catalog',catalog:{operation:'inspect',category:'modules',capability:moduleHash,version:1}}]);
  const moduleView=includedModule.catalog;
  if(moduleView?.operation!=='inspect'||moduleView.category!=='modules'||!moduleView.included||JSON.stringify(moduleView.definition)!==JSON.stringify(watcher.imports[0].module))throw new Error('Included native module differs from the shared fixture');
  const watchedRevision=(compositionState.catalog?.value as {revision:number}).revision;
  watcher.state.find((v:{name:string})=>v.name==='structureId').initial=compositionGroup.id;
  watcher.state.find((v:{name:string})=>v.name==='revision').initial=watchedRevision;
  const watcherSaved=await execute([{action:'rules',rule:{action:'edit',revision:lease.state().rules!.revision,edits:[{kind:'save',reference:'watcher',sequence:{id:'',name:'Native structure watch probe',interruption:0,repeat:false,program:JSON.stringify(watcher)}}]}}]);
  const watcherId=watcherSaved.rules?.sequences.find(s=>s.name==='Native structure watch probe')?.id;
  if(!watcherId||watcherSaved.rules!.running.some(r=>r.sequenceId===watcherId))throw new Error('Saving the watcher must not start it');
  await execute([{action:'rules',rule:{action:'play',revision:watcherSaved.rules!.revision,target:watcherId}}]);
  const waitForWatch=async(phase:string,cycles:number)=>{
   const deadline=Date.now()+15000;let last;
   do {
    last=await execute([{action:'rules',rule:{action:'inspect',target:watcherId}}]);
    const run=last.rules?.running.find(r=>r.sequenceId===watcherId);
    if(run?.state?.some(v=>v.name==='phase'&&v.value===phase)&&run.state.some(v=>v.name==='cycles'&&v.value===String(cycles)))return last;
    if(last.rules?.outcomes?.some(o=>o.sequenceId===watcherId))throw new Error('Watcher ended unexpectedly: '+JSON.stringify(last.rules.outcomes));
    await new Promise(r=>setTimeout(r,100));
   }while(Date.now()<deadline);
   throw new Error('Watcher did not reach '+phase+': '+JSON.stringify(last?.rules?.running));
  };
  const watcherArmed=await waitForWatch('waitingForDisturbance',0);
  const slot=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'structure.slot',version:1,arguments:{id:compositionGroup.id,index:0}}}]);
  const slotValue=slot.catalog?.value as {target:string;position:{x:number;y:number;z:number}};
  const watcherMembers=compositionAfter.objects.filter(o=>!compositionBefore.objects.some(before=>before.id===o.id)).map(o=>o.id);
  if(!slotValue?.target||watcherMembers.length!==6||!watcherMembers.includes(slotValue.target))throw new Error('Watcher member identities unavailable');
  await execute([{action:'execution',execution:{operation:'start',call:{id:'object.position.set',version:1,arguments:{target:slotValue.target,x:slotValue.position.x+.3,y:slotValue.position.y,z:slotValue.position.z}}}}]);
  const watcherDisturbed=await waitForWatch('waitingForRebuild',1);
  await execute([{action:'execution',execution:{operation:'start',call:{id:'structure.reset',version:1,arguments:{id:compositionGroup.id,revision:watchedRevision,members:watcherMembers}}}}]);
  const watcherRebuilt=await waitForWatch('waitingForDisturbance',1);
  const watcherStopped=await execute([{action:'rules',rule:{action:'stop',target:watcherId}}]);
  if(watcherStopped.rules?.running.some(r=>r.sequenceId===watcherId))throw new Error('Watcher did not stop');
  await execute([{action:'rules',rule:{action:'edit',revision:lease.state().rules!.revision,edits:[{kind:'delete',target:watcherId}]}}]);
  await execute([{action:'undo'}]);await execute([{action:'undo'}]);
  await writeFile(join(directory,'program-structure-watch.json'),JSON.stringify({boundary:'Real Unity runtime and shared transport. Movement is an explicit edit here; ball physics is covered separately in PlayMode. No headset or provider proof.',source:watcher,module:includedModule,saved:watcherSaved,armed:watcherArmed,disturbed:watcherDisturbed,rebuilt:watcherRebuilt,stopped:watcherStopped},null,2));
  await execute([{action:'undo'}]);
  const compositionUndo=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'structure.state',version:1,arguments:{id:compositionGroup.id}}}]);
  if((compositionUndo.catalog?.value as {displaced?:number})?.displaced!==1)throw new Error('Composed reset Undo did not restore the displaced piece');
  await execute([{action:'undo'}]);await execute([{action:'undo'}]);await execute([{action:'undo'}]);
  await execute([{action:'rules',rule:{action:'edit',revision:lease.state().rules!.revision,edits:[{kind:'delete',target:compositionId}]}}]);
  await writeFile(join(directory,'program-composition.json'),JSON.stringify({boundary:'Real Unity runtime and shared transport; no headset or provider proof.',source:JSON.parse(compositionSource),saved:compositionSaved,after:compositionAfter,group:compositionGroup,state:compositionState,undo:compositionUndo,outcome:compositionOutcome},null,2));
  const leverSource=JSON.parse(await readFile('unity/MaestroQuest/Assets/Maestro/Tests/Fixtures/program-spring-lever.json','utf8'));
  const connectedArgs=leverSource.imports[0].module.program.functions.find((f:{name:string})=>f.name==='create').body[0].arguments;
  const connectedBefore=structuredClone(lease.state());
  const connectedSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Create a structure',offset:0}}]);
  const connectedDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.batch.create',version:1}}]);
  const connectedAfter=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.batch.create',version:1,arguments:connectedArgs}}}]);
  const connectedIds=connectedAfter.execution?.selected?.output?.objectIds;
  if(!Array.isArray(connectedIds)||connectedIds.length!==2||!connectedIds.every(id=>typeof id==='string')||new Set(connectedIds).size!==2||connectedAfter.objects.length!==connectedBefore.objects.length+2)throw new Error('Connected blueprint did not create exactly two distinct pieces');
  const connectedRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection',version:1,arguments:{target:connectedIds[1]}}}]);
  const connectedValue=connectedRead.catalog?.value as {configured:boolean;connected:string};
  if(!connectedValue.configured||connectedValue.connected!==connectedIds[0])throw new Error('Blueprint did not bind its hinge to its own mount');
  const connectedUndo=await execute([{action:'undo'}]);if(connectedIds.some(id=>connectedUndo.objects.some(o=>o.id===id))||connectedUndo.objects.length!==connectedBefore.objects.length)throw new Error('Connected blueprint was not one Undo');
  await writeFile(join(directory,'connected-blueprint-authoring.json'),JSON.stringify({boundary:'Real Unity native states; browser acknowledgements replayed separately. Physics tested in PlayMode; no headset or provider proof.',arguments:connectedArgs,before:connectedBefore,search:connectedSearch,definition:connectedDefinition,after:connectedAfter,read:connectedRead,undo:connectedUndo},null,2));
  const leverHash=leverSource.imports[0].hash;
  const leverModule=await execute([{action:'catalog',catalog:{operation:'inspect',category:'modules',capability:leverHash,version:1}}]);
  if(!leverModule.catalog?.included||JSON.stringify(leverModule.catalog.definition)!==JSON.stringify(leverSource.imports[0].module))throw new Error('Included spring lever source differs from its pinned fixture');
  const leverBefore=await execute([{action:'rules',rule:{action:'inspect'}}]);
  const leverSaved=await execute([{action:'rules',rule:{action:'edit',revision:leverBefore.rules!.revision,edits:[{kind:'save',reference:'lever',sequence:{id:'',name:'Native spring lever probe',interruption:0,repeat:false,program:JSON.stringify(leverSource)}}]}}]);
  const leverId=leverSaved.rules?.sequences.find(s=>s.name==='Native spring lever probe')?.id;if(!leverId)throw new Error('Spring lever caller was not saved');
  let leverAfter=await execute([{action:'rules',rule:{action:'play',revision:leverSaved.rules!.revision,target:leverId}}]);
  const leverDeadline=Date.now()+15000;
  while(!leverAfter.rules?.outcomes?.some(o=>o.sequenceId===leverId)&&Date.now()<leverDeadline){await new Promise(r=>setTimeout(r,100));leverAfter=await execute([{action:'rules',rule:{action:'inspect',target:leverId}}]);}
  const leverOutcome=leverAfter.rules?.outcomes?.find(o=>o.sequenceId===leverId),leverMembers=leverAfter.objects.filter(o=>!leverBefore.objects.some(before=>before.id===o.id)).map(o=>o.id);
  if(leverOutcome?.phase!=='completed'||leverMembers.length!==2||leverMembers.some(id=>connectedIds.includes(id)))throw new Error('Spring lever module did not complete with fresh members: '+JSON.stringify(leverOutcome));
  const leverFacts=[];for(const id of leverMembers){const read=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection',version:1,arguments:{target:id}}}]);leverFacts.push(read);}
  const leverOwners=leverFacts.filter(f=>(f.catalog?.value as {configured:boolean}).configured);
  if(leverOwners.length!==1||!leverMembers.includes((leverOwners[0].catalog?.value as {connected:string}).connected))throw new Error('Program-created hinge does not connect the new members');
  const selectionBefore=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'room.selection',version:1}}]);
  if(!selectionBefore.constructionSelection||selectionBefore.constructionSelection.members.length)throw new Error('Native construction selection was not initially empty');
  const selectionFirst=await execute([{action:'execution',execution:{operation:'start',call:{id:'room.selection.set',version:1,arguments:{stateId:selectionBefore.constructionSelection.stateId,members:[leverMembers[0]],collecting:false}}}}]);
  const selectionBoth=await execute([{action:'execution',execution:{operation:'start',call:{id:'room.selection.set',version:1,arguments:{stateId:selectionFirst.constructionSelection!.stateId,members:leverMembers,collecting:false}}}}]);
  const selectionRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'room.selection',version:1}}]);
  if(!isDeepStrictEqual(selectionRead.catalog?.value,{stateId:selectionBoth.constructionSelection!.stateId,members:leverMembers,collecting:false}))throw new Error('Native fact and inline construction selection differ');
  const selectionLocated=await execute([{action:'inspect',target:leverMembers[0]}]);if(selectionLocated.selectedId!==leverMembers[0])throw new Error('Locate did not focus the requested construction member');
  const captureMembers=[],captureFacts=[];
  for(let i=0;i<leverMembers.length;i++){
   const fact=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.definition',version:1,arguments:{target:leverMembers[i]}}}]);
   captureFacts.push(fact);captureMembers.push({target:leverMembers[i],slot:'piece_'+(i+1),revision:(fact.catalog?.value as {revision:number}).revision});
  }
  const captureArguments=constructionCaptureCall(selectionLocated.constructionSelection!,selectionLocated.objects).arguments;
  if(!isDeepStrictEqual(captureArguments.members,captureMembers))throw new Error('Book selection draft differs from current native member facts');
  const captureSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Save construction',offset:0}}]);
  const captureDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'program.module.captureConstruction',version:1}}]);
  let captureAfter=await execute([{action:'execution',execution:{operation:'start',call:{id:'program.module.captureConstruction',version:1,arguments:captureArguments}}}]);
  const captureRun=captureAfter.execution?.selected?.id;if(!captureRun)throw new Error('Capture did not return a run identity');
  const captureDeadline=Date.now()+15000;
  while(captureAfter.execution?.selected?.phase!=='completed'&&Date.now()<captureDeadline){await new Promise(r=>setTimeout(r,100));captureAfter=await execute([{action:'execution',execution:{operation:'inspect',runId:captureRun}}]);}
  const capturedHash=captureAfter.execution?.selected?.output?.hash;if(typeof capturedHash!=='string')throw new Error('Capture did not publish a reusable module: '+JSON.stringify(captureAfter.execution?.selected));
  const capturedRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'modules',capability:capturedHash,version:1}}]);
  const capturedModule=capturedRead.catalog?.definition as {program:{functions:{name:string;body:{arguments:Record<string,unknown>}[]}[]}};
  if(!capturedModule||leverMembers.some(id=>JSON.stringify(capturedModule).includes(id)))throw new Error('Captured source retained original object identities');
  const movementBefore=capturedRead;
  const movementShown=await execute([{action:'execution',execution:{operation:'start',call:{id:'room.selection.manipulate',version:1,arguments:{stateId:selectionBoth.constructionSelection!.stateId,members:leverMembers,visible:true}}}}]);
  if(!movementShown.constructionManipulation?.visible||movementShown.constructionManipulation.holding)throw new Error('Native construction handle was not shown idle');
  const movementRead=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'room.selection.manipulation',version:1}}]);
  if(!isDeepStrictEqual(movementRead.catalog?.value,movementShown.constructionManipulation))throw new Error('Move handle fact differs from the inline observation');
  const movementFacts=[];for(const target of leverMembers)movementFacts.push(await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.placement',version:1,arguments:{target}}}]));
  const movementOrigin=movementFacts[0].catalog?.value as {position:{x:number;y:number;z:number};rotation:{x:number;y:number;z:number;w:number};scale:number};
  const movementArguments={members:movementFacts.map(f=>{const v=f.catalog?.value as {target:string;revision:number};return {target:v.target,revision:v.revision};}),position:{x:movementOrigin.position.x+.2,y:movementOrigin.position.y+.1,z:movementOrigin.position.z+.1},rotation:{x:0,y:Math.SQRT1_2,z:0,w:Math.SQRT1_2},scale:1.2};
  const movementSearch=await execute([{action:'catalog',catalog:{operation:'search',query:'Move, turn or resize a construction',offset:0}}]);
  const movementDefinition=await execute([{action:'catalog',catalog:{operation:'inspect',capability:'object.layout.transform',version:1}}]);
  const movementTransformed=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.layout.transform',version:1,arguments:movementArguments}}}]);
  if(movementTransformed.execution?.selected?.phase!=='completed'||(movementTransformed.execution.selected.output as {count:number}).count!==2)throw new Error('Native group transform did not complete');
  const movementAfterFacts=[];for(const target of leverMembers)movementAfterFacts.push(await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.placement',version:1,arguments:{target}}}]));
  for(let i=0;i<2;i++){const before=movementFacts[i].catalog?.value as typeof movementOrigin,after=movementAfterFacts[i].catalog?.value as typeof movementOrigin;if(Math.abs(after.scale-before.scale*1.2)>.0001)throw new Error('Group transform lost a member scale');}
  const movedOrigin=(movementAfterFacts[0].catalog?.value as typeof movementOrigin).position;if(Math.hypot(movedOrigin.x-movementArguments.position.x,movedOrigin.y-movementArguments.position.y,movedOrigin.z-movementArguments.position.z)>.0001)throw new Error('Group transform pivot was not placed');
  const movementUndo=await execute([{action:'undo'}]);
  for(let i=0;i<2;i++){const actual=movementUndo.objects.find(o=>o.id===leverMembers[i])!,expected=movementFacts[i].catalog?.value as typeof movementOrigin;if(Math.hypot(actual.position.x-expected.position.x,actual.position.y-expected.position.y,actual.position.z-expected.position.z)>.0001||Math.abs(actual.scale-expected.scale)>.0001)throw new Error('One group Undo did not restore both members');}
  const movementHidden=await execute([{action:'execution',execution:{operation:'start',call:{id:'room.selection.manipulate',version:1,arguments:{stateId:movementUndo.constructionSelection!.stateId,members:leverMembers,visible:false}}}}]);if(movementHidden.constructionManipulation?.visible)throw new Error('Move handle did not close');
  const currentCaptureSource=insertProgramCapability(JSON.stringify({version:2,entry:'main',resources:[],functions:[{name:'main',returns:'void',parameters:[],locals:[],body:[]}]}),{id:'program.module.captureConstruction',version:1,arguments:{...captureArguments,members:captureMembers.map(m=>({...m,revision:1}))}},{kind:'current',fields:captureMembers.map((_,i)=>`members.${i}.revision`)});
  const currentCaptureSaved=await execute([{action:'rules',rule:{action:'edit',revision:lease.state().rules!.revision,edits:[{kind:'save',reference:'capture_current',sequence:{id:'',name:'Native current capture probe',interruption:0,repeat:false,program:JSON.stringify(currentCaptureSource)}}]}}]);
  const currentCaptureId=currentCaptureSaved.rules?.sequences.find(s=>s.name==='Native current capture probe')?.id;if(!currentCaptureId)throw new Error('Current-member capture caller was not saved');
  let currentCaptureAfter=await execute([{action:'rules',rule:{action:'play',revision:currentCaptureSaved.rules!.revision,target:currentCaptureId}}]);
  const currentCaptureDeadline=Date.now()+15000;
  while(!currentCaptureAfter.rules?.outcomes?.some(o=>o.sequenceId===currentCaptureId)&&Date.now()<currentCaptureDeadline){await new Promise(r=>setTimeout(r,100));currentCaptureAfter=await execute([{action:'rules',rule:{action:'inspect',target:currentCaptureId}}]);}
  const currentCaptureOutcome=currentCaptureAfter.rules?.outcomes?.find(o=>o.sequenceId===currentCaptureId);
  if(currentCaptureOutcome?.phase!=='completed')throw new Error('Visible current-member reads did not complete native capture: '+JSON.stringify(currentCaptureOutcome));
  await writeFile(join(directory,'current-members-program.json'),JSON.stringify({source:currentCaptureSource,saved:currentCaptureSaved,after:currentCaptureAfter,outcome:currentCaptureOutcome,hash:capturedHash,placeholderRevisions:captureMembers.map(()=>1),actualRevisions:captureMembers.map(m=>m.revision)},null,2));
  const leverUndo=await execute([{action:'undo'}]);if(leverUndo.constructionSelection?.members.length||leverUndo.constructionSelection?.stateId===selectionBoth.constructionSelection!.stateId)throw new Error('Deleting original members retained a stale selection');if(leverMembers.some(id=>leverUndo.objects.some(o=>o.id===id)))throw new Error('Program-created lever was not one Undo');
  const rebuiltArgs=structuredClone(capturedModule.program.functions.find(f=>f.name==='create')!.body[0].arguments);
  const rebuilt=await execute([{action:'execution',execution:{operation:'start',call:{id:'object.batch.create',version:1,arguments:rebuiltArgs}}}]);
  const rebuiltIds=rebuilt.execution?.selected?.output?.objectIds;
  if(!Array.isArray(rebuiltIds)||rebuiltIds.length!==2||rebuiltIds.some(id=>typeof id!=='string'||leverMembers.includes(id)))throw new Error('Captured construction did not survive removal of originals');
  const rebuiltHinges=[];for(const id of rebuiltIds){const read=await execute([{action:'catalog',catalog:{operation:'inspect',category:'facts',capability:'object.connection',version:1,arguments:{target:id as string}}}]);rebuiltHinges.push(read);}
  const rebuiltOwner=rebuiltHinges.find(r=>(r.catalog?.value as {configured:boolean}).configured);
  if(!rebuiltOwner||!rebuiltIds.includes((rebuiltOwner.catalog?.value as {connected:string}).connected))throw new Error('Rebuilt hinge did not bind its fresh members');
  const rebuiltUndo=await execute([{action:'undo'}]);if(rebuiltIds.some(id=>rebuiltUndo.objects.some(o=>o.id===id)))throw new Error('Captured construction did not keep one Undo');
  await writeFile(join(directory,'construction-capture.json'),JSON.stringify({boundary:'Real Unity shared transport and module library; no headset or provider proof.',arguments:captureArguments,facts:captureFacts,before:selectionLocated,search:captureSearch,definition:captureDefinition,captured:captureAfter,module:capturedRead,originalsRemoved:leverUndo,rebuilt,connections:rebuiltHinges,undo:rebuiltUndo},null,2));
  await writeFile(join(directory,'construction-movement.json'),JSON.stringify({boundary:'Real Unity native handle visibility/facts, group transform and one Undo. Physical grip is verified separately in PlayMode; no headset/provider proof.',before:movementBefore,shown:movementShown,read:movementRead,facts:movementFacts,search:movementSearch,definition:movementDefinition,arguments:movementArguments,transformed:movementTransformed,afterFacts:movementAfterFacts,undo:movementUndo,hidden:movementHidden},null,2));
  await writeFile(join(directory,'construction-selection.json'),JSON.stringify({boundary:'Real Unity room selection, fact, locate and capture states; browser replay is separate, no physical headset proof.',before:selectionBefore,first:selectionFirst,both:selectionBoth,read:selectionRead,located:selectionLocated,definition:captureDefinition,facts:captureFacts,captured:captureAfter,removed:leverUndo},null,2));
  let captureRemoved=await execute([{action:'execution',execution:{operation:'start',call:{id:'program.module.remove',version:1,arguments:{hash:capturedHash}}}}]);
  const removeDeadline=Date.now()+15000;while(captureRemoved.execution?.selected?.phase!=='completed'&&Date.now()<removeDeadline){await new Promise(r=>setTimeout(r,100));captureRemoved=await execute([{action:'execution',execution:{operation:'inspect',runId:captureRemoved.execution!.selected!.id}}]);}
  if(captureRemoved.execution?.selected?.phase!=='completed')throw new Error('Captured probe module was not cleaned up');
  await execute([{action:'rules',rule:{action:'edit',revision:lease.state().rules!.revision,edits:[{kind:'delete',target:leverId},{kind:'delete',target:currentCaptureId}]}}]);
  await writeFile(join(directory,'program-spring-lever.json'),JSON.stringify({boundary:'Real Unity runtime and shared transport. Physics tested in PlayMode; no headset or provider proof.',source:leverSource,module:leverModule,saved:leverSaved,after:leverAfter,facts:leverFacts,undo:leverUndo,outcome:leverOutcome},null,2));
  outcome={constructionMovement:{sharedHandleTransformAndOneUndoVerified:true},constructionSelection:{sharedStateFactLocateCaptureAndPruneVerified:true},currentMembers:{visibleReadsAndIndexedGuardsVerified:true,program:currentCaptureId},constructionCapture:{hash:capturedHash,survivedOriginalRemovalAndInternalHingeAndUndoVerified:true},connectedBlueprint:{identitiesInternalHingeAndSingleUndoVerified:true},leverModule:{hash:leverHash,program:leverId,includedSourceAndNativeCreationVerified:true},drawingTip:{tipHash,configurationReadbackAndUndoVerified:true},surface:{chalkHash,stroke,toolAndInkReadEraseUndoVerified:true},watch:{moduleHash,program:watcherId,includedSourceAndNativeRearmVerified:true},composition:{program:compositionId,outcome:compositionOutcome,buildCaptureMoveResetAndUndoVerified:true},structures:{captureReceipt:structureAfter.execution?.selected,liveDisplacementResetAndUndoVerified:true},batch:{createReceipt:batchAfter.execution?.selected,identitiesAndSingleUndoVerified:true},layout:{applyReceipt:layoutAfter.execution?.selected,liveReadAndSingleUndoVerified:true},template:{hash:templateArgs.templateHash,createReceipt:templateAfter.execution?.selected,componentsAndSingleUndoVerified:true},createdId:target,createReceipt:selected,paintVerified:true,undoPaintVerified:true,undoCreateVerified:true,diagnostics:diagnostic.catalog.value,lathe:{createReceipt:lathe.execution?.selected,profile:value,editAndUndoVerified:true},collision:{summary:summaryValue,editAndUndoVerified:true},latheCycles:cycle+1};
  }
 }
 await writeFile(join(directory,'journey.json'),JSON.stringify({version:1,boundary:'Real Unity Editor app and shared room protocol; no Quest input, WebView, scan or Store proof',providerUsed:!!prompt,initial,observations,outcome},null,2));
 console.log(JSON.stringify({providerUsed:!!prompt,observations:observations.length,output:join(directory,'journey.json')}));
}catch(error){transport.checkHealth();throw error;}finally{await transport.close();}
