-keep class com.maestro.quest.browser.BookWebView { public *; }
-keep class com.maestro.quest.browser.ModelPicker { public *; }
-keep class com.tlab.webkit.BaseOffscreenFragment { public *; }
-keep class com.robot9.shared.SharedTexture { *; }
-keep class com.maestro.quest.browser.MotionBatchPicker { public *; }
-keep class com.maestro.quest.browser.WorkspaceExports { public *; }
-keep class com.maestro.quest.browser.WorkspacePicker { public *; }
-keep class com.maestro.quest.browser.DocumentPicker { public *; }
-keep class com.maestro.quest.browser.AudioPicker { public *; }
